#ifndef KMagicAttribH
#define KMagicAttribH

//#define	INVALID_ATTRIB	-1
// 枚举类型最后一个字母表示该数值的类型，v为整型，直接加的点数，p为百分比，b为布尔型
enum MAGIC_ATTRIB
{
//改变技能的属性
/*0  */	magic_skill_begin,
/*1  */	magic_skill_cost_v,								// 消耗MANA
/*2  */	magic_skill_costtype_v,							//	
/*3  */	magic_skill_mintimepercast_v,					// 每次发魔法的间隔时间
/*4  */	magic_skill_misslenum_v,						// 
/*5  */	magic_skill_misslesform_v,		
/*6  */	magic_skill_param1_v,		
/*7  */	magic_skill_param2_v,
/*8  */	magic_skill_attackradius,
/*9  */	magic_skill_reserve2,
/*10 */	magic_skill_reserve3,
/*11 */	magic_skill_reserve4,
/*12 */	magic_skill_eventskilllevel,
/*13 */	magic_skill_end,
/*14 */	magic_missle_begin,
/*15 */	magic_missle_movekind_v,						// 子弹格式
/*16 */	magic_missle_speed_v,							// 子弹飞行速度
/*17 */	magic_missle_lifetime_v,						// 子弹的生命时间
/*18 */	magic_missle_height_v,							// 子弹的高度
/*19 */	magic_missle_damagerange_v,						// 子弹破坏范围
/*20 */	magic_missle_radius_v,							// 子弹飞行半径
/*21 */	magic_missle_reserve1,
/*22 */	magic_missle_reserve2,
/*23 */	magic_missle_reserve3,
/*24 */	magic_missle_reserve4,
/*25 */	magic_missle_reserve5,
/*26 */	magic_missle_end,
/*27 */	magic_item_begin,
/*28 */	magic_weapondamagemin_v,
/*29 */	magic_weapondamagemax_v,
/*30 */	magic_armordefense_v,
/*31 */	magic_durability_v,
/*32 */	magic_requirestr,
/*33 */	magic_requiredex,
/*34 */	magic_requirevit,
/*35 */	magic_requireeng,
/*36 */	magic_requirelevel,
/*37 */	magic_requireseries,
/*38 */	magic_requiresex,
/*39 */	magic_requiremenpai,
/*40 */	magic_weapondamageenhance_p,
/*41 */	magic_armordefenseenhance_p,
/*42 */	magic_requirementreduce_p,
/*43 */	magic_indestructible_b,
/*44 */	magic_item_reserve1,
/*45 */	magic_item_reserve2,
/*46 */	magic_require_translife,
/*47 */	magic_require_fortune_value,
/*48 */	magic_item_reserve5,
/*49 */	magic_item_reserve6,
/*50 */	magic_item_reserve7,
/*51 */	magic_item_reserve8,
/*52 */	magic_item_reserve9,
/*53 */	magic_item_reserve10,
/*54 */	magic_item_end,
/*55 */	magic_damage_begin,		
/*56 */	magic_attackrating_v,
/*57 */	magic_attackrating_p,
/*58 */	magic_ignoredefense_p,
/*59 */	magic_physicsdamage_v,
/*60 */	magic_colddamage_v,
/*61 */	magic_firedamage_v,
/*62 */	magic_lightingdamage_v,
/*63 */	magic_poisondamage_v,
/*64 */	magic_magicdamage_v,
/*65 */	magic_physicsenhance_p,
/*66 */	magic_steallife_p,
/*67 */	magic_stealmana_p,
/*68 */	magic_stealstamina_p,
/*69 */	magic_knockback_p,
/*70 */	magic_deadlystrike_p,
/*71 */	magic_fatallystrike_p,
/*72 */	magic_stun_p,
/*73 */	magic_damage_reserve1,
/*74 */	magic_damage_reserve2,
/*75 */	magic_damage_reserve3,
/*76 */	magic_damage_reserve4,
/*77 */	magic_damage_reserve5,
/*78 */	magic_damage_reserve6,
/*79 */	magic_damage_reserve7,
/*80 */	magic_damage_reserve8,
/*81 */	magic_damage_reserve9,
/*82 */	magic_damage_reserve10,
/*83 */	magic_damage_end,
/*84 */	magic_normal_begin,
/*85 */	magic_lifemax_v,
/*86 */	magic_lifemax_p,
/*87 */	magic_life_v,
/*88 */	magic_lifereplenish_v,
/*89 */	magic_manamax_v,
/*90 */	magic_manamax_p,
/*91 */	magic_mana_v,
/*92 */	magic_manareplenish_v,
/*93 */	magic_staminamax_v,
/*94 */	magic_staminamax_p,
/*95 */	magic_stamina_v,
/*96 */	magic_staminareplenish_v,
/*97 */	magic_strength_v,
/*98 */	magic_dexterity_v,
/*99 */	magic_vitality_v,
/*100*/	magic_energy_v,
/*101*/	magic_poisonres_p,
/*102*/	magic_fireres_p,
/*103*/	magic_lightingres_p,
/*104*/	magic_physicsres_p,
/*105*/	magic_coldres_p,
/*106*/	magic_freezetimereduce_p,
/*107*/	magic_burntimereduce_p,
/*108*/	magic_poisontimereduce_p,
/*109*/	magic_poisondamagereduce_v,
/*110*/	magic_stuntimereduce_p,
/*111*/	magic_fastwalkrun_p,
/*112*/	magic_visionradius_p,
/*113*/	magic_fasthitrecover_v,
/*114*/	magic_allres_p,
/*115*/	magic_attackspeed_v,
/*116*/	magic_castspeed_v,
/*117*/	magic_meleedamagereturn_v,
/*118*/	magic_meleedamagereturn_p,
/*119*/	magic_rangedamagereturn_v,
/*120*/	magic_rangedamagereturn_p,
/*121*/	magic_addphysicsdamage_v,
/*122*/	magic_addfiredamage_v,
/*123*/	magic_addcolddamage_v,
/*124*/	magic_addlightingdamage_v,
/*125*/	magic_addpoisondamage_v,
/*126*/	magic_addphysicsdamage_p,
/*127*/	magic_slowmissle_b,
/*128*/	magic_changecamp_b,
/*129*/	magic_physicsarmor_v,
/*130*/	magic_coldarmor_v,
/*131*/	magic_firearmor_v,
/*132*/	magic_poisonarmor_v,
/*133*/	magic_lightingarmor_v,
/*134*/	magic_damage2addmana_p,
/*135*/	magic_lucky_v,
/*136*/	magic_steallifeenhance_p,
/*137*/	magic_stealmanaenhance_p,
/*138*/	magic_stealstaminaenhance_p,
/*139*/	magic_allskill_v,
/*140*/	magic_metalskill_v,
/*141*/	magic_woodskill_v,
/*142*/	magic_waterskill_v,
/*143*/	magic_fireskill_v,
/*144*/	magic_earthskill_v,
/*145*/	magic_knockbackenhance_p,
/*146*/	magic_deadlystrikeenhance_p,
/*147*/	magic_stunenhance_p,
/*148*/	magic_badstatustimereduce_v,
/*149*/	magic_manashield_p,
/*150*/	magic_adddefense_v,
/*151*/	magic_adddefense_p,
/*152*/	magic_fatallystrikeenhance_p,
/*153*/	magic_lifepotion_v,
/*154*/	magic_manapotion_v,
/*155*/	magic_physicsresmax_p,
/*156*/	magic_coldresmax_p,
/*157*/	magic_fireresmax_p,
/*158*/	magic_lightingresmax_p,
/*159*/	magic_poisonresmax_p,
/*160*/	magic_allresmax_p,
/*161*/	magic_coldenhance_p,
/*162*/	magic_fireenhance_p,
/*163*/	magic_lightingenhance_p,
/*164*/	magic_poisonenhance_p,
/*165*/	magic_magicenhance_p,
/*166*/	magic_attackratingenhance_v,
/*167*/	magic_attackratingenhance_p,
/*168*/ magic_addphysicsmagic_v,
/*169*/ magic_addcoldmagic_v,
/*170*/ magic_addfiremagic_v,
/*171*/ magic_addlightingmagic_v,
/*172*/ magic_addpoisonmagic_v,
/*173*/ magic_fatallystrikeres_p,
/*176*/ magic_expenhance_p=176,
/*181*/ magic_dynamicmagicshield_v=181,
/*187*/ magic_addstealfeatureskill=187,
/*188*/ magic_lucky_v_partner,
/*190*/ magic_lifereplenish_p=190,
/*191*/ magic_ignoreskill_p,
/*192*/ magic_returnskill_p,
/*193*/ magic_poisondamagereturn_v,
/*194*/ magic_poisondamagereturn_p,
/*195*/ magic_autoreplyskill,
/*200*/ magic_hide=200,
/*202*/ magic_poison2decmana_p=202,
/*205*/ magic_returnres_p=205,
/*218*/ magic_sorbdamage_p=218,
/*219*/ magic_anti_hitrecover,
/*220*/ magic_anti_stuntimereduce_p,
/*221*/ magic_anti_poisonres_p,
/*222*/ magic_anti_fireres_p,
/*223*/ magic_anti_lightingres_p,
/*224*/ magic_anti_physicsres_p,
/*225*/ magic_anti_coldres_p,
/*226*/ magic_block_rate,
/*227*/ magic_enhancehit_rate,
/*228*/ magic_poisonres_yan_p,
/*229*/ magic_lightingres_yan_p,
/*230*/ magic_fireres_yan_p,
/*231*/ magic_physicsres_yan_p,
/*232*/ magic_coldres_yan_p,
/*233*/ magic_lifemax_yan_v,
/*234*/ magic_lifemax_yan_p,
/*235*/ magic_manamax_yan_v,
/*236*/ magic_manamax_yan_p,
/*237*/ magic_sorbdamage_yan_p,
/*238*/ magic_fastwalkrun_yan_p,
/*239*/ magic_attackspeed_yan_v,
/*240*/ magic_castspeed_yan_v,
/*241*/ magic_allres_yan_p,
/*242*/ magic_anti_maxres_p,
/*243*/ magic_skill_enhance,
/*244*/ magic_magicdamage_p,
/*245*/ magic_fasthitrecover_yan_v,
/*246*/ magic_five_elements_enhance_v,
/*247*/ magic_five_elements_resist_v,
/*248*/ magic_manareplenish_p,
/*249*/ magic_add_damage_p,
/*254*/ magic_not_add_pkvalue_p=254,
/*255*/ magic_add_boss_damage,
/*256*/ magic_pk_punish_weaken,
/*257*/ magic_pk_punish_enhance,
/*258*/ magic_anti_poisontimereduce_p,
/*259*/ magic_do_hurt_p,
/*260*/ magic_anti_do_hurt_p,
/*261*/ magic_do_stun_p,
/*262*/ magic_anti_do_stun_p,
/*263*/ magic_anti_physicsres_yan_p,
/*264*/ magic_anti_poisonres_yan_p,
/*265*/ magic_anti_coldres_yan_p,
/*266*/ magic_anti_fireres_yan_p,
/*267*/ magic_anti_lightingres_yan_p,
/*268*/ magic_anti_allres_yan_p,
/*269*/ magic_anti_sorbdamage_yan_p,
/*270*/ magic_anti_block_rate,
/*271*/ magic_anti_enhancehit_rate,
/*275*/ magic_enhancehiteffect_rate=275,

/*end*/	magic_normal_end,
};

extern const char MAGIC_ATTRIB_STRING[magic_normal_end + 1][100] ; 


#endif
