#!/usr/bin/env python3
"""Generate Protocol V2 code from proto/jx/*.proto.

  Go       : protoc + protoc-gen-go        -> services/pkg/jxpb/*.pb.go
  GDScript : godobuf (Godot headless)      -> client/proto/jx_pb.gd   (from a merged single file)
  C++      : generated at build time by CMake (server/proto), nothing to do here.

Generated Go and GDScript files are committed so that `go build` and the Godot project work
without protoc.  Run after every .proto change:  python tools/gen_proto.py [--go] [--gd]

Tool discovery (override with env vars):
  JX_PROTOC   protoc executable   (default: build/*/vcpkg_installed/*/tools/protobuf/protoc)
  JX_GODOT    Godot executable    (default: "godot" on PATH, then the winget install dir)
"""
from __future__ import annotations

import argparse
import glob
import os
import re
import shutil
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROTO_DIR = os.path.join(ROOT, "proto")
PROTO_FILES = sorted(glob.glob(os.path.join(PROTO_DIR, "jx", "*.proto")))
GO_MODULE = "github.com/JXGAME04/DUANGODOT/next/services"
SERVICES_DIR = os.path.join(ROOT, "services")
CLIENT_DIR = os.path.join(ROOT, "client")
EXE = ".exe" if os.name == "nt" else ""


def find_protoc() -> str:
    cand = os.environ.get("JX_PROTOC")
    if cand and os.path.exists(cand):
        return cand
    pattern = os.path.join(ROOT, "build", "*", "vcpkg_installed", "*", "tools", "protobuf", "protoc" + EXE)
    found = sorted(glob.glob(pattern))
    if found:
        return found[0]
    on_path = shutil.which("protoc")
    if on_path:
        return on_path
    sys.exit("protoc not found: configure the C++ build first (cmake --preset ...) or set JX_PROTOC")


def find_godot() -> str:
    cand = os.environ.get("JX_GODOT")
    if cand and os.path.exists(cand):
        return cand
    for name in ("godot_console", "godot", "godot4"):
        on_path = shutil.which(name)
        if on_path:
            return on_path
    if os.name == "nt":
        pkg = os.path.join(os.environ.get("LOCALAPPDATA", ""), "Microsoft", "WinGet", "Packages")
        found = sorted(glob.glob(os.path.join(pkg, "GodotEngine.GodotEngine_*", "Godot_v*_win64_console.exe")))
        if found:
            return found[-1]
    sys.exit("Godot not found: install Godot 4 or set JX_GODOT")


def go_bin_dir() -> str:
    try:
        gopath = subprocess.check_output(["go", "env", "GOPATH"], text=True).strip()
    except (OSError, subprocess.CalledProcessError):
        return ""
    return os.path.join(gopath, "bin")


def gen_go(protoc: str) -> None:
    env = dict(os.environ)
    gobin = go_bin_dir()
    if gobin:
        env["PATH"] = gobin + os.pathsep + env.get("PATH", "")
    if not shutil.which("protoc-gen-go", path=env["PATH"]):
        sys.exit("protoc-gen-go not found: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest")
    out_dir = os.path.join(SERVICES_DIR, "pkg", "jxpb")
    os.makedirs(out_dir, exist_ok=True)
    for old in glob.glob(os.path.join(out_dir, "*.pb.go")):
        os.remove(old)
    cmd = [protoc, "-I", PROTO_DIR, "--go_out", SERVICES_DIR, "--go_opt", "module=" + GO_MODULE] + PROTO_FILES
    subprocess.check_call(cmd, env=env)
    print("go   :", ", ".join(os.path.basename(p) for p in glob.glob(os.path.join(out_dir, "*.pb.go"))))


HEADER_RE = re.compile(r"^\s*(syntax|package|option|import)\b")


def merge_protos(dest: str) -> None:
    """godobuf works on one file without imports; all our files share package jx.pb so a plain
    concatenation (minus syntax/package/option/import lines) is an equivalent definition."""
    parts = ["// GENERATED by tools/gen_proto.py from proto/jx/*.proto - do not edit.",
             'syntax = "proto3";', ""]
    for path in PROTO_FILES:
        parts.append("// ---- " + os.path.basename(path) + " ----")
        with open(path, encoding="utf-8") as f:
            for line in f:
                if HEADER_RE.match(line):
                    continue
                parts.append(line.rstrip("\n"))
        parts.append("")
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    with open(dest, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(parts) + "\n")


def gen_gd(godot: str) -> None:
    merged = os.path.join(CLIENT_DIR, "proto", "jx.proto")
    output = os.path.join(CLIENT_DIR, "proto", "jx_pb.gd")
    merge_protos(merged)
    cmd = [godot, "--headless", "--path", CLIENT_DIR, "-s", "res://addons/godobuf/godobuf_cmdln.gd",
           "--input=" + merged, "--output=" + output]
    res = subprocess.run(cmd, text=True, capture_output=True)
    sys.stdout.write(res.stdout)
    if res.returncode != 0 or not os.path.exists(output) or "Compilation failed" in res.stdout + res.stderr:
        sys.stderr.write(res.stderr)
        sys.exit("godobuf generation failed")
    print("gd   :", os.path.relpath(output, ROOT))


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--go", action="store_true", help="generate Go only")
    ap.add_argument("--gd", action="store_true", help="generate GDScript only")
    args = ap.parse_args()
    do_go = args.go or not args.gd
    do_gd = args.gd or not args.go
    if not PROTO_FILES:
        sys.exit("no .proto files found under " + PROTO_DIR)
    print("proto:", ", ".join(os.path.basename(p) for p in PROTO_FILES))
    if do_go:
        gen_go(find_protoc())
    if do_gd:
        gen_gd(find_godot())


if __name__ == "__main__":
    main()
