#!/usr/bin/env python3
"""Writes server/zone/include/jx/zone/KMagicAttribId.h from docs/linux/jx_linux_magicattrib.tsv:
the MAGIC_ATTRIB ids of the JX2 server (KMagicDesc ctor 0x080724B0, docs/LINUX-SERVER.md §9) as
one enum, so the zone names an attribute the way the tables and the binary do
(`magic_lifemax_v`, `magic_weapondamagemin_v`...).  Run again whenever the TSV changes:

    python tools/gen_magic_ids.py
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TSV = os.path.join(ROOT, "docs", "linux", "jx_linux_magicattrib.tsv")
OUT = os.path.join(ROOT, "server", "zone", "include", "jx", "zone", "KMagicAttribId.h")


def main():
    rows = []
    for line in open(TSV, encoding="utf-8"):
        parts = line.rstrip("\n").split("\t")
        if len(parts) < 2 or not parts[0].isdigit():
            continue
        name = parts[1].strip()
        if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", name):
            continue
        rows.append((int(parts[0]), name))
    rows.sort()
    out = [
        "// Generated by tools/gen_magic_ids.py from docs/linux/jx_linux_magicattrib.tsv - do not edit.",
        "// MAGIC_ATTRIB of the JX2 server (KMagicDesc ctor jx_linux_y 0x080724B0): the id every item",
        "// table, skill table and KNpcAttribModify::ProcessFunc[] uses (docs/LINUX-SERVER.md §9, §10).",
        "#pragma once",
        "",
        "namespace jx::zone {",
        "",
        "enum KMagic : int {",
    ]
    for id_, name in rows:
        out.append(f"    magic_{name} = {id_},")
    out.append(f"    magic_id_count = {rows[-1][0] + 1},")
    out.append("};")
    out.append("")
    out.append("// The name of an id as the tables spell it (\"lifemax_v\"), \"\" when unknown.")
    out.append("[[nodiscard]] const char* magic_attrib_name(int id) noexcept;")
    out.append("")
    out.append("} // namespace jx::zone")
    out.append("")
    open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(out))
    # the name table, in the .cpp beside KNpcAttribModify
    cpp = os.path.join(ROOT, "server", "zone", "src", "KMagicAttribId.cpp")
    lines = [
        "// Generated by tools/gen_magic_ids.py from docs/linux/jx_linux_magicattrib.tsv - do not edit.",
        '#include "jx/zone/KMagicAttribId.h"',
        "",
        "#include <array>",
        "#include <cstddef>",
        "",
        "namespace jx::zone {",
        "",
        "namespace {",
        f"constexpr std::array<const char*, {rows[-1][0] + 1}> kNames = [] {{",
        f"    std::array<const char*, {rows[-1][0] + 1}> n{{}};",
        "    for (auto& s : n) s = \"\";",
    ]
    for id_, name in rows:
        lines.append(f'    n[{id_}] = "{name}";')
    lines += [
        "    return n;",
        "}();",
        "} // namespace",
        "",
        "const char* magic_attrib_name(int id) noexcept",
        "{",
        "    return id >= 0 && id < static_cast<int>(kNames.size()) ? kNames[static_cast<std::size_t>(id)] : \"\";",
        "}",
        "",
        "} // namespace jx::zone",
        "",
    ]
    open(cpp, "w", encoding="utf-8", newline="\n").write("\n".join(lines))
    print(f"{len(rows)} ids -> {os.path.relpath(OUT, ROOT)}, {os.path.relpath(cpp, ROOT)}")


if __name__ == "__main__":
    main()
