// Client <-> gateway messages.  C2G = client to gateway, G2C = gateway to client.
// Some C2G messages are forwarded unchanged to the zone (see MsgId comments in msg.proto).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.4
// source: jx/client.proto

package jxpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// KNpc::m_Doing as far as clients need it.
type Action int32

const (
	Action_ACTION_STAND  Action = 0
	Action_ACTION_ATTACK Action = 1 // frames = swing length in logic frames (18 Hz), dir = facing, target
	Action_ACTION_HURT   Action = 2 // frames = hurt length (KNpc::DoHurt), pos = where the entity stands
	Action_ACTION_DEATH  Action = 3 // frames = death animation; the corpse keeps the last frame until despawn
	Action_ACTION_REVIVE Action = 4
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "ACTION_STAND",
		1: "ACTION_ATTACK",
		2: "ACTION_HURT",
		3: "ACTION_DEATH",
		4: "ACTION_REVIVE",
	}
	Action_value = map[string]int32{
		"ACTION_STAND":  0,
		"ACTION_ATTACK": 1,
		"ACTION_HURT":   2,
		"ACTION_DEATH":  3,
		"ACTION_REVIVE": 4,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_jx_client_proto_enumTypes[0].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_jx_client_proto_enumTypes[0]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{0}
}

type Hello struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"` // PROTOCOL_VERSION in msg.proto
	ClientVersion   string                 `protobuf:"bytes,2,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	Platform        string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"` // "windows", "linux", "android", ...
	DeviceId        string                 `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_jx_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{0}
}

func (x *Hello) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *Hello) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *Hello) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *Hello) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type HelloAck struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	ServerTimeMs    uint64                 `protobuf:"varint,2,opt,name=server_time_ms,json=serverTimeMs,proto3" json:"server_time_ms,omitempty"`
	ServerVersion   string                 `protobuf:"bytes,3,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	Sid             uint64                 `protobuf:"varint,4,opt,name=sid,proto3" json:"sid,omitempty"`                                 // session id, useful when reading logs
	AuthMode        string                 `protobuf:"bytes,5,opt,name=auth_mode,json=authMode,proto3" json:"auth_mode,omitempty"`        // "dev" (first login registers the account) or "strict" (registered accounts only)
	HeartbeatS      uint32                 `protobuf:"varint,6,opt,name=heartbeat_s,json=heartbeatS,proto3" json:"heartbeat_s,omitempty"` // the gateway drops a silent in-world session after this many seconds; ping more often
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HelloAck) Reset() {
	*x = HelloAck{}
	mi := &file_jx_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAck) ProtoMessage() {}

func (x *HelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAck.ProtoReflect.Descriptor instead.
func (*HelloAck) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{1}
}

func (x *HelloAck) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *HelloAck) GetServerTimeMs() uint64 {
	if x != nil {
		return x.ServerTimeMs
	}
	return 0
}

func (x *HelloAck) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *HelloAck) GetSid() uint64 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *HelloAck) GetAuthMode() string {
	if x != nil {
		return x.AuthMode
	}
	return ""
}

func (x *HelloAck) GetHeartbeatS() uint32 {
	if x != nil {
		return x.HeartbeatS
	}
	return 0
}

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // dev auth only; real auth uses tokens (phase 3)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_jx_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{2}
}

func (x *LoginReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        Result                 `protobuf:"varint,1,opt,name=result,proto3,enum=jx.pb.Result" json:"result,omitempty"`
	AccountId     uint64                 `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"` // human readable reason (field names must avoid protobuf keywords: godobuf)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRes) Reset() {
	*x = LoginRes{}
	mi := &file_jx_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRes) ProtoMessage() {}

func (x *LoginRes) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRes.ProtoReflect.Descriptor instead.
func (*LoginRes) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{3}
}

func (x *LoginRes) GetResult() Result {
	if x != nil {
		return x.Result
	}
	return Result_RESULT_OK
}

func (x *LoginRes) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *LoginRes) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type CharSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Level         uint32                 `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Series        uint32                 `protobuf:"varint,4,opt,name=series,proto3" json:"series,omitempty"`
	Sex           uint32                 `protobuf:"varint,5,opt,name=sex,proto3" json:"sex,omitempty"`
	Faction       uint32                 `protobuf:"varint,6,opt,name=faction,proto3" json:"faction,omitempty"`
	ZoneId        uint32                 `protobuf:"varint,7,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharSummary) Reset() {
	*x = CharSummary{}
	mi := &file_jx_client_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharSummary) ProtoMessage() {}

func (x *CharSummary) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharSummary.ProtoReflect.Descriptor instead.
func (*CharSummary) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{4}
}

func (x *CharSummary) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *CharSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CharSummary) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CharSummary) GetSeries() uint32 {
	if x != nil {
		return x.Series
	}
	return 0
}

func (x *CharSummary) GetSex() uint32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *CharSummary) GetFaction() uint32 {
	if x != nil {
		return x.Faction
	}
	return 0
}

func (x *CharSummary) GetZoneId() uint32 {
	if x != nil {
		return x.ZoneId
	}
	return 0
}

type CharListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharListReq) Reset() {
	*x = CharListReq{}
	mi := &file_jx_client_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharListReq) ProtoMessage() {}

func (x *CharListReq) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharListReq.ProtoReflect.Descriptor instead.
func (*CharListReq) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{5}
}

type CharListRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        Result                 `protobuf:"varint,1,opt,name=result,proto3,enum=jx.pb.Result" json:"result,omitempty"`
	Chars         []*CharSummary         `protobuf:"bytes,2,rep,name=chars,proto3" json:"chars,omitempty"`
	MaxChars      uint32                 `protobuf:"varint,3,opt,name=max_chars,json=maxChars,proto3" json:"max_chars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharListRes) Reset() {
	*x = CharListRes{}
	mi := &file_jx_client_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharListRes) ProtoMessage() {}

func (x *CharListRes) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharListRes.ProtoReflect.Descriptor instead.
func (*CharListRes) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{6}
}

func (x *CharListRes) GetResult() Result {
	if x != nil {
		return x.Result
	}
	return Result_RESULT_OK
}

func (x *CharListRes) GetChars() []*CharSummary {
	if x != nil {
		return x.Chars
	}
	return nil
}

func (x *CharListRes) GetMaxChars() uint32 {
	if x != nil {
		return x.MaxChars
	}
	return 0
}

type CharCreateReq struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Name   string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Series uint32                 `protobuf:"varint,2,opt,name=series,proto3" json:"series,omitempty"`
	Sex    uint32                 `protobuf:"varint,3,opt,name=sex,proto3" json:"sex,omitempty"`
	// The starting village the player picked (KUiSelNativePlace): the Id of Settings/NativePlaceList.ini,
	// which is the map id of the village (53 Ba Lang Huyen, 20 Giang Tan Thon...).  0 = not chosen.
	NativePlace   uint32 `protobuf:"varint,4,opt,name=native_place,json=nativePlace,proto3" json:"native_place,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharCreateReq) Reset() {
	*x = CharCreateReq{}
	mi := &file_jx_client_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharCreateReq) ProtoMessage() {}

func (x *CharCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharCreateReq.ProtoReflect.Descriptor instead.
func (*CharCreateReq) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{7}
}

func (x *CharCreateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CharCreateReq) GetSeries() uint32 {
	if x != nil {
		return x.Series
	}
	return 0
}

func (x *CharCreateReq) GetSex() uint32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *CharCreateReq) GetNativePlace() uint32 {
	if x != nil {
		return x.NativePlace
	}
	return 0
}

type CharCreateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        Result                 `protobuf:"varint,1,opt,name=result,proto3,enum=jx.pb.Result" json:"result,omitempty"`
	Summary       *CharSummary           `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharCreateRes) Reset() {
	*x = CharCreateRes{}
	mi := &file_jx_client_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharCreateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharCreateRes) ProtoMessage() {}

func (x *CharCreateRes) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharCreateRes.ProtoReflect.Descriptor instead.
func (*CharCreateRes) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{8}
}

func (x *CharCreateRes) GetResult() Result {
	if x != nil {
		return x.Result
	}
	return Result_RESULT_OK
}

func (x *CharCreateRes) GetSummary() *CharSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

type EnterWorldReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterWorldReq) Reset() {
	*x = EnterWorldReq{}
	mi := &file_jx_client_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterWorldReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterWorldReq) ProtoMessage() {}

func (x *EnterWorldReq) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterWorldReq.ProtoReflect.Descriptor instead.
func (*EnterWorldReq) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{9}
}

func (x *EnterWorldReq) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type EnterWorldRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        Result                 `protobuf:"varint,1,opt,name=result,proto3,enum=jx.pb.Result" json:"result,omitempty"`
	ZoneId        uint32                 `protobuf:"varint,2,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	ZoneName      string                 `protobuf:"bytes,3,opt,name=zone_name,json=zoneName,proto3" json:"zone_name,omitempty"`
	EntityId      uint64                 `protobuf:"varint,4,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"` // the entity that belongs to this client in the zone
	Pos           *Vec2                  `protobuf:"bytes,5,opt,name=pos,proto3" json:"pos,omitempty"`
	TickHz        uint32                 `protobuf:"varint,6,opt,name=tick_hz,json=tickHz,proto3" json:"tick_hz,omitempty"`
	MapId         uint32                 `protobuf:"varint,7,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"` // which map bundle to draw (0 = plain grid)
	SceneW        uint32                 `protobuf:"varint,8,opt,name=scene_w,json=sceneW,proto3" json:"scene_w,omitempty"`
	SceneH        uint32                 `protobuf:"varint,9,opt,name=scene_h,json=sceneH,proto3" json:"scene_h,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterWorldRes) Reset() {
	*x = EnterWorldRes{}
	mi := &file_jx_client_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterWorldRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterWorldRes) ProtoMessage() {}

func (x *EnterWorldRes) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterWorldRes.ProtoReflect.Descriptor instead.
func (*EnterWorldRes) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{10}
}

func (x *EnterWorldRes) GetResult() Result {
	if x != nil {
		return x.Result
	}
	return Result_RESULT_OK
}

func (x *EnterWorldRes) GetZoneId() uint32 {
	if x != nil {
		return x.ZoneId
	}
	return 0
}

func (x *EnterWorldRes) GetZoneName() string {
	if x != nil {
		return x.ZoneName
	}
	return ""
}

func (x *EnterWorldRes) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *EnterWorldRes) GetPos() *Vec2 {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *EnterWorldRes) GetTickHz() uint32 {
	if x != nil {
		return x.TickHz
	}
	return 0
}

func (x *EnterWorldRes) GetMapId() uint32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *EnterWorldRes) GetSceneW() uint32 {
	if x != nil {
		return x.SceneW
	}
	return 0
}

func (x *EnterWorldRes) GetSceneH() uint32 {
	if x != nil {
		return x.SceneH
	}
	return 0
}

type LeaveWorldReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveWorldReq) Reset() {
	*x = LeaveWorldReq{}
	mi := &file_jx_client_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveWorldReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveWorldReq) ProtoMessage() {}

func (x *LeaveWorldReq) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveWorldReq.ProtoReflect.Descriptor instead.
func (*LeaveWorldReq) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{11}
}

// Server authoritative movement: the client asks to move towards a target, the zone
// simulates and broadcasts EntityMove to everyone who can see the entity.
type MoveReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        *Vec2                  `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Seq           uint32                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"` // client sequence number, echoed in EntityMove for the own entity
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveReq) Reset() {
	*x = MoveReq{}
	mi := &file_jx_client_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveReq) ProtoMessage() {}

func (x *MoveReq) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveReq.ProtoReflect.Descriptor instead.
func (*MoveReq) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{12}
}

func (x *MoveReq) GetTarget() *Vec2 {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *MoveReq) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

// Basic melee attack on a target (KNpc::DoAttack).  The zone repeats the swing until the target
// dies, the player moves or the target leaves reach.
type AttackReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        uint64                 `protobuf:"varint,1,opt,name=target,proto3" json:"target,omitempty"`
	Seq           uint32                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttackReq) Reset() {
	*x = AttackReq{}
	mi := &file_jx_client_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttackReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackReq) ProtoMessage() {}

func (x *AttackReq) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackReq.ProtoReflect.Descriptor instead.
func (*AttackReq) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{13}
}

func (x *AttackReq) GetTarget() uint64 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *AttackReq) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

// An entity started an action (old NPC_HURT_SYNC / NPC_DEATH_SYNC / skill sync).
type EntityAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Action        Action                 `protobuf:"varint,2,opt,name=action,proto3,enum=jx.pb.Action" json:"action,omitempty"`
	Target        uint64                 `protobuf:"varint,3,opt,name=target,proto3" json:"target,omitempty"`
	Dir           uint32                 `protobuf:"varint,4,opt,name=dir,proto3" json:"dir,omitempty"`
	Frames        uint32                 `protobuf:"varint,5,opt,name=frames,proto3" json:"frames,omitempty"`
	Pos           *Vec2                  `protobuf:"bytes,6,opt,name=pos,proto3" json:"pos,omitempty"`
	Tick          uint64                 `protobuf:"varint,7,opt,name=tick,proto3" json:"tick,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityAction) Reset() {
	*x = EntityAction{}
	mi := &file_jx_client_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityAction) ProtoMessage() {}

func (x *EntityAction) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityAction.ProtoReflect.Descriptor instead.
func (*EntityAction) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{14}
}

func (x *EntityAction) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *EntityAction) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_ACTION_STAND
}

func (x *EntityAction) GetTarget() uint64 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *EntityAction) GetDir() uint32 {
	if x != nil {
		return x.Dir
	}
	return 0
}

func (x *EntityAction) GetFrames() uint32 {
	if x != nil {
		return x.Frames
	}
	return 0
}

func (x *EntityAction) GetPos() *Vec2 {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *EntityAction) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

// Life changed (damage / heal), sent to everyone who sees the entity.
type EntityLife struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Life          uint32                 `protobuf:"varint,2,opt,name=life,proto3" json:"life,omitempty"`
	LifeMax       uint32                 `protobuf:"varint,3,opt,name=life_max,json=lifeMax,proto3" json:"life_max,omitempty"`
	Delta         int32                  `protobuf:"varint,4,opt,name=delta,proto3" json:"delta,omitempty"` // negative = damage
	Source        uint64                 `protobuf:"varint,5,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityLife) Reset() {
	*x = EntityLife{}
	mi := &file_jx_client_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityLife) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityLife) ProtoMessage() {}

func (x *EntityLife) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityLife.ProtoReflect.Descriptor instead.
func (*EntityLife) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{15}
}

func (x *EntityLife) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *EntityLife) GetLife() uint32 {
	if x != nil {
		return x.Life
	}
	return 0
}

func (x *EntityLife) GetLifeMax() uint32 {
	if x != nil {
		return x.LifeMax
	}
	return 0
}

func (x *EntityLife) GetDelta() int32 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *EntityLife) GetSource() uint64 {
	if x != nil {
		return x.Source
	}
	return 0
}

type EntityInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	EntityType    EntityType             `protobuf:"varint,2,opt,name=entity_type,json=entityType,proto3,enum=jx.pb.EntityType" json:"entity_type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Pos           *Vec2                  `protobuf:"bytes,4,opt,name=pos,proto3" json:"pos,omitempty"`
	Target        *Vec2                  `protobuf:"bytes,5,opt,name=target,proto3" json:"target,omitempty"` // where it is currently moving to (== pos when idle)
	MoveSpeed     uint32                 `protobuf:"varint,6,opt,name=move_speed,json=moveSpeed,proto3" json:"move_speed,omitempty"`
	Level         uint32                 `protobuf:"varint,7,opt,name=level,proto3" json:"level,omitempty"`
	Series        uint32                 `protobuf:"varint,8,opt,name=series,proto3" json:"series,omitempty"`
	Sex           uint32                 `protobuf:"varint,9,opt,name=sex,proto3" json:"sex,omitempty"`
	TemplateId    uint32                 `protobuf:"varint,10,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"` // npc/monster template, 0 for players
	Path          []*Vec2                `protobuf:"bytes,11,rep,name=path,proto3" json:"path,omitempty"`                                // remaining waypoints after pos (server pathfinding)
	Dir           uint32                 `protobuf:"varint,12,opt,name=dir,proto3" json:"dir,omitempty"`                                 // facing direction 0..63 (old g_GetDirIndex: 0 = down, clockwise on screen)
	Life          uint32                 `protobuf:"varint,13,opt,name=life,proto3" json:"life,omitempty"`
	LifeMax       uint32                 `protobuf:"varint,14,opt,name=life_max,json=lifeMax,proto3" json:"life_max,omitempty"`
	Doing         Action                 `protobuf:"varint,15,opt,name=doing,proto3,enum=jx.pb.Action" json:"doing,omitempty"` // what it is doing right now (a corpse reports ACTION_DEATH)
	DoingFrames   uint32                 `protobuf:"varint,16,opt,name=doing_frames,json=doingFrames,proto3" json:"doing_frames,omitempty"`
	Count         uint32                 `protobuf:"varint,17,opt,name=count,proto3" json:"count,omitempty"` // ENTITY_DROP: the stack of the item, or the coins of a money pile (template_id = ObjData row)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityInfo) Reset() {
	*x = EntityInfo{}
	mi := &file_jx_client_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityInfo) ProtoMessage() {}

func (x *EntityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityInfo.ProtoReflect.Descriptor instead.
func (*EntityInfo) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{16}
}

func (x *EntityInfo) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *EntityInfo) GetEntityType() EntityType {
	if x != nil {
		return x.EntityType
	}
	return EntityType_ENTITY_UNKNOWN
}

func (x *EntityInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EntityInfo) GetPos() *Vec2 {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *EntityInfo) GetTarget() *Vec2 {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *EntityInfo) GetMoveSpeed() uint32 {
	if x != nil {
		return x.MoveSpeed
	}
	return 0
}

func (x *EntityInfo) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *EntityInfo) GetSeries() uint32 {
	if x != nil {
		return x.Series
	}
	return 0
}

func (x *EntityInfo) GetSex() uint32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *EntityInfo) GetTemplateId() uint32 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *EntityInfo) GetPath() []*Vec2 {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *EntityInfo) GetDir() uint32 {
	if x != nil {
		return x.Dir
	}
	return 0
}

func (x *EntityInfo) GetLife() uint32 {
	if x != nil {
		return x.Life
	}
	return 0
}

func (x *EntityInfo) GetLifeMax() uint32 {
	if x != nil {
		return x.LifeMax
	}
	return 0
}

func (x *EntityInfo) GetDoing() Action {
	if x != nil {
		return x.Doing
	}
	return Action_ACTION_STAND
}

func (x *EntityInfo) GetDoingFrames() uint32 {
	if x != nil {
		return x.DoingFrames
	}
	return 0
}

func (x *EntityInfo) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type PickUpReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Seq           uint32                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"` // answered with G2C_ITEM_ADD / G2C_MONEY, or G2C_ITEM_RESULT with the reason
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PickUpReq) Reset() {
	*x = PickUpReq{}
	mi := &file_jx_client_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PickUpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PickUpReq) ProtoMessage() {}

func (x *PickUpReq) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PickUpReq.ProtoReflect.Descriptor instead.
func (*PickUpReq) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{17}
}

func (x *PickUpReq) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *PickUpReq) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type EntitySpawn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*EntityInfo          `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntitySpawn) Reset() {
	*x = EntitySpawn{}
	mi := &file_jx_client_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntitySpawn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntitySpawn) ProtoMessage() {}

func (x *EntitySpawn) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntitySpawn.ProtoReflect.Descriptor instead.
func (*EntitySpawn) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{18}
}

func (x *EntitySpawn) GetEntities() []*EntityInfo {
	if x != nil {
		return x.Entities
	}
	return nil
}

type EntityDespawn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityIds     []uint64               `protobuf:"varint,1,rep,packed,name=entity_ids,json=entityIds,proto3" json:"entity_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityDespawn) Reset() {
	*x = EntityDespawn{}
	mi := &file_jx_client_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityDespawn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityDespawn) ProtoMessage() {}

func (x *EntityDespawn) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityDespawn.ProtoReflect.Descriptor instead.
func (*EntityDespawn) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{19}
}

func (x *EntityDespawn) GetEntityIds() []uint64 {
	if x != nil {
		return x.EntityIds
	}
	return nil
}

type EntityMove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Pos           *Vec2                  `protobuf:"bytes,2,opt,name=pos,proto3" json:"pos,omitempty"`       // position at tick
	Target        *Vec2                  `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"` // final destination (last waypoint), == pos when idle
	MoveSpeed     uint32                 `protobuf:"varint,4,opt,name=move_speed,json=moveSpeed,proto3" json:"move_speed,omitempty"`
	Tick          uint64                 `protobuf:"varint,5,opt,name=tick,proto3" json:"tick,omitempty"`
	Seq           uint32                 `protobuf:"varint,6,opt,name=seq,proto3" json:"seq,omitempty"`  // MoveReq.seq when this is the receiver own entity
	Path          []*Vec2                `protobuf:"bytes,7,rep,name=path,proto3" json:"path,omitempty"` // waypoints from pos to target; the client follows the same line
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityMove) Reset() {
	*x = EntityMove{}
	mi := &file_jx_client_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityMove) ProtoMessage() {}

func (x *EntityMove) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityMove.ProtoReflect.Descriptor instead.
func (*EntityMove) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{20}
}

func (x *EntityMove) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *EntityMove) GetPos() *Vec2 {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *EntityMove) GetTarget() *Vec2 {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *EntityMove) GetMoveSpeed() uint32 {
	if x != nil {
		return x.MoveSpeed
	}
	return 0
}

func (x *EntityMove) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *EntityMove) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *EntityMove) GetPath() []*Vec2 {
	if x != nil {
		return x.Path
	}
	return nil
}

// The movements of entities FAR from the receiver, gathered over a few ticks into one frame
// (KSubWorld::flush_far, N3).  Each entry is the entity's latest state, exactly what an EntityMove
// would carry; the client handles them one by one.  What moves near the receiver still comes as a
// single EntityMove the moment it happens.
type EntityMoves struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Moves         []*EntityMove          `protobuf:"bytes,1,rep,name=moves,proto3" json:"moves,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityMoves) Reset() {
	*x = EntityMoves{}
	mi := &file_jx_client_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityMoves) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityMoves) ProtoMessage() {}

func (x *EntityMoves) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityMoves.ProtoReflect.Descriptor instead.
func (*EntityMoves) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{21}
}

func (x *EntityMoves) GetMoves() []*EntityMove {
	if x != nil {
		return x.Moves
	}
	return nil
}

type ChatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatReq) Reset() {
	*x = ChatReq{}
	mi := &file_jx_client_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatReq) ProtoMessage() {}

func (x *ChatReq) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatReq.ProtoReflect.Descriptor instead.
func (*ChatReq) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{22}
}

func (x *ChatReq) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// One item as the client sees it: what the character holds (KItem) plus what its table row says
// (name, picture, size, price) so the bag window needs no table of its own.
type ItemView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Genre         uint32                 `protobuf:"varint,2,opt,name=genre,proto3" json:"genre,omitempty"` // ITEMGENRE: 0 equipment, 1 medicine, 4 quest, 5 town portal, 6 script item
	Detail        uint32                 `protobuf:"varint,3,opt,name=detail,proto3" json:"detail,omitempty"`
	Particular    uint32                 `protobuf:"varint,4,opt,name=particular,proto3" json:"particular,omitempty"`
	Level         uint32                 `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	Series        int32                  `protobuf:"varint,6,opt,name=series,proto3" json:"series,omitempty"`
	Count         uint32                 `protobuf:"varint,7,opt,name=count,proto3" json:"count,omitempty"`
	Durability    int32                  `protobuf:"varint,8,opt,name=durability,proto3" json:"durability,omitempty"` // -1 = never wears
	MaxDurability int32                  `protobuf:"varint,9,opt,name=max_durability,json=maxDurability,proto3" json:"max_durability,omitempty"`
	ExType        uint32                 `protobuf:"varint,10,opt,name=ex_type,json=exType,proto3" json:"ex_type,omitempty"` // 0 normal, 1 gold, 2 platina, 3 purple
	Room          uint32                 `protobuf:"varint,11,opt,name=room,proto3" json:"room,omitempty"`                   // 0 bag, 1 repository, 2 trade, 3 quick slots, 10 worn (x = part)
	X             uint32                 `protobuf:"varint,12,opt,name=x,proto3" json:"x,omitempty"`
	Y             uint32                 `protobuf:"varint,13,opt,name=y,proto3" json:"y,omitempty"`
	Width         uint32                 `protobuf:"varint,14,opt,name=width,proto3" json:"width,omitempty"` // cells
	Height        uint32                 `protobuf:"varint,15,opt,name=height,proto3" json:"height,omitempty"`
	Name          string                 `protobuf:"bytes,16,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,17,opt,name=image,proto3" json:"image,omitempty"` // \spr\item\... of the old client
	Intro         string                 `protobuf:"bytes,18,opt,name=intro,proto3" json:"intro,omitempty"`
	Price         uint32                 `protobuf:"varint,19,opt,name=price,proto3" json:"price,omitempty"`
	Base          []*ItemMagic           `protobuf:"bytes,20,rep,name=base,proto3" json:"base,omitempty"`
	Require       []*ItemMagic           `protobuf:"bytes,21,rep,name=require,proto3" json:"require,omitempty"`
	Magic         []*ItemMagic           `protobuf:"bytes,22,rep,name=magic,proto3" json:"magic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemView) Reset() {
	*x = ItemView{}
	mi := &file_jx_client_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemView) ProtoMessage() {}

func (x *ItemView) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemView.ProtoReflect.Descriptor instead.
func (*ItemView) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{23}
}

func (x *ItemView) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ItemView) GetGenre() uint32 {
	if x != nil {
		return x.Genre
	}
	return 0
}

func (x *ItemView) GetDetail() uint32 {
	if x != nil {
		return x.Detail
	}
	return 0
}

func (x *ItemView) GetParticular() uint32 {
	if x != nil {
		return x.Particular
	}
	return 0
}

func (x *ItemView) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *ItemView) GetSeries() int32 {
	if x != nil {
		return x.Series
	}
	return 0
}

func (x *ItemView) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ItemView) GetDurability() int32 {
	if x != nil {
		return x.Durability
	}
	return 0
}

func (x *ItemView) GetMaxDurability() int32 {
	if x != nil {
		return x.MaxDurability
	}
	return 0
}

func (x *ItemView) GetExType() uint32 {
	if x != nil {
		return x.ExType
	}
	return 0
}

func (x *ItemView) GetRoom() uint32 {
	if x != nil {
		return x.Room
	}
	return 0
}

func (x *ItemView) GetX() uint32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ItemView) GetY() uint32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *ItemView) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ItemView) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ItemView) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ItemView) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ItemView) GetIntro() string {
	if x != nil {
		return x.Intro
	}
	return ""
}

func (x *ItemView) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ItemView) GetBase() []*ItemMagic {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *ItemView) GetRequire() []*ItemMagic {
	if x != nil {
		return x.Require
	}
	return nil
}

func (x *ItemView) GetMagic() []*ItemMagic {
	if x != nil {
		return x.Magic
	}
	return nil
}

type InventorySync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ItemView            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Money         uint32                 `protobuf:"varint,2,opt,name=money,proto3" json:"money,omitempty"`
	BankMoney     uint32                 `protobuf:"varint,3,opt,name=bank_money,json=bankMoney,proto3" json:"bank_money,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventorySync) Reset() {
	*x = InventorySync{}
	mi := &file_jx_client_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventorySync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventorySync) ProtoMessage() {}

func (x *InventorySync) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventorySync.ProtoReflect.Descriptor instead.
func (*InventorySync) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{24}
}

func (x *InventorySync) GetItems() []*ItemView {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *InventorySync) GetMoney() uint32 {
	if x != nil {
		return x.Money
	}
	return 0
}

func (x *InventorySync) GetBankMoney() uint32 {
	if x != nil {
		return x.BankMoney
	}
	return 0
}

type ItemAdd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *ItemView              `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemAdd) Reset() {
	*x = ItemAdd{}
	mi := &file_jx_client_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemAdd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemAdd) ProtoMessage() {}

func (x *ItemAdd) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemAdd.ProtoReflect.Descriptor instead.
func (*ItemAdd) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{25}
}

func (x *ItemAdd) GetItem() *ItemView {
	if x != nil {
		return x.Item
	}
	return nil
}

type ItemRemove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemRemove) Reset() {
	*x = ItemRemove{}
	mi := &file_jx_client_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemRemove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemRemove) ProtoMessage() {}

func (x *ItemRemove) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemRemove.ProtoReflect.Descriptor instead.
func (*ItemRemove) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{26}
}

func (x *ItemRemove) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ItemMove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Room          uint32                 `protobuf:"varint,2,opt,name=room,proto3" json:"room,omitempty"`
	X             uint32                 `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             uint32                 `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	Seq           uint32                 `protobuf:"varint,5,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemMove) Reset() {
	*x = ItemMove{}
	mi := &file_jx_client_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemMove) ProtoMessage() {}

func (x *ItemMove) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemMove.ProtoReflect.Descriptor instead.
func (*ItemMove) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{27}
}

func (x *ItemMove) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ItemMove) GetRoom() uint32 {
	if x != nil {
		return x.Room
	}
	return 0
}

func (x *ItemMove) GetX() uint32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ItemMove) GetY() uint32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *ItemMove) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type ItemEquipReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Part          int32                  `protobuf:"varint,2,opt,name=part,proto3" json:"part,omitempty"` // ITEM_PART; -1 = the part its kind goes to (KItemList::GetEquipPlace)
	Seq           uint32                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemEquipReq) Reset() {
	*x = ItemEquipReq{}
	mi := &file_jx_client_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemEquipReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemEquipReq) ProtoMessage() {}

func (x *ItemEquipReq) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemEquipReq.ProtoReflect.Descriptor instead.
func (*ItemEquipReq) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{28}
}

func (x *ItemEquipReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ItemEquipReq) GetPart() int32 {
	if x != nil {
		return x.Part
	}
	return 0
}

func (x *ItemEquipReq) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type ItemUnequipReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Part          uint32                 `protobuf:"varint,1,opt,name=part,proto3" json:"part,omitempty"`
	Seq           uint32                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemUnequipReq) Reset() {
	*x = ItemUnequipReq{}
	mi := &file_jx_client_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemUnequipReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemUnequipReq) ProtoMessage() {}

func (x *ItemUnequipReq) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemUnequipReq.ProtoReflect.Descriptor instead.
func (*ItemUnequipReq) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{29}
}

func (x *ItemUnequipReq) GetPart() uint32 {
	if x != nil {
		return x.Part
	}
	return 0
}

func (x *ItemUnequipReq) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type ItemUseReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Seq           uint32                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemUseReq) Reset() {
	*x = ItemUseReq{}
	mi := &file_jx_client_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemUseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemUseReq) ProtoMessage() {}

func (x *ItemUseReq) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemUseReq.ProtoReflect.Descriptor instead.
func (*ItemUseReq) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{30}
}

func (x *ItemUseReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ItemUseReq) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type ItemDropReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Seq           uint32                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemDropReq) Reset() {
	*x = ItemDropReq{}
	mi := &file_jx_client_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemDropReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemDropReq) ProtoMessage() {}

func (x *ItemDropReq) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemDropReq.ProtoReflect.Descriptor instead.
func (*ItemDropReq) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{31}
}

func (x *ItemDropReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ItemDropReq) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type ItemResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint32                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Result        Result                 `protobuf:"varint,2,opt,name=result,proto3,enum=jx.pb.Result" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemResult) Reset() {
	*x = ItemResult{}
	mi := &file_jx_client_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemResult) ProtoMessage() {}

func (x *ItemResult) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemResult.ProtoReflect.Descriptor instead.
func (*ItemResult) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{32}
}

func (x *ItemResult) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ItemResult) GetResult() Result {
	if x != nil {
		return x.Result
	}
	return Result_RESULT_OK
}

type MoneySync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Money         uint32                 `protobuf:"varint,1,opt,name=money,proto3" json:"money,omitempty"`
	BankMoney     uint32                 `protobuf:"varint,2,opt,name=bank_money,json=bankMoney,proto3" json:"bank_money,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoneySync) Reset() {
	*x = MoneySync{}
	mi := &file_jx_client_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoneySync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoneySync) ProtoMessage() {}

func (x *MoneySync) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoneySync.ProtoReflect.Descriptor instead.
func (*MoneySync) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{33}
}

func (x *MoneySync) GetMoney() uint32 {
	if x != nil {
		return x.Money
	}
	return 0
}

func (x *MoneySync) GetBankMoney() uint32 {
	if x != nil {
		return x.BankMoney
	}
	return 0
}

// The player was moved to another map (KNpc::ChangeWorld across subworlds on the old server).
// The client drops every entity, loads the bundle and waits for the EntitySpawn of the new
// surroundings (which includes the player itself).
type ChangeMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapId         uint32                 `protobuf:"varint,1,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	Pos           *Vec2                  `protobuf:"bytes,2,opt,name=pos,proto3" json:"pos,omitempty"`
	SceneW        uint32                 `protobuf:"varint,3,opt,name=scene_w,json=sceneW,proto3" json:"scene_w,omitempty"`
	SceneH        uint32                 `protobuf:"varint,4,opt,name=scene_h,json=sceneH,proto3" json:"scene_h,omitempty"`
	EntityId      uint64                 `protobuf:"varint,5,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"` // the player's entity in the new map
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeMap) Reset() {
	*x = ChangeMap{}
	mi := &file_jx_client_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeMap) ProtoMessage() {}

func (x *ChangeMap) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeMap.ProtoReflect.Descriptor instead.
func (*ChangeMap) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{34}
}

func (x *ChangeMap) GetMapId() uint32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *ChangeMap) GetPos() *Vec2 {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *ChangeMap) GetSceneW() uint32 {
	if x != nil {
		return x.SceneW
	}
	return 0
}

func (x *ChangeMap) GetSceneH() uint32 {
	if x != nil {
		return x.SceneH
	}
	return 0
}

func (x *ChangeMap) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

type ChatMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMsg) Reset() {
	*x = ChatMsg{}
	mi := &file_jx_client_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMsg) ProtoMessage() {}

func (x *ChatMsg) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMsg.ProtoReflect.Descriptor instead.
func (*ChatMsg) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{35}
}

func (x *ChatMsg) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *ChatMsg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChatMsg) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientMs      uint64                 `protobuf:"varint,1,opt,name=client_ms,json=clientMs,proto3" json:"client_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_jx_client_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{36}
}

func (x *Ping) GetClientMs() uint64 {
	if x != nil {
		return x.ClientMs
	}
	return 0
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientMs      uint64                 `protobuf:"varint,1,opt,name=client_ms,json=clientMs,proto3" json:"client_ms,omitempty"`
	ServerMs      uint64                 `protobuf:"varint,2,opt,name=server_ms,json=serverMs,proto3" json:"server_ms,omitempty"`
	Tick          uint64                 `protobuf:"varint,3,opt,name=tick,proto3" json:"tick,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_jx_client_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{37}
}

func (x *Pong) GetClientMs() uint64 {
	if x != nil {
		return x.ClientMs
	}
	return 0
}

func (x *Pong) GetServerMs() uint64 {
	if x != nil {
		return x.ServerMs
	}
	return 0
}

func (x *Pong) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

type Kick struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        Result                 `protobuf:"varint,1,opt,name=reason,proto3,enum=jx.pb.Result" json:"reason,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kick) Reset() {
	*x = Kick{}
	mi := &file_jx_client_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kick) ProtoMessage() {}

func (x *Kick) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kick.ProtoReflect.Descriptor instead.
func (*Kick) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{38}
}

func (x *Kick) GetReason() Result {
	if x != nil {
		return x.Reason
	}
	return Result_RESULT_OK
}

func (x *Kick) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_jx_client_proto protoreflect.FileDescriptor

const file_jx_client_proto_rawDesc = "" +
	"\n" +
	"\x0fjx/client.proto\x12\x05jx.pb\x1a\x0fjx/common.proto\x1a\rjx/role.proto\"\x92\x01\n" +
	"\x05Hello\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12%\n" +
	"\x0eclient_version\x18\x02 \x01(\tR\rclientVersion\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x1b\n" +
	"\tdevice_id\x18\x04 \x01(\tR\bdeviceId\"\xd2\x01\n" +
	"\bHelloAck\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12$\n" +
	"\x0eserver_time_ms\x18\x02 \x01(\x04R\fserverTimeMs\x12%\n" +
	"\x0eserver_version\x18\x03 \x01(\tR\rserverVersion\x12\x10\n" +
	"\x03sid\x18\x04 \x01(\x04R\x03sid\x12\x1b\n" +
	"\tauth_mode\x18\x05 \x01(\tR\bauthMode\x12\x1f\n" +
	"\vheartbeat_s\x18\x06 \x01(\rR\n" +
	"heartbeatS\"@\n" +
	"\bLoginReq\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"d\n" +
	"\bLoginRes\x12%\n" +
	"\x06result\x18\x01 \x01(\x0e2\r.jx.pb.ResultR\x06result\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x04R\taccountId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"\xb1\x01\n" +
	"\vCharSummary\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x03 \x01(\rR\x05level\x12\x16\n" +
	"\x06series\x18\x04 \x01(\rR\x06series\x12\x10\n" +
	"\x03sex\x18\x05 \x01(\rR\x03sex\x12\x18\n" +
	"\afaction\x18\x06 \x01(\rR\afaction\x12\x17\n" +
	"\azone_id\x18\a \x01(\rR\x06zoneId\"\r\n" +
	"\vCharListReq\"{\n" +
	"\vCharListRes\x12%\n" +
	"\x06result\x18\x01 \x01(\x0e2\r.jx.pb.ResultR\x06result\x12(\n" +
	"\x05chars\x18\x02 \x03(\v2\x12.jx.pb.CharSummaryR\x05chars\x12\x1b\n" +
	"\tmax_chars\x18\x03 \x01(\rR\bmaxChars\"p\n" +
	"\rCharCreateReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06series\x18\x02 \x01(\rR\x06series\x12\x10\n" +
	"\x03sex\x18\x03 \x01(\rR\x03sex\x12!\n" +
	"\fnative_place\x18\x04 \x01(\rR\vnativePlace\"d\n" +
	"\rCharCreateRes\x12%\n" +
	"\x06result\x18\x01 \x01(\x0e2\r.jx.pb.ResultR\x06result\x12,\n" +
	"\asummary\x18\x02 \x01(\v2\x12.jx.pb.CharSummaryR\asummary\",\n" +
	"\rEnterWorldReq\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\"\x8a\x02\n" +
	"\rEnterWorldRes\x12%\n" +
	"\x06result\x18\x01 \x01(\x0e2\r.jx.pb.ResultR\x06result\x12\x17\n" +
	"\azone_id\x18\x02 \x01(\rR\x06zoneId\x12\x1b\n" +
	"\tzone_name\x18\x03 \x01(\tR\bzoneName\x12\x1b\n" +
	"\tentity_id\x18\x04 \x01(\x04R\bentityId\x12\x1d\n" +
	"\x03pos\x18\x05 \x01(\v2\v.jx.pb.Vec2R\x03pos\x12\x17\n" +
	"\atick_hz\x18\x06 \x01(\rR\x06tickHz\x12\x15\n" +
	"\x06map_id\x18\a \x01(\rR\x05mapId\x12\x17\n" +
	"\ascene_w\x18\b \x01(\rR\x06sceneW\x12\x17\n" +
	"\ascene_h\x18\t \x01(\rR\x06sceneH\"\x0f\n" +
	"\rLeaveWorldReq\"@\n" +
	"\aMoveReq\x12#\n" +
	"\x06target\x18\x01 \x01(\v2\v.jx.pb.Vec2R\x06target\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\rR\x03seq\"5\n" +
	"\tAttackReq\x12\x16\n" +
	"\x06target\x18\x01 \x01(\x04R\x06target\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\rR\x03seq\"\xc7\x01\n" +
	"\fEntityAction\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\x12%\n" +
	"\x06action\x18\x02 \x01(\x0e2\r.jx.pb.ActionR\x06action\x12\x16\n" +
	"\x06target\x18\x03 \x01(\x04R\x06target\x12\x10\n" +
	"\x03dir\x18\x04 \x01(\rR\x03dir\x12\x16\n" +
	"\x06frames\x18\x05 \x01(\rR\x06frames\x12\x1d\n" +
	"\x03pos\x18\x06 \x01(\v2\v.jx.pb.Vec2R\x03pos\x12\x12\n" +
	"\x04tick\x18\a \x01(\x04R\x04tick\"\x86\x01\n" +
	"\n" +
	"EntityLife\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\x12\x12\n" +
	"\x04life\x18\x02 \x01(\rR\x04life\x12\x19\n" +
	"\blife_max\x18\x03 \x01(\rR\alifeMax\x12\x14\n" +
	"\x05delta\x18\x04 \x01(\x05R\x05delta\x12\x16\n" +
	"\x06source\x18\x05 \x01(\x04R\x06source\"\xf5\x03\n" +
	"\n" +
	"EntityInfo\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\x122\n" +
	"\ventity_type\x18\x02 \x01(\x0e2\x11.jx.pb.EntityTypeR\n" +
	"entityType\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\x03pos\x18\x04 \x01(\v2\v.jx.pb.Vec2R\x03pos\x12#\n" +
	"\x06target\x18\x05 \x01(\v2\v.jx.pb.Vec2R\x06target\x12\x1d\n" +
	"\n" +
	"move_speed\x18\x06 \x01(\rR\tmoveSpeed\x12\x14\n" +
	"\x05level\x18\a \x01(\rR\x05level\x12\x16\n" +
	"\x06series\x18\b \x01(\rR\x06series\x12\x10\n" +
	"\x03sex\x18\t \x01(\rR\x03sex\x12\x1f\n" +
	"\vtemplate_id\x18\n" +
	" \x01(\rR\n" +
	"templateId\x12\x1f\n" +
	"\x04path\x18\v \x03(\v2\v.jx.pb.Vec2R\x04path\x12\x10\n" +
	"\x03dir\x18\f \x01(\rR\x03dir\x12\x12\n" +
	"\x04life\x18\r \x01(\rR\x04life\x12\x19\n" +
	"\blife_max\x18\x0e \x01(\rR\alifeMax\x12#\n" +
	"\x05doing\x18\x0f \x01(\x0e2\r.jx.pb.ActionR\x05doing\x12!\n" +
	"\fdoing_frames\x18\x10 \x01(\rR\vdoingFrames\x12\x14\n" +
	"\x05count\x18\x11 \x01(\rR\x05count\":\n" +
	"\tPickUpReq\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\rR\x03seq\"<\n" +
	"\vEntitySpawn\x12-\n" +
	"\bentities\x18\x01 \x03(\v2\x11.jx.pb.EntityInfoR\bentities\".\n" +
	"\rEntityDespawn\x12\x1d\n" +
	"\n" +
	"entity_ids\x18\x01 \x03(\x04R\tentityIds\"\xd3\x01\n" +
	"\n" +
	"EntityMove\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\x12\x1d\n" +
	"\x03pos\x18\x02 \x01(\v2\v.jx.pb.Vec2R\x03pos\x12#\n" +
	"\x06target\x18\x03 \x01(\v2\v.jx.pb.Vec2R\x06target\x12\x1d\n" +
	"\n" +
	"move_speed\x18\x04 \x01(\rR\tmoveSpeed\x12\x12\n" +
	"\x04tick\x18\x05 \x01(\x04R\x04tick\x12\x10\n" +
	"\x03seq\x18\x06 \x01(\rR\x03seq\x12\x1f\n" +
	"\x04path\x18\a \x03(\v2\v.jx.pb.Vec2R\x04path\"6\n" +
	"\vEntityMoves\x12'\n" +
	"\x05moves\x18\x01 \x03(\v2\x11.jx.pb.EntityMoveR\x05moves\"\x1d\n" +
	"\aChatReq\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\xba\x04\n" +
	"\bItemView\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05genre\x18\x02 \x01(\rR\x05genre\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\rR\x06detail\x12\x1e\n" +
	"\n" +
	"particular\x18\x04 \x01(\rR\n" +
	"particular\x12\x14\n" +
	"\x05level\x18\x05 \x01(\rR\x05level\x12\x16\n" +
	"\x06series\x18\x06 \x01(\x05R\x06series\x12\x14\n" +
	"\x05count\x18\a \x01(\rR\x05count\x12\x1e\n" +
	"\n" +
	"durability\x18\b \x01(\x05R\n" +
	"durability\x12%\n" +
	"\x0emax_durability\x18\t \x01(\x05R\rmaxDurability\x12\x17\n" +
	"\aex_type\x18\n" +
	" \x01(\rR\x06exType\x12\x12\n" +
	"\x04room\x18\v \x01(\rR\x04room\x12\f\n" +
	"\x01x\x18\f \x01(\rR\x01x\x12\f\n" +
	"\x01y\x18\r \x01(\rR\x01y\x12\x14\n" +
	"\x05width\x18\x0e \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x0f \x01(\rR\x06height\x12\x12\n" +
	"\x04name\x18\x10 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x11 \x01(\tR\x05image\x12\x14\n" +
	"\x05intro\x18\x12 \x01(\tR\x05intro\x12\x14\n" +
	"\x05price\x18\x13 \x01(\rR\x05price\x12$\n" +
	"\x04base\x18\x14 \x03(\v2\x10.jx.pb.ItemMagicR\x04base\x12*\n" +
	"\arequire\x18\x15 \x03(\v2\x10.jx.pb.ItemMagicR\arequire\x12&\n" +
	"\x05magic\x18\x16 \x03(\v2\x10.jx.pb.ItemMagicR\x05magic\"k\n" +
	"\rInventorySync\x12%\n" +
	"\x05items\x18\x01 \x03(\v2\x0f.jx.pb.ItemViewR\x05items\x12\x14\n" +
	"\x05money\x18\x02 \x01(\rR\x05money\x12\x1d\n" +
	"\n" +
	"bank_money\x18\x03 \x01(\rR\tbankMoney\".\n" +
	"\aItemAdd\x12#\n" +
	"\x04item\x18\x01 \x01(\v2\x0f.jx.pb.ItemViewR\x04item\"\x1c\n" +
	"\n" +
	"ItemRemove\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\\\n" +
	"\bItemMove\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04room\x18\x02 \x01(\rR\x04room\x12\f\n" +
	"\x01x\x18\x03 \x01(\rR\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\rR\x01y\x12\x10\n" +
	"\x03seq\x18\x05 \x01(\rR\x03seq\"D\n" +
	"\fItemEquipReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04part\x18\x02 \x01(\x05R\x04part\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\rR\x03seq\"6\n" +
	"\x0eItemUnequipReq\x12\x12\n" +
	"\x04part\x18\x01 \x01(\rR\x04part\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\rR\x03seq\".\n" +
	"\n" +
	"ItemUseReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\rR\x03seq\"/\n" +
	"\vItemDropReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\rR\x03seq\"E\n" +
	"\n" +
	"ItemResult\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\rR\x03seq\x12%\n" +
	"\x06result\x18\x02 \x01(\x0e2\r.jx.pb.ResultR\x06result\"@\n" +
	"\tMoneySync\x12\x14\n" +
	"\x05money\x18\x01 \x01(\rR\x05money\x12\x1d\n" +
	"\n" +
	"bank_money\x18\x02 \x01(\rR\tbankMoney\"\x90\x01\n" +
	"\tChangeMap\x12\x15\n" +
	"\x06map_id\x18\x01 \x01(\rR\x05mapId\x12\x1d\n" +
	"\x03pos\x18\x02 \x01(\v2\v.jx.pb.Vec2R\x03pos\x12\x17\n" +
	"\ascene_w\x18\x03 \x01(\rR\x06sceneW\x12\x17\n" +
	"\ascene_h\x18\x04 \x01(\rR\x06sceneH\x12\x1b\n" +
	"\tentity_id\x18\x05 \x01(\x04R\bentityId\"N\n" +
	"\aChatMsg\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"#\n" +
	"\x04Ping\x12\x1b\n" +
	"\tclient_ms\x18\x01 \x01(\x04R\bclientMs\"T\n" +
	"\x04Pong\x12\x1b\n" +
	"\tclient_ms\x18\x01 \x01(\x04R\bclientMs\x12\x1b\n" +
	"\tserver_ms\x18\x02 \x01(\x04R\bserverMs\x12\x12\n" +
	"\x04tick\x18\x03 \x01(\x04R\x04tick\"A\n" +
	"\x04Kick\x12%\n" +
	"\x06reason\x18\x01 \x01(\x0e2\r.jx.pb.ResultR\x06reason\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text*c\n" +
	"\x06Action\x12\x10\n" +
	"\fACTION_STAND\x10\x00\x12\x11\n" +
	"\rACTION_ATTACK\x10\x01\x12\x0f\n" +
	"\vACTION_HURT\x10\x02\x12\x10\n" +
	"\fACTION_DEATH\x10\x03\x12\x11\n" +
	"\rACTION_REVIVE\x10\x04B6Z4github.com/JXGAME04/DUANGODOT/next/services/pkg/jxpbb\x06proto3"

var (
	file_jx_client_proto_rawDescOnce sync.Once
	file_jx_client_proto_rawDescData []byte
)

func file_jx_client_proto_rawDescGZIP() []byte {
	file_jx_client_proto_rawDescOnce.Do(func() {
		file_jx_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jx_client_proto_rawDesc), len(file_jx_client_proto_rawDesc)))
	})
	return file_jx_client_proto_rawDescData
}

var file_jx_client_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_jx_client_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_jx_client_proto_goTypes = []any{
	(Action)(0),            // 0: jx.pb.Action
	(*Hello)(nil),          // 1: jx.pb.Hello
	(*HelloAck)(nil),       // 2: jx.pb.HelloAck
	(*LoginReq)(nil),       // 3: jx.pb.LoginReq
	(*LoginRes)(nil),       // 4: jx.pb.LoginRes
	(*CharSummary)(nil),    // 5: jx.pb.CharSummary
	(*CharListReq)(nil),    // 6: jx.pb.CharListReq
	(*CharListRes)(nil),    // 7: jx.pb.CharListRes
	(*CharCreateReq)(nil),  // 8: jx.pb.CharCreateReq
	(*CharCreateRes)(nil),  // 9: jx.pb.CharCreateRes
	(*EnterWorldReq)(nil),  // 10: jx.pb.EnterWorldReq
	(*EnterWorldRes)(nil),  // 11: jx.pb.EnterWorldRes
	(*LeaveWorldReq)(nil),  // 12: jx.pb.LeaveWorldReq
	(*MoveReq)(nil),        // 13: jx.pb.MoveReq
	(*AttackReq)(nil),      // 14: jx.pb.AttackReq
	(*EntityAction)(nil),   // 15: jx.pb.EntityAction
	(*EntityLife)(nil),     // 16: jx.pb.EntityLife
	(*EntityInfo)(nil),     // 17: jx.pb.EntityInfo
	(*PickUpReq)(nil),      // 18: jx.pb.PickUpReq
	(*EntitySpawn)(nil),    // 19: jx.pb.EntitySpawn
	(*EntityDespawn)(nil),  // 20: jx.pb.EntityDespawn
	(*EntityMove)(nil),     // 21: jx.pb.EntityMove
	(*EntityMoves)(nil),    // 22: jx.pb.EntityMoves
	(*ChatReq)(nil),        // 23: jx.pb.ChatReq
	(*ItemView)(nil),       // 24: jx.pb.ItemView
	(*InventorySync)(nil),  // 25: jx.pb.InventorySync
	(*ItemAdd)(nil),        // 26: jx.pb.ItemAdd
	(*ItemRemove)(nil),     // 27: jx.pb.ItemRemove
	(*ItemMove)(nil),       // 28: jx.pb.ItemMove
	(*ItemEquipReq)(nil),   // 29: jx.pb.ItemEquipReq
	(*ItemUnequipReq)(nil), // 30: jx.pb.ItemUnequipReq
	(*ItemUseReq)(nil),     // 31: jx.pb.ItemUseReq
	(*ItemDropReq)(nil),    // 32: jx.pb.ItemDropReq
	(*ItemResult)(nil),     // 33: jx.pb.ItemResult
	(*MoneySync)(nil),      // 34: jx.pb.MoneySync
	(*ChangeMap)(nil),      // 35: jx.pb.ChangeMap
	(*ChatMsg)(nil),        // 36: jx.pb.ChatMsg
	(*Ping)(nil),           // 37: jx.pb.Ping
	(*Pong)(nil),           // 38: jx.pb.Pong
	(*Kick)(nil),           // 39: jx.pb.Kick
	(Result)(0),            // 40: jx.pb.Result
	(*Vec2)(nil),           // 41: jx.pb.Vec2
	(EntityType)(0),        // 42: jx.pb.EntityType
	(*ItemMagic)(nil),      // 43: jx.pb.ItemMagic
}
var file_jx_client_proto_depIdxs = []int32{
	40, // 0: jx.pb.LoginRes.result:type_name -> jx.pb.Result
	40, // 1: jx.pb.CharListRes.result:type_name -> jx.pb.Result
	5,  // 2: jx.pb.CharListRes.chars:type_name -> jx.pb.CharSummary
	40, // 3: jx.pb.CharCreateRes.result:type_name -> jx.pb.Result
	5,  // 4: jx.pb.CharCreateRes.summary:type_name -> jx.pb.CharSummary
	40, // 5: jx.pb.EnterWorldRes.result:type_name -> jx.pb.Result
	41, // 6: jx.pb.EnterWorldRes.pos:type_name -> jx.pb.Vec2
	41, // 7: jx.pb.MoveReq.target:type_name -> jx.pb.Vec2
	0,  // 8: jx.pb.EntityAction.action:type_name -> jx.pb.Action
	41, // 9: jx.pb.EntityAction.pos:type_name -> jx.pb.Vec2
	42, // 10: jx.pb.EntityInfo.entity_type:type_name -> jx.pb.EntityType
	41, // 11: jx.pb.EntityInfo.pos:type_name -> jx.pb.Vec2
	41, // 12: jx.pb.EntityInfo.target:type_name -> jx.pb.Vec2
	41, // 13: jx.pb.EntityInfo.path:type_name -> jx.pb.Vec2
	0,  // 14: jx.pb.EntityInfo.doing:type_name -> jx.pb.Action
	17, // 15: jx.pb.EntitySpawn.entities:type_name -> jx.pb.EntityInfo
	41, // 16: jx.pb.EntityMove.pos:type_name -> jx.pb.Vec2
	41, // 17: jx.pb.EntityMove.target:type_name -> jx.pb.Vec2
	41, // 18: jx.pb.EntityMove.path:type_name -> jx.pb.Vec2
	21, // 19: jx.pb.EntityMoves.moves:type_name -> jx.pb.EntityMove
	43, // 20: jx.pb.ItemView.base:type_name -> jx.pb.ItemMagic
	43, // 21: jx.pb.ItemView.require:type_name -> jx.pb.ItemMagic
	43, // 22: jx.pb.ItemView.magic:type_name -> jx.pb.ItemMagic
	24, // 23: jx.pb.InventorySync.items:type_name -> jx.pb.ItemView
	24, // 24: jx.pb.ItemAdd.item:type_name -> jx.pb.ItemView
	40, // 25: jx.pb.ItemResult.result:type_name -> jx.pb.Result
	41, // 26: jx.pb.ChangeMap.pos:type_name -> jx.pb.Vec2
	40, // 27: jx.pb.Kick.reason:type_name -> jx.pb.Result
	28, // [28:28] is the sub-list for method output_type
	28, // [28:28] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_jx_client_proto_init() }
func file_jx_client_proto_init() {
	if File_jx_client_proto != nil {
		return
	}
	file_jx_common_proto_init()
	file_jx_role_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jx_client_proto_rawDesc), len(file_jx_client_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_jx_client_proto_goTypes,
		DependencyIndexes: file_jx_client_proto_depIdxs,
		EnumInfos:         file_jx_client_proto_enumTypes,
		MessageInfos:      file_jx_client_proto_msgTypes,
	}.Build()
	File_jx_client_proto = out.File
	file_jx_client_proto_goTypes = nil
	file_jx_client_proto_depIdxs = nil
}
