// Client <-> gateway messages.  C2G = client to gateway, G2C = gateway to client.
// Some C2G messages are forwarded unchanged to the zone (see MsgId comments in msg.proto).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.4
// source: jx/client.proto

package jxpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Hello struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"` // PROTOCOL_VERSION in msg.proto
	ClientVersion   string                 `protobuf:"bytes,2,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	Platform        string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"` // "windows", "linux", "android", ...
	DeviceId        string                 `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_jx_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{0}
}

func (x *Hello) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *Hello) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *Hello) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *Hello) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type HelloAck struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	ServerTimeMs    uint64                 `protobuf:"varint,2,opt,name=server_time_ms,json=serverTimeMs,proto3" json:"server_time_ms,omitempty"`
	ServerVersion   string                 `protobuf:"bytes,3,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	Sid             uint64                 `protobuf:"varint,4,opt,name=sid,proto3" json:"sid,omitempty"` // session id, useful when reading logs
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HelloAck) Reset() {
	*x = HelloAck{}
	mi := &file_jx_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAck) ProtoMessage() {}

func (x *HelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAck.ProtoReflect.Descriptor instead.
func (*HelloAck) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{1}
}

func (x *HelloAck) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *HelloAck) GetServerTimeMs() uint64 {
	if x != nil {
		return x.ServerTimeMs
	}
	return 0
}

func (x *HelloAck) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *HelloAck) GetSid() uint64 {
	if x != nil {
		return x.Sid
	}
	return 0
}

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // dev auth only; real auth uses tokens (phase 3)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_jx_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{2}
}

func (x *LoginReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        Result                 `protobuf:"varint,1,opt,name=result,proto3,enum=jx.pb.Result" json:"result,omitempty"`
	AccountId     uint64                 `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"` // human readable reason (field names must avoid protobuf keywords: godobuf)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRes) Reset() {
	*x = LoginRes{}
	mi := &file_jx_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRes) ProtoMessage() {}

func (x *LoginRes) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRes.ProtoReflect.Descriptor instead.
func (*LoginRes) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{3}
}

func (x *LoginRes) GetResult() Result {
	if x != nil {
		return x.Result
	}
	return Result_RESULT_OK
}

func (x *LoginRes) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *LoginRes) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type CharSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Level         uint32                 `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Series        uint32                 `protobuf:"varint,4,opt,name=series,proto3" json:"series,omitempty"`
	Sex           uint32                 `protobuf:"varint,5,opt,name=sex,proto3" json:"sex,omitempty"`
	Faction       uint32                 `protobuf:"varint,6,opt,name=faction,proto3" json:"faction,omitempty"`
	ZoneId        uint32                 `protobuf:"varint,7,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharSummary) Reset() {
	*x = CharSummary{}
	mi := &file_jx_client_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharSummary) ProtoMessage() {}

func (x *CharSummary) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharSummary.ProtoReflect.Descriptor instead.
func (*CharSummary) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{4}
}

func (x *CharSummary) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *CharSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CharSummary) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CharSummary) GetSeries() uint32 {
	if x != nil {
		return x.Series
	}
	return 0
}

func (x *CharSummary) GetSex() uint32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *CharSummary) GetFaction() uint32 {
	if x != nil {
		return x.Faction
	}
	return 0
}

func (x *CharSummary) GetZoneId() uint32 {
	if x != nil {
		return x.ZoneId
	}
	return 0
}

type CharListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharListReq) Reset() {
	*x = CharListReq{}
	mi := &file_jx_client_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharListReq) ProtoMessage() {}

func (x *CharListReq) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharListReq.ProtoReflect.Descriptor instead.
func (*CharListReq) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{5}
}

type CharListRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        Result                 `protobuf:"varint,1,opt,name=result,proto3,enum=jx.pb.Result" json:"result,omitempty"`
	Chars         []*CharSummary         `protobuf:"bytes,2,rep,name=chars,proto3" json:"chars,omitempty"`
	MaxChars      uint32                 `protobuf:"varint,3,opt,name=max_chars,json=maxChars,proto3" json:"max_chars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharListRes) Reset() {
	*x = CharListRes{}
	mi := &file_jx_client_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharListRes) ProtoMessage() {}

func (x *CharListRes) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharListRes.ProtoReflect.Descriptor instead.
func (*CharListRes) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{6}
}

func (x *CharListRes) GetResult() Result {
	if x != nil {
		return x.Result
	}
	return Result_RESULT_OK
}

func (x *CharListRes) GetChars() []*CharSummary {
	if x != nil {
		return x.Chars
	}
	return nil
}

func (x *CharListRes) GetMaxChars() uint32 {
	if x != nil {
		return x.MaxChars
	}
	return 0
}

type CharCreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Series        uint32                 `protobuf:"varint,2,opt,name=series,proto3" json:"series,omitempty"`
	Sex           uint32                 `protobuf:"varint,3,opt,name=sex,proto3" json:"sex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharCreateReq) Reset() {
	*x = CharCreateReq{}
	mi := &file_jx_client_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharCreateReq) ProtoMessage() {}

func (x *CharCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharCreateReq.ProtoReflect.Descriptor instead.
func (*CharCreateReq) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{7}
}

func (x *CharCreateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CharCreateReq) GetSeries() uint32 {
	if x != nil {
		return x.Series
	}
	return 0
}

func (x *CharCreateReq) GetSex() uint32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

type CharCreateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        Result                 `protobuf:"varint,1,opt,name=result,proto3,enum=jx.pb.Result" json:"result,omitempty"`
	Summary       *CharSummary           `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharCreateRes) Reset() {
	*x = CharCreateRes{}
	mi := &file_jx_client_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharCreateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharCreateRes) ProtoMessage() {}

func (x *CharCreateRes) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharCreateRes.ProtoReflect.Descriptor instead.
func (*CharCreateRes) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{8}
}

func (x *CharCreateRes) GetResult() Result {
	if x != nil {
		return x.Result
	}
	return Result_RESULT_OK
}

func (x *CharCreateRes) GetSummary() *CharSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

type EnterWorldReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterWorldReq) Reset() {
	*x = EnterWorldReq{}
	mi := &file_jx_client_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterWorldReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterWorldReq) ProtoMessage() {}

func (x *EnterWorldReq) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterWorldReq.ProtoReflect.Descriptor instead.
func (*EnterWorldReq) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{9}
}

func (x *EnterWorldReq) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type EnterWorldRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        Result                 `protobuf:"varint,1,opt,name=result,proto3,enum=jx.pb.Result" json:"result,omitempty"`
	ZoneId        uint32                 `protobuf:"varint,2,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	ZoneName      string                 `protobuf:"bytes,3,opt,name=zone_name,json=zoneName,proto3" json:"zone_name,omitempty"`
	EntityId      uint64                 `protobuf:"varint,4,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"` // the entity that belongs to this client in the zone
	Pos           *Vec2                  `protobuf:"bytes,5,opt,name=pos,proto3" json:"pos,omitempty"`
	TickHz        uint32                 `protobuf:"varint,6,opt,name=tick_hz,json=tickHz,proto3" json:"tick_hz,omitempty"`
	MapId         uint32                 `protobuf:"varint,7,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"` // which map bundle to draw (0 = plain grid)
	SceneW        uint32                 `protobuf:"varint,8,opt,name=scene_w,json=sceneW,proto3" json:"scene_w,omitempty"`
	SceneH        uint32                 `protobuf:"varint,9,opt,name=scene_h,json=sceneH,proto3" json:"scene_h,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterWorldRes) Reset() {
	*x = EnterWorldRes{}
	mi := &file_jx_client_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterWorldRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterWorldRes) ProtoMessage() {}

func (x *EnterWorldRes) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterWorldRes.ProtoReflect.Descriptor instead.
func (*EnterWorldRes) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{10}
}

func (x *EnterWorldRes) GetResult() Result {
	if x != nil {
		return x.Result
	}
	return Result_RESULT_OK
}

func (x *EnterWorldRes) GetZoneId() uint32 {
	if x != nil {
		return x.ZoneId
	}
	return 0
}

func (x *EnterWorldRes) GetZoneName() string {
	if x != nil {
		return x.ZoneName
	}
	return ""
}

func (x *EnterWorldRes) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *EnterWorldRes) GetPos() *Vec2 {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *EnterWorldRes) GetTickHz() uint32 {
	if x != nil {
		return x.TickHz
	}
	return 0
}

func (x *EnterWorldRes) GetMapId() uint32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *EnterWorldRes) GetSceneW() uint32 {
	if x != nil {
		return x.SceneW
	}
	return 0
}

func (x *EnterWorldRes) GetSceneH() uint32 {
	if x != nil {
		return x.SceneH
	}
	return 0
}

type LeaveWorldReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveWorldReq) Reset() {
	*x = LeaveWorldReq{}
	mi := &file_jx_client_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveWorldReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveWorldReq) ProtoMessage() {}

func (x *LeaveWorldReq) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveWorldReq.ProtoReflect.Descriptor instead.
func (*LeaveWorldReq) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{11}
}

// Server authoritative movement: the client asks to move towards a target, the zone
// simulates and broadcasts EntityMove to everyone who can see the entity.
type MoveReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        *Vec2                  `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Seq           uint32                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"` // client sequence number, echoed in EntityMove for the own entity
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveReq) Reset() {
	*x = MoveReq{}
	mi := &file_jx_client_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveReq) ProtoMessage() {}

func (x *MoveReq) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveReq.ProtoReflect.Descriptor instead.
func (*MoveReq) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{12}
}

func (x *MoveReq) GetTarget() *Vec2 {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *MoveReq) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type EntityInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	EntityType    EntityType             `protobuf:"varint,2,opt,name=entity_type,json=entityType,proto3,enum=jx.pb.EntityType" json:"entity_type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Pos           *Vec2                  `protobuf:"bytes,4,opt,name=pos,proto3" json:"pos,omitempty"`
	Target        *Vec2                  `protobuf:"bytes,5,opt,name=target,proto3" json:"target,omitempty"` // where it is currently moving to (== pos when idle)
	MoveSpeed     uint32                 `protobuf:"varint,6,opt,name=move_speed,json=moveSpeed,proto3" json:"move_speed,omitempty"`
	Level         uint32                 `protobuf:"varint,7,opt,name=level,proto3" json:"level,omitempty"`
	Series        uint32                 `protobuf:"varint,8,opt,name=series,proto3" json:"series,omitempty"`
	Sex           uint32                 `protobuf:"varint,9,opt,name=sex,proto3" json:"sex,omitempty"`
	TemplateId    uint32                 `protobuf:"varint,10,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"` // npc/monster template, 0 for players
	Path          []*Vec2                `protobuf:"bytes,11,rep,name=path,proto3" json:"path,omitempty"`                                // remaining waypoints after pos (server pathfinding)
	Dir           uint32                 `protobuf:"varint,12,opt,name=dir,proto3" json:"dir,omitempty"`                                 // facing direction 0..7 (old game convention)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityInfo) Reset() {
	*x = EntityInfo{}
	mi := &file_jx_client_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityInfo) ProtoMessage() {}

func (x *EntityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityInfo.ProtoReflect.Descriptor instead.
func (*EntityInfo) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{13}
}

func (x *EntityInfo) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *EntityInfo) GetEntityType() EntityType {
	if x != nil {
		return x.EntityType
	}
	return EntityType_ENTITY_UNKNOWN
}

func (x *EntityInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EntityInfo) GetPos() *Vec2 {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *EntityInfo) GetTarget() *Vec2 {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *EntityInfo) GetMoveSpeed() uint32 {
	if x != nil {
		return x.MoveSpeed
	}
	return 0
}

func (x *EntityInfo) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *EntityInfo) GetSeries() uint32 {
	if x != nil {
		return x.Series
	}
	return 0
}

func (x *EntityInfo) GetSex() uint32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *EntityInfo) GetTemplateId() uint32 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *EntityInfo) GetPath() []*Vec2 {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *EntityInfo) GetDir() uint32 {
	if x != nil {
		return x.Dir
	}
	return 0
}

type EntitySpawn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*EntityInfo          `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntitySpawn) Reset() {
	*x = EntitySpawn{}
	mi := &file_jx_client_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntitySpawn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntitySpawn) ProtoMessage() {}

func (x *EntitySpawn) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntitySpawn.ProtoReflect.Descriptor instead.
func (*EntitySpawn) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{14}
}

func (x *EntitySpawn) GetEntities() []*EntityInfo {
	if x != nil {
		return x.Entities
	}
	return nil
}

type EntityDespawn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityIds     []uint64               `protobuf:"varint,1,rep,packed,name=entity_ids,json=entityIds,proto3" json:"entity_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityDespawn) Reset() {
	*x = EntityDespawn{}
	mi := &file_jx_client_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityDespawn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityDespawn) ProtoMessage() {}

func (x *EntityDespawn) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityDespawn.ProtoReflect.Descriptor instead.
func (*EntityDespawn) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{15}
}

func (x *EntityDespawn) GetEntityIds() []uint64 {
	if x != nil {
		return x.EntityIds
	}
	return nil
}

type EntityMove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Pos           *Vec2                  `protobuf:"bytes,2,opt,name=pos,proto3" json:"pos,omitempty"`       // position at tick
	Target        *Vec2                  `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"` // final destination (last waypoint), == pos when idle
	MoveSpeed     uint32                 `protobuf:"varint,4,opt,name=move_speed,json=moveSpeed,proto3" json:"move_speed,omitempty"`
	Tick          uint64                 `protobuf:"varint,5,opt,name=tick,proto3" json:"tick,omitempty"`
	Seq           uint32                 `protobuf:"varint,6,opt,name=seq,proto3" json:"seq,omitempty"`  // MoveReq.seq when this is the receiver own entity
	Path          []*Vec2                `protobuf:"bytes,7,rep,name=path,proto3" json:"path,omitempty"` // waypoints from pos to target; the client follows the same line
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityMove) Reset() {
	*x = EntityMove{}
	mi := &file_jx_client_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityMove) ProtoMessage() {}

func (x *EntityMove) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityMove.ProtoReflect.Descriptor instead.
func (*EntityMove) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{16}
}

func (x *EntityMove) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *EntityMove) GetPos() *Vec2 {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *EntityMove) GetTarget() *Vec2 {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *EntityMove) GetMoveSpeed() uint32 {
	if x != nil {
		return x.MoveSpeed
	}
	return 0
}

func (x *EntityMove) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *EntityMove) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *EntityMove) GetPath() []*Vec2 {
	if x != nil {
		return x.Path
	}
	return nil
}

type ChatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatReq) Reset() {
	*x = ChatReq{}
	mi := &file_jx_client_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatReq) ProtoMessage() {}

func (x *ChatReq) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatReq.ProtoReflect.Descriptor instead.
func (*ChatReq) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{17}
}

func (x *ChatReq) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ChatMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMsg) Reset() {
	*x = ChatMsg{}
	mi := &file_jx_client_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMsg) ProtoMessage() {}

func (x *ChatMsg) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMsg.ProtoReflect.Descriptor instead.
func (*ChatMsg) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{18}
}

func (x *ChatMsg) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *ChatMsg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChatMsg) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientMs      uint64                 `protobuf:"varint,1,opt,name=client_ms,json=clientMs,proto3" json:"client_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_jx_client_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{19}
}

func (x *Ping) GetClientMs() uint64 {
	if x != nil {
		return x.ClientMs
	}
	return 0
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientMs      uint64                 `protobuf:"varint,1,opt,name=client_ms,json=clientMs,proto3" json:"client_ms,omitempty"`
	ServerMs      uint64                 `protobuf:"varint,2,opt,name=server_ms,json=serverMs,proto3" json:"server_ms,omitempty"`
	Tick          uint64                 `protobuf:"varint,3,opt,name=tick,proto3" json:"tick,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_jx_client_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{20}
}

func (x *Pong) GetClientMs() uint64 {
	if x != nil {
		return x.ClientMs
	}
	return 0
}

func (x *Pong) GetServerMs() uint64 {
	if x != nil {
		return x.ServerMs
	}
	return 0
}

func (x *Pong) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

type Kick struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        Result                 `protobuf:"varint,1,opt,name=reason,proto3,enum=jx.pb.Result" json:"reason,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kick) Reset() {
	*x = Kick{}
	mi := &file_jx_client_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kick) ProtoMessage() {}

func (x *Kick) ProtoReflect() protoreflect.Message {
	mi := &file_jx_client_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kick.ProtoReflect.Descriptor instead.
func (*Kick) Descriptor() ([]byte, []int) {
	return file_jx_client_proto_rawDescGZIP(), []int{21}
}

func (x *Kick) GetReason() Result {
	if x != nil {
		return x.Reason
	}
	return Result_RESULT_OK
}

func (x *Kick) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_jx_client_proto protoreflect.FileDescriptor

const file_jx_client_proto_rawDesc = "" +
	"\n" +
	"\x0fjx/client.proto\x12\x05jx.pb\x1a\x0fjx/common.proto\"\x92\x01\n" +
	"\x05Hello\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12%\n" +
	"\x0eclient_version\x18\x02 \x01(\tR\rclientVersion\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x1b\n" +
	"\tdevice_id\x18\x04 \x01(\tR\bdeviceId\"\x94\x01\n" +
	"\bHelloAck\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12$\n" +
	"\x0eserver_time_ms\x18\x02 \x01(\x04R\fserverTimeMs\x12%\n" +
	"\x0eserver_version\x18\x03 \x01(\tR\rserverVersion\x12\x10\n" +
	"\x03sid\x18\x04 \x01(\x04R\x03sid\"@\n" +
	"\bLoginReq\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"d\n" +
	"\bLoginRes\x12%\n" +
	"\x06result\x18\x01 \x01(\x0e2\r.jx.pb.ResultR\x06result\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x04R\taccountId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"\xb1\x01\n" +
	"\vCharSummary\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x03 \x01(\rR\x05level\x12\x16\n" +
	"\x06series\x18\x04 \x01(\rR\x06series\x12\x10\n" +
	"\x03sex\x18\x05 \x01(\rR\x03sex\x12\x18\n" +
	"\afaction\x18\x06 \x01(\rR\afaction\x12\x17\n" +
	"\azone_id\x18\a \x01(\rR\x06zoneId\"\r\n" +
	"\vCharListReq\"{\n" +
	"\vCharListRes\x12%\n" +
	"\x06result\x18\x01 \x01(\x0e2\r.jx.pb.ResultR\x06result\x12(\n" +
	"\x05chars\x18\x02 \x03(\v2\x12.jx.pb.CharSummaryR\x05chars\x12\x1b\n" +
	"\tmax_chars\x18\x03 \x01(\rR\bmaxChars\"M\n" +
	"\rCharCreateReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06series\x18\x02 \x01(\rR\x06series\x12\x10\n" +
	"\x03sex\x18\x03 \x01(\rR\x03sex\"d\n" +
	"\rCharCreateRes\x12%\n" +
	"\x06result\x18\x01 \x01(\x0e2\r.jx.pb.ResultR\x06result\x12,\n" +
	"\asummary\x18\x02 \x01(\v2\x12.jx.pb.CharSummaryR\asummary\",\n" +
	"\rEnterWorldReq\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\"\x8a\x02\n" +
	"\rEnterWorldRes\x12%\n" +
	"\x06result\x18\x01 \x01(\x0e2\r.jx.pb.ResultR\x06result\x12\x17\n" +
	"\azone_id\x18\x02 \x01(\rR\x06zoneId\x12\x1b\n" +
	"\tzone_name\x18\x03 \x01(\tR\bzoneName\x12\x1b\n" +
	"\tentity_id\x18\x04 \x01(\x04R\bentityId\x12\x1d\n" +
	"\x03pos\x18\x05 \x01(\v2\v.jx.pb.Vec2R\x03pos\x12\x17\n" +
	"\atick_hz\x18\x06 \x01(\rR\x06tickHz\x12\x15\n" +
	"\x06map_id\x18\a \x01(\rR\x05mapId\x12\x17\n" +
	"\ascene_w\x18\b \x01(\rR\x06sceneW\x12\x17\n" +
	"\ascene_h\x18\t \x01(\rR\x06sceneH\"\x0f\n" +
	"\rLeaveWorldReq\"@\n" +
	"\aMoveReq\x12#\n" +
	"\x06target\x18\x01 \x01(\v2\v.jx.pb.Vec2R\x06target\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\rR\x03seq\"\xe8\x02\n" +
	"\n" +
	"EntityInfo\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\x122\n" +
	"\ventity_type\x18\x02 \x01(\x0e2\x11.jx.pb.EntityTypeR\n" +
	"entityType\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\x03pos\x18\x04 \x01(\v2\v.jx.pb.Vec2R\x03pos\x12#\n" +
	"\x06target\x18\x05 \x01(\v2\v.jx.pb.Vec2R\x06target\x12\x1d\n" +
	"\n" +
	"move_speed\x18\x06 \x01(\rR\tmoveSpeed\x12\x14\n" +
	"\x05level\x18\a \x01(\rR\x05level\x12\x16\n" +
	"\x06series\x18\b \x01(\rR\x06series\x12\x10\n" +
	"\x03sex\x18\t \x01(\rR\x03sex\x12\x1f\n" +
	"\vtemplate_id\x18\n" +
	" \x01(\rR\n" +
	"templateId\x12\x1f\n" +
	"\x04path\x18\v \x03(\v2\v.jx.pb.Vec2R\x04path\x12\x10\n" +
	"\x03dir\x18\f \x01(\rR\x03dir\"<\n" +
	"\vEntitySpawn\x12-\n" +
	"\bentities\x18\x01 \x03(\v2\x11.jx.pb.EntityInfoR\bentities\".\n" +
	"\rEntityDespawn\x12\x1d\n" +
	"\n" +
	"entity_ids\x18\x01 \x03(\x04R\tentityIds\"\xd3\x01\n" +
	"\n" +
	"EntityMove\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\x12\x1d\n" +
	"\x03pos\x18\x02 \x01(\v2\v.jx.pb.Vec2R\x03pos\x12#\n" +
	"\x06target\x18\x03 \x01(\v2\v.jx.pb.Vec2R\x06target\x12\x1d\n" +
	"\n" +
	"move_speed\x18\x04 \x01(\rR\tmoveSpeed\x12\x12\n" +
	"\x04tick\x18\x05 \x01(\x04R\x04tick\x12\x10\n" +
	"\x03seq\x18\x06 \x01(\rR\x03seq\x12\x1f\n" +
	"\x04path\x18\a \x03(\v2\v.jx.pb.Vec2R\x04path\"\x1d\n" +
	"\aChatReq\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"N\n" +
	"\aChatMsg\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"#\n" +
	"\x04Ping\x12\x1b\n" +
	"\tclient_ms\x18\x01 \x01(\x04R\bclientMs\"T\n" +
	"\x04Pong\x12\x1b\n" +
	"\tclient_ms\x18\x01 \x01(\x04R\bclientMs\x12\x1b\n" +
	"\tserver_ms\x18\x02 \x01(\x04R\bserverMs\x12\x12\n" +
	"\x04tick\x18\x03 \x01(\x04R\x04tick\"A\n" +
	"\x04Kick\x12%\n" +
	"\x06reason\x18\x01 \x01(\x0e2\r.jx.pb.ResultR\x06reason\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04textB6Z4github.com/JXGAME04/DUANGODOT/next/services/pkg/jxpbb\x06proto3"

var (
	file_jx_client_proto_rawDescOnce sync.Once
	file_jx_client_proto_rawDescData []byte
)

func file_jx_client_proto_rawDescGZIP() []byte {
	file_jx_client_proto_rawDescOnce.Do(func() {
		file_jx_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jx_client_proto_rawDesc), len(file_jx_client_proto_rawDesc)))
	})
	return file_jx_client_proto_rawDescData
}

var file_jx_client_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_jx_client_proto_goTypes = []any{
	(*Hello)(nil),         // 0: jx.pb.Hello
	(*HelloAck)(nil),      // 1: jx.pb.HelloAck
	(*LoginReq)(nil),      // 2: jx.pb.LoginReq
	(*LoginRes)(nil),      // 3: jx.pb.LoginRes
	(*CharSummary)(nil),   // 4: jx.pb.CharSummary
	(*CharListReq)(nil),   // 5: jx.pb.CharListReq
	(*CharListRes)(nil),   // 6: jx.pb.CharListRes
	(*CharCreateReq)(nil), // 7: jx.pb.CharCreateReq
	(*CharCreateRes)(nil), // 8: jx.pb.CharCreateRes
	(*EnterWorldReq)(nil), // 9: jx.pb.EnterWorldReq
	(*EnterWorldRes)(nil), // 10: jx.pb.EnterWorldRes
	(*LeaveWorldReq)(nil), // 11: jx.pb.LeaveWorldReq
	(*MoveReq)(nil),       // 12: jx.pb.MoveReq
	(*EntityInfo)(nil),    // 13: jx.pb.EntityInfo
	(*EntitySpawn)(nil),   // 14: jx.pb.EntitySpawn
	(*EntityDespawn)(nil), // 15: jx.pb.EntityDespawn
	(*EntityMove)(nil),    // 16: jx.pb.EntityMove
	(*ChatReq)(nil),       // 17: jx.pb.ChatReq
	(*ChatMsg)(nil),       // 18: jx.pb.ChatMsg
	(*Ping)(nil),          // 19: jx.pb.Ping
	(*Pong)(nil),          // 20: jx.pb.Pong
	(*Kick)(nil),          // 21: jx.pb.Kick
	(Result)(0),           // 22: jx.pb.Result
	(*Vec2)(nil),          // 23: jx.pb.Vec2
	(EntityType)(0),       // 24: jx.pb.EntityType
}
var file_jx_client_proto_depIdxs = []int32{
	22, // 0: jx.pb.LoginRes.result:type_name -> jx.pb.Result
	22, // 1: jx.pb.CharListRes.result:type_name -> jx.pb.Result
	4,  // 2: jx.pb.CharListRes.chars:type_name -> jx.pb.CharSummary
	22, // 3: jx.pb.CharCreateRes.result:type_name -> jx.pb.Result
	4,  // 4: jx.pb.CharCreateRes.summary:type_name -> jx.pb.CharSummary
	22, // 5: jx.pb.EnterWorldRes.result:type_name -> jx.pb.Result
	23, // 6: jx.pb.EnterWorldRes.pos:type_name -> jx.pb.Vec2
	23, // 7: jx.pb.MoveReq.target:type_name -> jx.pb.Vec2
	24, // 8: jx.pb.EntityInfo.entity_type:type_name -> jx.pb.EntityType
	23, // 9: jx.pb.EntityInfo.pos:type_name -> jx.pb.Vec2
	23, // 10: jx.pb.EntityInfo.target:type_name -> jx.pb.Vec2
	23, // 11: jx.pb.EntityInfo.path:type_name -> jx.pb.Vec2
	13, // 12: jx.pb.EntitySpawn.entities:type_name -> jx.pb.EntityInfo
	23, // 13: jx.pb.EntityMove.pos:type_name -> jx.pb.Vec2
	23, // 14: jx.pb.EntityMove.target:type_name -> jx.pb.Vec2
	23, // 15: jx.pb.EntityMove.path:type_name -> jx.pb.Vec2
	22, // 16: jx.pb.Kick.reason:type_name -> jx.pb.Result
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_jx_client_proto_init() }
func file_jx_client_proto_init() {
	if File_jx_client_proto != nil {
		return
	}
	file_jx_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jx_client_proto_rawDesc), len(file_jx_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_jx_client_proto_goTypes,
		DependencyIndexes: file_jx_client_proto_depIdxs,
		MessageInfos:      file_jx_client_proto_msgTypes,
	}.Build()
	File_jx_client_proto = out.File
	file_jx_client_proto_goTypes = nil
	file_jx_client_proto_depIdxs = nil
}
