// Shared scalar types.  Package jx.pb is used by every file so the three generators
// (C++ jx::pb, Go jxpb, GDScript) see one namespace.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.4
// source: jx/common.proto

package jxpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Result int32

const (
	Result_RESULT_OK               Result = 0
	Result_RESULT_INTERNAL_ERROR   Result = 1
	Result_RESULT_BAD_REQUEST      Result = 2
	Result_RESULT_UNAUTHORIZED     Result = 3
	Result_RESULT_NOT_FOUND        Result = 4
	Result_RESULT_ALREADY_EXISTS   Result = 5
	Result_RESULT_FULL             Result = 6
	Result_RESULT_INVALID_NAME     Result = 7
	Result_RESULT_WRONG_STATE      Result = 8
	Result_RESULT_ZONE_UNAVAILABLE Result = 9
	Result_RESULT_VERSION_MISMATCH Result = 10
	// login results of the old Sword3PaySys / Bishop (LoginDef.h LOGIN_R_*, S3PAccount::Login)
	Result_RESULT_ACCOUNT_IN_USE Result = 11 // LOGIN_R_ACCOUNT_EXIST: the account is logged in elsewhere
	Result_RESULT_ACCOUNT_FROZEN Result = 12 // LOGIN_R_FREEZE: frozen by a GM
	Result_RESULT_NO_GAME_TIME   Result = 13 // LOGIN_R_TIMEOUT / E_ACCOUNT_NODEPOSIT: no game time left
	Result_RESULT_SERVER_BUSY    Result = 14 // LOGIN_R_FAILED: too many failed logins, try again later
	// session protection (new in JX NEXT)
	Result_RESULT_RATE_LIMITED    Result = 15 // the client sent more than the gateway allows
	Result_RESULT_TIMEOUT         Result = 16 // no heartbeat within the allowed time
	Result_RESULT_REPLACED        Result = 17 // LOGIN_R_BEDISCONNECTED: the account logged in from elsewhere
	Result_RESULT_SERVER_SHUTDOWN Result = 18 // LL_R_SERVER_SHUTDOWN: the gateway is going down
)

// Enum value maps for Result.
var (
	Result_name = map[int32]string{
		0:  "RESULT_OK",
		1:  "RESULT_INTERNAL_ERROR",
		2:  "RESULT_BAD_REQUEST",
		3:  "RESULT_UNAUTHORIZED",
		4:  "RESULT_NOT_FOUND",
		5:  "RESULT_ALREADY_EXISTS",
		6:  "RESULT_FULL",
		7:  "RESULT_INVALID_NAME",
		8:  "RESULT_WRONG_STATE",
		9:  "RESULT_ZONE_UNAVAILABLE",
		10: "RESULT_VERSION_MISMATCH",
		11: "RESULT_ACCOUNT_IN_USE",
		12: "RESULT_ACCOUNT_FROZEN",
		13: "RESULT_NO_GAME_TIME",
		14: "RESULT_SERVER_BUSY",
		15: "RESULT_RATE_LIMITED",
		16: "RESULT_TIMEOUT",
		17: "RESULT_REPLACED",
		18: "RESULT_SERVER_SHUTDOWN",
	}
	Result_value = map[string]int32{
		"RESULT_OK":               0,
		"RESULT_INTERNAL_ERROR":   1,
		"RESULT_BAD_REQUEST":      2,
		"RESULT_UNAUTHORIZED":     3,
		"RESULT_NOT_FOUND":        4,
		"RESULT_ALREADY_EXISTS":   5,
		"RESULT_FULL":             6,
		"RESULT_INVALID_NAME":     7,
		"RESULT_WRONG_STATE":      8,
		"RESULT_ZONE_UNAVAILABLE": 9,
		"RESULT_VERSION_MISMATCH": 10,
		"RESULT_ACCOUNT_IN_USE":   11,
		"RESULT_ACCOUNT_FROZEN":   12,
		"RESULT_NO_GAME_TIME":     13,
		"RESULT_SERVER_BUSY":      14,
		"RESULT_RATE_LIMITED":     15,
		"RESULT_TIMEOUT":          16,
		"RESULT_REPLACED":         17,
		"RESULT_SERVER_SHUTDOWN":  18,
	}
)

func (x Result) Enum() *Result {
	p := new(Result)
	*p = x
	return p
}

func (x Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Result) Descriptor() protoreflect.EnumDescriptor {
	return file_jx_common_proto_enumTypes[0].Descriptor()
}

func (Result) Type() protoreflect.EnumType {
	return &file_jx_common_proto_enumTypes[0]
}

func (x Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Result.Descriptor instead.
func (Result) EnumDescriptor() ([]byte, []int) {
	return file_jx_common_proto_rawDescGZIP(), []int{0}
}

type EntityType int32

const (
	EntityType_ENTITY_UNKNOWN EntityType = 0
	EntityType_ENTITY_PLAYER  EntityType = 1
	EntityType_ENTITY_NPC     EntityType = 2
	EntityType_ENTITY_MONSTER EntityType = 3
	EntityType_ENTITY_DROP    EntityType = 4
)

// Enum value maps for EntityType.
var (
	EntityType_name = map[int32]string{
		0: "ENTITY_UNKNOWN",
		1: "ENTITY_PLAYER",
		2: "ENTITY_NPC",
		3: "ENTITY_MONSTER",
		4: "ENTITY_DROP",
	}
	EntityType_value = map[string]int32{
		"ENTITY_UNKNOWN": 0,
		"ENTITY_PLAYER":  1,
		"ENTITY_NPC":     2,
		"ENTITY_MONSTER": 3,
		"ENTITY_DROP":    4,
	}
)

func (x EntityType) Enum() *EntityType {
	p := new(EntityType)
	*p = x
	return p
}

func (x EntityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityType) Descriptor() protoreflect.EnumDescriptor {
	return file_jx_common_proto_enumTypes[1].Descriptor()
}

func (EntityType) Type() protoreflect.EnumType {
	return &file_jx_common_proto_enumTypes[1]
}

func (x EntityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityType.Descriptor instead.
func (EntityType) EnumDescriptor() ([]byte, []int) {
	return file_jx_common_proto_rawDescGZIP(), []int{1}
}

// World position in integer units (old game: 1 cell = 32 units, one map ~ 10k x 10k units).
type Vec2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vec2) Reset() {
	*x = Vec2{}
	mi := &file_jx_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vec2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vec2) ProtoMessage() {}

func (x *Vec2) ProtoReflect() protoreflect.Message {
	mi := &file_jx_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vec2.ProtoReflect.Descriptor instead.
func (*Vec2) Descriptor() ([]byte, []int) {
	return file_jx_common_proto_rawDescGZIP(), []int{0}
}

func (x *Vec2) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vec2) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

var File_jx_common_proto protoreflect.FileDescriptor

const file_jx_common_proto_rawDesc = "" +
	"\n" +
	"\x0fjx/common.proto\x12\x05jx.pb\"\"\n" +
	"\x04Vec2\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y*\xd5\x03\n" +
	"\x06Result\x12\r\n" +
	"\tRESULT_OK\x10\x00\x12\x19\n" +
	"\x15RESULT_INTERNAL_ERROR\x10\x01\x12\x16\n" +
	"\x12RESULT_BAD_REQUEST\x10\x02\x12\x17\n" +
	"\x13RESULT_UNAUTHORIZED\x10\x03\x12\x14\n" +
	"\x10RESULT_NOT_FOUND\x10\x04\x12\x19\n" +
	"\x15RESULT_ALREADY_EXISTS\x10\x05\x12\x0f\n" +
	"\vRESULT_FULL\x10\x06\x12\x17\n" +
	"\x13RESULT_INVALID_NAME\x10\a\x12\x16\n" +
	"\x12RESULT_WRONG_STATE\x10\b\x12\x1b\n" +
	"\x17RESULT_ZONE_UNAVAILABLE\x10\t\x12\x1b\n" +
	"\x17RESULT_VERSION_MISMATCH\x10\n" +
	"\x12\x19\n" +
	"\x15RESULT_ACCOUNT_IN_USE\x10\v\x12\x19\n" +
	"\x15RESULT_ACCOUNT_FROZEN\x10\f\x12\x17\n" +
	"\x13RESULT_NO_GAME_TIME\x10\r\x12\x16\n" +
	"\x12RESULT_SERVER_BUSY\x10\x0e\x12\x17\n" +
	"\x13RESULT_RATE_LIMITED\x10\x0f\x12\x12\n" +
	"\x0eRESULT_TIMEOUT\x10\x10\x12\x13\n" +
	"\x0fRESULT_REPLACED\x10\x11\x12\x1a\n" +
	"\x16RESULT_SERVER_SHUTDOWN\x10\x12*h\n" +
	"\n" +
	"EntityType\x12\x12\n" +
	"\x0eENTITY_UNKNOWN\x10\x00\x12\x11\n" +
	"\rENTITY_PLAYER\x10\x01\x12\x0e\n" +
	"\n" +
	"ENTITY_NPC\x10\x02\x12\x12\n" +
	"\x0eENTITY_MONSTER\x10\x03\x12\x0f\n" +
	"\vENTITY_DROP\x10\x04B6Z4github.com/JXGAME04/DUANGODOT/next/services/pkg/jxpbb\x06proto3"

var (
	file_jx_common_proto_rawDescOnce sync.Once
	file_jx_common_proto_rawDescData []byte
)

func file_jx_common_proto_rawDescGZIP() []byte {
	file_jx_common_proto_rawDescOnce.Do(func() {
		file_jx_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jx_common_proto_rawDesc), len(file_jx_common_proto_rawDesc)))
	})
	return file_jx_common_proto_rawDescData
}

var file_jx_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_jx_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_jx_common_proto_goTypes = []any{
	(Result)(0),     // 0: jx.pb.Result
	(EntityType)(0), // 1: jx.pb.EntityType
	(*Vec2)(nil),    // 2: jx.pb.Vec2
}
var file_jx_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_jx_common_proto_init() }
func file_jx_common_proto_init() {
	if File_jx_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jx_common_proto_rawDesc), len(file_jx_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_jx_common_proto_goTypes,
		DependencyIndexes: file_jx_common_proto_depIdxs,
		EnumInfos:         file_jx_common_proto_enumTypes,
		MessageInfos:      file_jx_common_proto_msgTypes,
	}.Build()
	File_jx_common_proto = out.File
	file_jx_common_proto_goTypes = nil
	file_jx_common_proto_depIdxs = nil
}
