// Gateway <-> zone messages (never sent to clients).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.4
// source: jx/internal.proto

package jxpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ZoneHello struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	GatewayId       string                 `protobuf:"bytes,2,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ZoneHello) Reset() {
	*x = ZoneHello{}
	mi := &file_jx_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoneHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneHello) ProtoMessage() {}

func (x *ZoneHello) ProtoReflect() protoreflect.Message {
	mi := &file_jx_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneHello.ProtoReflect.Descriptor instead.
func (*ZoneHello) Descriptor() ([]byte, []int) {
	return file_jx_internal_proto_rawDescGZIP(), []int{0}
}

func (x *ZoneHello) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *ZoneHello) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

type ZoneHelloAck struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	ZoneId          uint32                 `protobuf:"varint,2,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	ZoneName        string                 `protobuf:"bytes,3,opt,name=zone_name,json=zoneName,proto3" json:"zone_name,omitempty"`
	TickHz          uint32                 `protobuf:"varint,4,opt,name=tick_hz,json=tickHz,proto3" json:"tick_hz,omitempty"`
	Capacity        uint32                 `protobuf:"varint,5,opt,name=capacity,proto3" json:"capacity,omitempty"`
	MapId           uint32                 `protobuf:"varint,6,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`    // asset bundle id (client/assets/maps/<map_id>), 0 = no map
	SceneW          uint32                 `protobuf:"varint,7,opt,name=scene_w,json=sceneW,proto3" json:"scene_w,omitempty"` // map size in scene units
	SceneH          uint32                 `protobuf:"varint,8,opt,name=scene_h,json=sceneH,proto3" json:"scene_h,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ZoneHelloAck) Reset() {
	*x = ZoneHelloAck{}
	mi := &file_jx_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoneHelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneHelloAck) ProtoMessage() {}

func (x *ZoneHelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_jx_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneHelloAck.ProtoReflect.Descriptor instead.
func (*ZoneHelloAck) Descriptor() ([]byte, []int) {
	return file_jx_internal_proto_rawDescGZIP(), []int{1}
}

func (x *ZoneHelloAck) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *ZoneHelloAck) GetZoneId() uint32 {
	if x != nil {
		return x.ZoneId
	}
	return 0
}

func (x *ZoneHelloAck) GetZoneName() string {
	if x != nil {
		return x.ZoneName
	}
	return ""
}

func (x *ZoneHelloAck) GetTickHz() uint32 {
	if x != nil {
		return x.TickHz
	}
	return 0
}

func (x *ZoneHelloAck) GetCapacity() uint32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *ZoneHelloAck) GetMapId() uint32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *ZoneHelloAck) GetSceneW() uint32 {
	if x != nil {
		return x.SceneW
	}
	return 0
}

func (x *ZoneHelloAck) GetSceneH() uint32 {
	if x != nil {
		return x.SceneH
	}
	return 0
}

// Gateway asks the zone to spawn a player for a client session.
type SessionOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sid           uint64                 `protobuf:"varint,1,opt,name=sid,proto3" json:"sid,omitempty"`
	AccountId     uint64                 `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Role          *RoleData              `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionOpen) Reset() {
	*x = SessionOpen{}
	mi := &file_jx_internal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionOpen) ProtoMessage() {}

func (x *SessionOpen) ProtoReflect() protoreflect.Message {
	mi := &file_jx_internal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionOpen.ProtoReflect.Descriptor instead.
func (*SessionOpen) Descriptor() ([]byte, []int) {
	return file_jx_internal_proto_rawDescGZIP(), []int{2}
}

func (x *SessionOpen) GetSid() uint64 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *SessionOpen) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *SessionOpen) GetRole() *RoleData {
	if x != nil {
		return x.Role
	}
	return nil
}

type SessionOpenAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sid           uint64                 `protobuf:"varint,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Result        Result                 `protobuf:"varint,2,opt,name=result,proto3,enum=jx.pb.Result" json:"result,omitempty"`
	EntityId      uint64                 `protobuf:"varint,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Pos           *Vec2                  `protobuf:"bytes,4,opt,name=pos,proto3" json:"pos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionOpenAck) Reset() {
	*x = SessionOpenAck{}
	mi := &file_jx_internal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionOpenAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionOpenAck) ProtoMessage() {}

func (x *SessionOpenAck) ProtoReflect() protoreflect.Message {
	mi := &file_jx_internal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionOpenAck.ProtoReflect.Descriptor instead.
func (*SessionOpenAck) Descriptor() ([]byte, []int) {
	return file_jx_internal_proto_rawDescGZIP(), []int{3}
}

func (x *SessionOpenAck) GetSid() uint64 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *SessionOpenAck) GetResult() Result {
	if x != nil {
		return x.Result
	}
	return Result_RESULT_OK
}

func (x *SessionOpenAck) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *SessionOpenAck) GetPos() *Vec2 {
	if x != nil {
		return x.Pos
	}
	return nil
}

type SessionClose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sid           uint64                 `protobuf:"varint,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Reason        uint32                 `protobuf:"varint,2,opt,name=reason,proto3" json:"reason,omitempty"` // 0 = client left, 1 = timeout, 2 = kicked, 3 = gateway shutdown
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionClose) Reset() {
	*x = SessionClose{}
	mi := &file_jx_internal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionClose) ProtoMessage() {}

func (x *SessionClose) ProtoReflect() protoreflect.Message {
	mi := &file_jx_internal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionClose.ProtoReflect.Descriptor instead.
func (*SessionClose) Descriptor() ([]byte, []int) {
	return file_jx_internal_proto_rawDescGZIP(), []int{4}
}

func (x *SessionClose) GetSid() uint64 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *SessionClose) GetReason() uint32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

// A client message forwarded to the zone verbatim.
type ClientPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sid           uint64                 `protobuf:"varint,1,opt,name=sid,proto3" json:"sid,omitempty"`
	MsgId         uint32                 `protobuf:"varint,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientPacket) Reset() {
	*x = ClientPacket{}
	mi := &file_jx_internal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientPacket) ProtoMessage() {}

func (x *ClientPacket) ProtoReflect() protoreflect.Message {
	mi := &file_jx_internal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientPacket.ProtoReflect.Descriptor instead.
func (*ClientPacket) Descriptor() ([]byte, []int) {
	return file_jx_internal_proto_rawDescGZIP(), []int{5}
}

func (x *ClientPacket) GetSid() uint64 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *ClientPacket) GetMsgId() uint32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *ClientPacket) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// A message from the zone to one or many client sessions (fan-out done by the gateway).
type ZonePacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sids          []uint64               `protobuf:"varint,1,rep,packed,name=sids,proto3" json:"sids,omitempty"`
	MsgId         uint32                 `protobuf:"varint,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZonePacket) Reset() {
	*x = ZonePacket{}
	mi := &file_jx_internal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZonePacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZonePacket) ProtoMessage() {}

func (x *ZonePacket) ProtoReflect() protoreflect.Message {
	mi := &file_jx_internal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZonePacket.ProtoReflect.Descriptor instead.
func (*ZonePacket) Descriptor() ([]byte, []int) {
	return file_jx_internal_proto_rawDescGZIP(), []int{6}
}

func (x *ZonePacket) GetSids() []uint64 {
	if x != nil {
		return x.Sids
	}
	return nil
}

func (x *ZonePacket) GetMsgId() uint32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *ZonePacket) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Zone -> gateway: persist the player (periodic and on SessionClose).
type PlayerSave struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sid           uint64                 `protobuf:"varint,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Role          *RoleData              `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Final         bool                   `protobuf:"varint,3,opt,name=final,proto3" json:"final,omitempty"` // true when the player has left the zone
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerSave) Reset() {
	*x = PlayerSave{}
	mi := &file_jx_internal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerSave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerSave) ProtoMessage() {}

func (x *PlayerSave) ProtoReflect() protoreflect.Message {
	mi := &file_jx_internal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerSave.ProtoReflect.Descriptor instead.
func (*PlayerSave) Descriptor() ([]byte, []int) {
	return file_jx_internal_proto_rawDescGZIP(), []int{7}
}

func (x *PlayerSave) GetSid() uint64 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *PlayerSave) GetRole() *RoleData {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *PlayerSave) GetFinal() bool {
	if x != nil {
		return x.Final
	}
	return false
}

type ZoneStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneId        uint32                 `protobuf:"varint,1,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	Tick          uint64                 `protobuf:"varint,2,opt,name=tick,proto3" json:"tick,omitempty"`
	Players       uint32                 `protobuf:"varint,3,opt,name=players,proto3" json:"players,omitempty"`
	Entities      uint32                 `protobuf:"varint,4,opt,name=entities,proto3" json:"entities,omitempty"`
	TickMsAvg     uint32                 `protobuf:"varint,5,opt,name=tick_ms_avg,json=tickMsAvg,proto3" json:"tick_ms_avg,omitempty"`
	TickMsMax     uint32                 `protobuf:"varint,6,opt,name=tick_ms_max,json=tickMsMax,proto3" json:"tick_ms_max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZoneStats) Reset() {
	*x = ZoneStats{}
	mi := &file_jx_internal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoneStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneStats) ProtoMessage() {}

func (x *ZoneStats) ProtoReflect() protoreflect.Message {
	mi := &file_jx_internal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneStats.ProtoReflect.Descriptor instead.
func (*ZoneStats) Descriptor() ([]byte, []int) {
	return file_jx_internal_proto_rawDescGZIP(), []int{8}
}

func (x *ZoneStats) GetZoneId() uint32 {
	if x != nil {
		return x.ZoneId
	}
	return 0
}

func (x *ZoneStats) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *ZoneStats) GetPlayers() uint32 {
	if x != nil {
		return x.Players
	}
	return 0
}

func (x *ZoneStats) GetEntities() uint32 {
	if x != nil {
		return x.Entities
	}
	return 0
}

func (x *ZoneStats) GetTickMsAvg() uint32 {
	if x != nil {
		return x.TickMsAvg
	}
	return 0
}

func (x *ZoneStats) GetTickMsMax() uint32 {
	if x != nil {
		return x.TickMsMax
	}
	return 0
}

var File_jx_internal_proto protoreflect.FileDescriptor

const file_jx_internal_proto_rawDesc = "" +
	"\n" +
	"\x11jx/internal.proto\x12\x05jx.pb\x1a\x0fjx/common.proto\x1a\rjx/role.proto\"U\n" +
	"\tZoneHello\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x02 \x01(\tR\tgatewayId\"\xed\x01\n" +
	"\fZoneHelloAck\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x17\n" +
	"\azone_id\x18\x02 \x01(\rR\x06zoneId\x12\x1b\n" +
	"\tzone_name\x18\x03 \x01(\tR\bzoneName\x12\x17\n" +
	"\atick_hz\x18\x04 \x01(\rR\x06tickHz\x12\x1a\n" +
	"\bcapacity\x18\x05 \x01(\rR\bcapacity\x12\x15\n" +
	"\x06map_id\x18\x06 \x01(\rR\x05mapId\x12\x17\n" +
	"\ascene_w\x18\a \x01(\rR\x06sceneW\x12\x17\n" +
	"\ascene_h\x18\b \x01(\rR\x06sceneH\"c\n" +
	"\vSessionOpen\x12\x10\n" +
	"\x03sid\x18\x01 \x01(\x04R\x03sid\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x04R\taccountId\x12#\n" +
	"\x04role\x18\x03 \x01(\v2\x0f.jx.pb.RoleDataR\x04role\"\x85\x01\n" +
	"\x0eSessionOpenAck\x12\x10\n" +
	"\x03sid\x18\x01 \x01(\x04R\x03sid\x12%\n" +
	"\x06result\x18\x02 \x01(\x0e2\r.jx.pb.ResultR\x06result\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\x04R\bentityId\x12\x1d\n" +
	"\x03pos\x18\x04 \x01(\v2\v.jx.pb.Vec2R\x03pos\"8\n" +
	"\fSessionClose\x12\x10\n" +
	"\x03sid\x18\x01 \x01(\x04R\x03sid\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\rR\x06reason\"Q\n" +
	"\fClientPacket\x12\x10\n" +
	"\x03sid\x18\x01 \x01(\x04R\x03sid\x12\x15\n" +
	"\x06msg_id\x18\x02 \x01(\rR\x05msgId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"Q\n" +
	"\n" +
	"ZonePacket\x12\x12\n" +
	"\x04sids\x18\x01 \x03(\x04R\x04sids\x12\x15\n" +
	"\x06msg_id\x18\x02 \x01(\rR\x05msgId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"Y\n" +
	"\n" +
	"PlayerSave\x12\x10\n" +
	"\x03sid\x18\x01 \x01(\x04R\x03sid\x12#\n" +
	"\x04role\x18\x02 \x01(\v2\x0f.jx.pb.RoleDataR\x04role\x12\x14\n" +
	"\x05final\x18\x03 \x01(\bR\x05final\"\xae\x01\n" +
	"\tZoneStats\x12\x17\n" +
	"\azone_id\x18\x01 \x01(\rR\x06zoneId\x12\x12\n" +
	"\x04tick\x18\x02 \x01(\x04R\x04tick\x12\x18\n" +
	"\aplayers\x18\x03 \x01(\rR\aplayers\x12\x1a\n" +
	"\bentities\x18\x04 \x01(\rR\bentities\x12\x1e\n" +
	"\vtick_ms_avg\x18\x05 \x01(\rR\ttickMsAvg\x12\x1e\n" +
	"\vtick_ms_max\x18\x06 \x01(\rR\ttickMsMaxB6Z4github.com/JXGAME04/DUANGODOT/next/services/pkg/jxpbb\x06proto3"

var (
	file_jx_internal_proto_rawDescOnce sync.Once
	file_jx_internal_proto_rawDescData []byte
)

func file_jx_internal_proto_rawDescGZIP() []byte {
	file_jx_internal_proto_rawDescOnce.Do(func() {
		file_jx_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jx_internal_proto_rawDesc), len(file_jx_internal_proto_rawDesc)))
	})
	return file_jx_internal_proto_rawDescData
}

var file_jx_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_jx_internal_proto_goTypes = []any{
	(*ZoneHello)(nil),      // 0: jx.pb.ZoneHello
	(*ZoneHelloAck)(nil),   // 1: jx.pb.ZoneHelloAck
	(*SessionOpen)(nil),    // 2: jx.pb.SessionOpen
	(*SessionOpenAck)(nil), // 3: jx.pb.SessionOpenAck
	(*SessionClose)(nil),   // 4: jx.pb.SessionClose
	(*ClientPacket)(nil),   // 5: jx.pb.ClientPacket
	(*ZonePacket)(nil),     // 6: jx.pb.ZonePacket
	(*PlayerSave)(nil),     // 7: jx.pb.PlayerSave
	(*ZoneStats)(nil),      // 8: jx.pb.ZoneStats
	(*RoleData)(nil),       // 9: jx.pb.RoleData
	(Result)(0),            // 10: jx.pb.Result
	(*Vec2)(nil),           // 11: jx.pb.Vec2
}
var file_jx_internal_proto_depIdxs = []int32{
	9,  // 0: jx.pb.SessionOpen.role:type_name -> jx.pb.RoleData
	10, // 1: jx.pb.SessionOpenAck.result:type_name -> jx.pb.Result
	11, // 2: jx.pb.SessionOpenAck.pos:type_name -> jx.pb.Vec2
	9,  // 3: jx.pb.PlayerSave.role:type_name -> jx.pb.RoleData
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_jx_internal_proto_init() }
func file_jx_internal_proto_init() {
	if File_jx_internal_proto != nil {
		return
	}
	file_jx_common_proto_init()
	file_jx_role_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jx_internal_proto_rawDesc), len(file_jx_internal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_jx_internal_proto_goTypes,
		DependencyIndexes: file_jx_internal_proto_depIdxs,
		MessageInfos:      file_jx_internal_proto_msgTypes,
	}.Build()
	File_jx_internal_proto = out.File
	file_jx_internal_proto_goTypes = nil
	file_jx_internal_proto_depIdxs = nil
}
