// Message id registry.  Every frame on the wire carries one of these ids (see docs/PROTOCOL.md).
//   1000-1999  C2G   client -> gateway
//   2000-2999  G2C   gateway -> client
//   9000-9999  internal gateway <-> zone
// Never reuse a number.  Ids marked (zone) are forwarded by the gateway to the zone as ClientPacket.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.4
// source: jx/msg.proto

package jxpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Protocol int32

const (
	Protocol_PROTOCOL_UNSPECIFIED Protocol = 0
	Protocol_PROTOCOL_VERSION     Protocol = 1
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0: "PROTOCOL_UNSPECIFIED",
		1: "PROTOCOL_VERSION",
	}
	Protocol_value = map[string]int32{
		"PROTOCOL_UNSPECIFIED": 0,
		"PROTOCOL_VERSION":     1,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_jx_msg_proto_enumTypes[0].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_jx_msg_proto_enumTypes[0]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_jx_msg_proto_rawDescGZIP(), []int{0}
}

type MsgId int32

const (
	MsgId_MSG_NONE MsgId = 0
	// client -> gateway
	MsgId_C2G_HELLO       MsgId = 1001
	MsgId_C2G_LOGIN       MsgId = 1002
	MsgId_C2G_CHAR_LIST   MsgId = 1003
	MsgId_C2G_CHAR_CREATE MsgId = 1004
	MsgId_C2G_ENTER_WORLD MsgId = 1005
	MsgId_C2G_LEAVE_WORLD MsgId = 1006
	MsgId_C2G_PING        MsgId = 1007
	MsgId_C2G_MOVE        MsgId = 1101 // (zone)
	MsgId_C2G_CHAT        MsgId = 1102 // (zone)
	MsgId_C2G_ATTACK      MsgId = 1103 // (zone)
	// gateway -> client
	MsgId_G2C_HELLO_ACK       MsgId = 2001
	MsgId_G2C_LOGIN_RES       MsgId = 2002
	MsgId_G2C_CHAR_LIST_RES   MsgId = 2003
	MsgId_G2C_CHAR_CREATE_RES MsgId = 2004
	MsgId_G2C_ENTER_WORLD_RES MsgId = 2005
	MsgId_G2C_PONG            MsgId = 2007
	MsgId_G2C_KICK            MsgId = 2008
	MsgId_G2C_ENTITY_SPAWN    MsgId = 2101
	MsgId_G2C_ENTITY_DESPAWN  MsgId = 2102
	MsgId_G2C_ENTITY_MOVE     MsgId = 2103
	MsgId_G2C_CHAT_MSG        MsgId = 2104
	MsgId_G2C_ENTITY_ACTION   MsgId = 2105 // attack / hurt / death / revive (old NPC_HURT_SYNC, NPC_DEATH_SYNC, skill sync)
	MsgId_G2C_ENTITY_LIFE     MsgId = 2106
	MsgId_G2C_CHANGE_MAP      MsgId = 2107 // the zone moved the player to another map (NewWorld of a trap script)
	MsgId_G2C_ENTITY_MOVES    MsgId = 2108 // several EntityMove in one frame: what moved far from the receiver, every few ticks (N3)
	// gateway <-> zone
	MsgId_GZ_ZONE_HELLO       MsgId = 9001
	MsgId_ZG_ZONE_HELLO_ACK   MsgId = 9002
	MsgId_GZ_SESSION_OPEN     MsgId = 9003
	MsgId_ZG_SESSION_OPEN_ACK MsgId = 9004
	MsgId_GZ_SESSION_CLOSE    MsgId = 9005
	MsgId_GZ_CLIENT_PACKET    MsgId = 9006
	MsgId_ZG_ZONE_PACKET      MsgId = 9007
	MsgId_ZG_PLAYER_SAVE      MsgId = 9008
	MsgId_ZG_ZONE_STATS       MsgId = 9009
)

// Enum value maps for MsgId.
var (
	MsgId_name = map[int32]string{
		0:    "MSG_NONE",
		1001: "C2G_HELLO",
		1002: "C2G_LOGIN",
		1003: "C2G_CHAR_LIST",
		1004: "C2G_CHAR_CREATE",
		1005: "C2G_ENTER_WORLD",
		1006: "C2G_LEAVE_WORLD",
		1007: "C2G_PING",
		1101: "C2G_MOVE",
		1102: "C2G_CHAT",
		1103: "C2G_ATTACK",
		2001: "G2C_HELLO_ACK",
		2002: "G2C_LOGIN_RES",
		2003: "G2C_CHAR_LIST_RES",
		2004: "G2C_CHAR_CREATE_RES",
		2005: "G2C_ENTER_WORLD_RES",
		2007: "G2C_PONG",
		2008: "G2C_KICK",
		2101: "G2C_ENTITY_SPAWN",
		2102: "G2C_ENTITY_DESPAWN",
		2103: "G2C_ENTITY_MOVE",
		2104: "G2C_CHAT_MSG",
		2105: "G2C_ENTITY_ACTION",
		2106: "G2C_ENTITY_LIFE",
		2107: "G2C_CHANGE_MAP",
		2108: "G2C_ENTITY_MOVES",
		9001: "GZ_ZONE_HELLO",
		9002: "ZG_ZONE_HELLO_ACK",
		9003: "GZ_SESSION_OPEN",
		9004: "ZG_SESSION_OPEN_ACK",
		9005: "GZ_SESSION_CLOSE",
		9006: "GZ_CLIENT_PACKET",
		9007: "ZG_ZONE_PACKET",
		9008: "ZG_PLAYER_SAVE",
		9009: "ZG_ZONE_STATS",
	}
	MsgId_value = map[string]int32{
		"MSG_NONE":            0,
		"C2G_HELLO":           1001,
		"C2G_LOGIN":           1002,
		"C2G_CHAR_LIST":       1003,
		"C2G_CHAR_CREATE":     1004,
		"C2G_ENTER_WORLD":     1005,
		"C2G_LEAVE_WORLD":     1006,
		"C2G_PING":            1007,
		"C2G_MOVE":            1101,
		"C2G_CHAT":            1102,
		"C2G_ATTACK":          1103,
		"G2C_HELLO_ACK":       2001,
		"G2C_LOGIN_RES":       2002,
		"G2C_CHAR_LIST_RES":   2003,
		"G2C_CHAR_CREATE_RES": 2004,
		"G2C_ENTER_WORLD_RES": 2005,
		"G2C_PONG":            2007,
		"G2C_KICK":            2008,
		"G2C_ENTITY_SPAWN":    2101,
		"G2C_ENTITY_DESPAWN":  2102,
		"G2C_ENTITY_MOVE":     2103,
		"G2C_CHAT_MSG":        2104,
		"G2C_ENTITY_ACTION":   2105,
		"G2C_ENTITY_LIFE":     2106,
		"G2C_CHANGE_MAP":      2107,
		"G2C_ENTITY_MOVES":    2108,
		"GZ_ZONE_HELLO":       9001,
		"ZG_ZONE_HELLO_ACK":   9002,
		"GZ_SESSION_OPEN":     9003,
		"ZG_SESSION_OPEN_ACK": 9004,
		"GZ_SESSION_CLOSE":    9005,
		"GZ_CLIENT_PACKET":    9006,
		"ZG_ZONE_PACKET":      9007,
		"ZG_PLAYER_SAVE":      9008,
		"ZG_ZONE_STATS":       9009,
	}
)

func (x MsgId) Enum() *MsgId {
	p := new(MsgId)
	*p = x
	return p
}

func (x MsgId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgId) Descriptor() protoreflect.EnumDescriptor {
	return file_jx_msg_proto_enumTypes[1].Descriptor()
}

func (MsgId) Type() protoreflect.EnumType {
	return &file_jx_msg_proto_enumTypes[1]
}

func (x MsgId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgId.Descriptor instead.
func (MsgId) EnumDescriptor() ([]byte, []int) {
	return file_jx_msg_proto_rawDescGZIP(), []int{1}
}

var File_jx_msg_proto protoreflect.FileDescriptor

const file_jx_msg_proto_rawDesc = "" +
	"\n" +
	"\fjx/msg.proto\x12\x05jx.pb*:\n" +
	"\bProtocol\x12\x18\n" +
	"\x14PROTOCOL_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10PROTOCOL_VERSION\x10\x01*\xd6\x05\n" +
	"\x05MsgId\x12\f\n" +
	"\bMSG_NONE\x10\x00\x12\x0e\n" +
	"\tC2G_HELLO\x10\xe9\a\x12\x0e\n" +
	"\tC2G_LOGIN\x10\xea\a\x12\x12\n" +
	"\rC2G_CHAR_LIST\x10\xeb\a\x12\x14\n" +
	"\x0fC2G_CHAR_CREATE\x10\xec\a\x12\x14\n" +
	"\x0fC2G_ENTER_WORLD\x10\xed\a\x12\x14\n" +
	"\x0fC2G_LEAVE_WORLD\x10\xee\a\x12\r\n" +
	"\bC2G_PING\x10\xef\a\x12\r\n" +
	"\bC2G_MOVE\x10\xcd\b\x12\r\n" +
	"\bC2G_CHAT\x10\xce\b\x12\x0f\n" +
	"\n" +
	"C2G_ATTACK\x10\xcf\b\x12\x12\n" +
	"\rG2C_HELLO_ACK\x10\xd1\x0f\x12\x12\n" +
	"\rG2C_LOGIN_RES\x10\xd2\x0f\x12\x16\n" +
	"\x11G2C_CHAR_LIST_RES\x10\xd3\x0f\x12\x18\n" +
	"\x13G2C_CHAR_CREATE_RES\x10\xd4\x0f\x12\x18\n" +
	"\x13G2C_ENTER_WORLD_RES\x10\xd5\x0f\x12\r\n" +
	"\bG2C_PONG\x10\xd7\x0f\x12\r\n" +
	"\bG2C_KICK\x10\xd8\x0f\x12\x15\n" +
	"\x10G2C_ENTITY_SPAWN\x10\xb5\x10\x12\x17\n" +
	"\x12G2C_ENTITY_DESPAWN\x10\xb6\x10\x12\x14\n" +
	"\x0fG2C_ENTITY_MOVE\x10\xb7\x10\x12\x11\n" +
	"\fG2C_CHAT_MSG\x10\xb8\x10\x12\x16\n" +
	"\x11G2C_ENTITY_ACTION\x10\xb9\x10\x12\x14\n" +
	"\x0fG2C_ENTITY_LIFE\x10\xba\x10\x12\x13\n" +
	"\x0eG2C_CHANGE_MAP\x10\xbb\x10\x12\x15\n" +
	"\x10G2C_ENTITY_MOVES\x10\xbc\x10\x12\x12\n" +
	"\rGZ_ZONE_HELLO\x10\xa9F\x12\x16\n" +
	"\x11ZG_ZONE_HELLO_ACK\x10\xaaF\x12\x14\n" +
	"\x0fGZ_SESSION_OPEN\x10\xabF\x12\x18\n" +
	"\x13ZG_SESSION_OPEN_ACK\x10\xacF\x12\x15\n" +
	"\x10GZ_SESSION_CLOSE\x10\xadF\x12\x15\n" +
	"\x10GZ_CLIENT_PACKET\x10\xaeF\x12\x13\n" +
	"\x0eZG_ZONE_PACKET\x10\xafF\x12\x13\n" +
	"\x0eZG_PLAYER_SAVE\x10\xb0F\x12\x12\n" +
	"\rZG_ZONE_STATS\x10\xb1FB6Z4github.com/JXGAME04/DUANGODOT/next/services/pkg/jxpbb\x06proto3"

var (
	file_jx_msg_proto_rawDescOnce sync.Once
	file_jx_msg_proto_rawDescData []byte
)

func file_jx_msg_proto_rawDescGZIP() []byte {
	file_jx_msg_proto_rawDescOnce.Do(func() {
		file_jx_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jx_msg_proto_rawDesc), len(file_jx_msg_proto_rawDesc)))
	})
	return file_jx_msg_proto_rawDescData
}

var file_jx_msg_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_jx_msg_proto_goTypes = []any{
	(Protocol)(0), // 0: jx.pb.Protocol
	(MsgId)(0),    // 1: jx.pb.MsgId
}
var file_jx_msg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_jx_msg_proto_init() }
func file_jx_msg_proto_init() {
	if File_jx_msg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jx_msg_proto_rawDesc), len(file_jx_msg_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_jx_msg_proto_goTypes,
		DependencyIndexes: file_jx_msg_proto_depIdxs,
		EnumInfos:         file_jx_msg_proto_enumTypes,
	}.Build()
	File_jx_msg_proto = out.File
	file_jx_msg_proto_goTypes = nil
	file_jx_msg_proto_depIdxs = nil
}
