// Message id registry.  Every frame on the wire carries one of these ids (see docs/PROTOCOL.md).
//   1000-1999  C2G   client -> gateway
//   2000-2999  G2C   gateway -> client
//   9000-9999  internal gateway <-> zone
// Never reuse a number.  Ids marked (zone) are forwarded by the gateway to the zone as ClientPacket.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.4
// source: jx/msg.proto

package jxpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Protocol int32

const (
	Protocol_PROTOCOL_UNSPECIFIED Protocol = 0
	Protocol_PROTOCOL_VERSION     Protocol = 1
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0: "PROTOCOL_UNSPECIFIED",
		1: "PROTOCOL_VERSION",
	}
	Protocol_value = map[string]int32{
		"PROTOCOL_UNSPECIFIED": 0,
		"PROTOCOL_VERSION":     1,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_jx_msg_proto_enumTypes[0].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_jx_msg_proto_enumTypes[0]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_jx_msg_proto_rawDescGZIP(), []int{0}
}

type MsgId int32

const (
	MsgId_MSG_NONE MsgId = 0
	// client -> gateway
	MsgId_C2G_HELLO           MsgId = 1001
	MsgId_C2G_LOGIN           MsgId = 1002
	MsgId_C2G_CHAR_LIST       MsgId = 1003
	MsgId_C2G_CHAR_CREATE     MsgId = 1004
	MsgId_C2G_ENTER_WORLD     MsgId = 1005
	MsgId_C2G_LEAVE_WORLD     MsgId = 1006
	MsgId_C2G_PING            MsgId = 1007
	MsgId_C2G_MOVE            MsgId = 1101 // (zone)
	MsgId_C2G_CHAT            MsgId = 1102 // (zone)
	MsgId_C2G_ATTACK          MsgId = 1103 // (zone)
	MsgId_C2G_ITEM_MOVE       MsgId = 1104 // (zone) an item to another cell / room
	MsgId_C2G_ITEM_EQUIP      MsgId = 1105 // (zone) wear an item from the bag
	MsgId_C2G_ITEM_UNEQUIP    MsgId = 1106 // (zone) take a worn item off into the bag
	MsgId_C2G_ITEM_USE        MsgId = 1107 // (zone) eat a medicine / use an item
	MsgId_C2G_ITEM_DROP       MsgId = 1108 // (zone) throw an item away: it lies on the ground for a while
	MsgId_C2G_PICK_UP         MsgId = 1109 // (zone) pick up an item / money from the ground
	MsgId_C2G_ADD_POINT       MsgId = 1110 // (zone) spend attribute points (KPlayer::AddBaseStrength.. of the old c2s_playeraddattribute)
	MsgId_C2G_ADD_SKILL_POINT MsgId = 1111 // (zone) spend skill points on a skill (KPlayer::AddSkillPoint)
	MsgId_C2G_CAST_SKILL      MsgId = 1112 // (zone) cast a skill at a target or a spot (NpcSkillCommand -> KNpc::SendCommand(do_skill))
	MsgId_C2G_REVIVE          MsgId = 1113 // (zone) a dead character asks to revive at its revive point (the handler slot 118 -> KPlayer::Revive(0))
	MsgId_C2G_RIDE            MsgId = 1114 // (zone) mount / dismount the worn horse (0x080AEFA0 -> KNpc::SetHorse 0x0807D520)
	MsgId_C2G_SKILL_DESC      MsgId = 1115 // (zone) the numbers of a skill level for its tip (KSkill::GetDesc 0x006FBC90 of the 2.0 client runs the level script; the zone answers)
	// gateway -> client
	MsgId_G2C_HELLO_ACK       MsgId = 2001
	MsgId_G2C_LOGIN_RES       MsgId = 2002
	MsgId_G2C_CHAR_LIST_RES   MsgId = 2003
	MsgId_G2C_CHAR_CREATE_RES MsgId = 2004
	MsgId_G2C_ENTER_WORLD_RES MsgId = 2005
	MsgId_G2C_PONG            MsgId = 2007
	MsgId_G2C_KICK            MsgId = 2008
	MsgId_G2C_ENTITY_SPAWN    MsgId = 2101
	MsgId_G2C_ENTITY_DESPAWN  MsgId = 2102
	MsgId_G2C_ENTITY_MOVE     MsgId = 2103
	MsgId_G2C_CHAT_MSG        MsgId = 2104
	MsgId_G2C_ENTITY_ACTION   MsgId = 2105 // attack / hurt / death / revive (old NPC_HURT_SYNC, NPC_DEATH_SYNC, skill sync)
	MsgId_G2C_ENTITY_LIFE     MsgId = 2106
	MsgId_G2C_CHANGE_MAP      MsgId = 2107 // the zone moved the player to another map (NewWorld of a trap script)
	MsgId_G2C_ENTITY_MOVES    MsgId = 2108 // several EntityMove in one frame: what moved far from the receiver, every few ticks (N3)
	MsgId_G2C_ITEM_LIST       MsgId = 2109 // everything the character carries, on entering the world
	MsgId_G2C_ITEM_ADD        MsgId = 2110 // a new item, or a stack that changed (same id, new count)
	MsgId_G2C_ITEM_REMOVE     MsgId = 2111 // an item is gone (used up, dropped)
	MsgId_G2C_ITEM_MOVE       MsgId = 2112 // an item lies somewhere else now (also the answer to C2G_ITEM_MOVE / EQUIP / UNEQUIP)
	MsgId_G2C_ITEM_RESULT     MsgId = 2113 // a request that changed nothing, with why
	MsgId_G2C_MONEY           MsgId = 2114 // money in the bag and the repository
	MsgId_G2C_PLAYER_ATTRIB   MsgId = 2115 // the character's own numbers (CURPLAYER_SYNC + PLAYER_ATTRIBUTE_SYNC + PLAYER_LEVEL_UP_SYNC of the old game)
	MsgId_G2C_SKILL_LIST      MsgId = 2116 // every skill the character holds (s2c_synccurplayerskill)
	MsgId_G2C_SKILL_LEVEL     MsgId = 2117 // one skill's level / experience / the skill points left (the 0x5e packet)
	MsgId_G2C_SKILL_FORBID    MsgId = 2118 // a skill (or all) locked or freed (the 0x63 packet)
	MsgId_G2C_ENTITY_RIDE     MsgId = 2119 // a npc mounted or dismounted (the 0x20 flag of the old 0x4c / 0x4d sync)
	MsgId_G2C_ENTITY_CAMP     MsgId = 2120 // a npc's camp changed (the 0x59 packet)
	MsgId_G2C_PLAYER_FACTION  MsgId = 2121 // the character's faction record (the 0x7b packet; 0x7c = cleared)
	MsgId_G2C_ENTITY_STATE    MsgId = 2122 // a skill's timed state on the character (the 0x87 packet; empty = removed)
	MsgId_G2C_SKILL_DESC      MsgId = 2123 // the answer to C2G_SKILL_DESC: cost / range / attributes of the level shown and of the next one
	MsgId_G2C_MISSLE          MsgId = 2124 // a missile of a cast: born, flying (a position every 6 frames), gone - the client draws it (the 2.0 client re-runs CastMissles from the 0x5a packet instead)
	// gateway <-> zone
	MsgId_GZ_ZONE_HELLO       MsgId = 9001
	MsgId_ZG_ZONE_HELLO_ACK   MsgId = 9002
	MsgId_GZ_SESSION_OPEN     MsgId = 9003
	MsgId_ZG_SESSION_OPEN_ACK MsgId = 9004
	MsgId_GZ_SESSION_CLOSE    MsgId = 9005
	MsgId_GZ_CLIENT_PACKET    MsgId = 9006
	MsgId_ZG_ZONE_PACKET      MsgId = 9007
	MsgId_ZG_PLAYER_SAVE      MsgId = 9008
	MsgId_ZG_ZONE_STATS       MsgId = 9009
)

// Enum value maps for MsgId.
var (
	MsgId_name = map[int32]string{
		0:    "MSG_NONE",
		1001: "C2G_HELLO",
		1002: "C2G_LOGIN",
		1003: "C2G_CHAR_LIST",
		1004: "C2G_CHAR_CREATE",
		1005: "C2G_ENTER_WORLD",
		1006: "C2G_LEAVE_WORLD",
		1007: "C2G_PING",
		1101: "C2G_MOVE",
		1102: "C2G_CHAT",
		1103: "C2G_ATTACK",
		1104: "C2G_ITEM_MOVE",
		1105: "C2G_ITEM_EQUIP",
		1106: "C2G_ITEM_UNEQUIP",
		1107: "C2G_ITEM_USE",
		1108: "C2G_ITEM_DROP",
		1109: "C2G_PICK_UP",
		1110: "C2G_ADD_POINT",
		1111: "C2G_ADD_SKILL_POINT",
		1112: "C2G_CAST_SKILL",
		1113: "C2G_REVIVE",
		1114: "C2G_RIDE",
		1115: "C2G_SKILL_DESC",
		2001: "G2C_HELLO_ACK",
		2002: "G2C_LOGIN_RES",
		2003: "G2C_CHAR_LIST_RES",
		2004: "G2C_CHAR_CREATE_RES",
		2005: "G2C_ENTER_WORLD_RES",
		2007: "G2C_PONG",
		2008: "G2C_KICK",
		2101: "G2C_ENTITY_SPAWN",
		2102: "G2C_ENTITY_DESPAWN",
		2103: "G2C_ENTITY_MOVE",
		2104: "G2C_CHAT_MSG",
		2105: "G2C_ENTITY_ACTION",
		2106: "G2C_ENTITY_LIFE",
		2107: "G2C_CHANGE_MAP",
		2108: "G2C_ENTITY_MOVES",
		2109: "G2C_ITEM_LIST",
		2110: "G2C_ITEM_ADD",
		2111: "G2C_ITEM_REMOVE",
		2112: "G2C_ITEM_MOVE",
		2113: "G2C_ITEM_RESULT",
		2114: "G2C_MONEY",
		2115: "G2C_PLAYER_ATTRIB",
		2116: "G2C_SKILL_LIST",
		2117: "G2C_SKILL_LEVEL",
		2118: "G2C_SKILL_FORBID",
		2119: "G2C_ENTITY_RIDE",
		2120: "G2C_ENTITY_CAMP",
		2121: "G2C_PLAYER_FACTION",
		2122: "G2C_ENTITY_STATE",
		2123: "G2C_SKILL_DESC",
		2124: "G2C_MISSLE",
		9001: "GZ_ZONE_HELLO",
		9002: "ZG_ZONE_HELLO_ACK",
		9003: "GZ_SESSION_OPEN",
		9004: "ZG_SESSION_OPEN_ACK",
		9005: "GZ_SESSION_CLOSE",
		9006: "GZ_CLIENT_PACKET",
		9007: "ZG_ZONE_PACKET",
		9008: "ZG_PLAYER_SAVE",
		9009: "ZG_ZONE_STATS",
	}
	MsgId_value = map[string]int32{
		"MSG_NONE":            0,
		"C2G_HELLO":           1001,
		"C2G_LOGIN":           1002,
		"C2G_CHAR_LIST":       1003,
		"C2G_CHAR_CREATE":     1004,
		"C2G_ENTER_WORLD":     1005,
		"C2G_LEAVE_WORLD":     1006,
		"C2G_PING":            1007,
		"C2G_MOVE":            1101,
		"C2G_CHAT":            1102,
		"C2G_ATTACK":          1103,
		"C2G_ITEM_MOVE":       1104,
		"C2G_ITEM_EQUIP":      1105,
		"C2G_ITEM_UNEQUIP":    1106,
		"C2G_ITEM_USE":        1107,
		"C2G_ITEM_DROP":       1108,
		"C2G_PICK_UP":         1109,
		"C2G_ADD_POINT":       1110,
		"C2G_ADD_SKILL_POINT": 1111,
		"C2G_CAST_SKILL":      1112,
		"C2G_REVIVE":          1113,
		"C2G_RIDE":            1114,
		"C2G_SKILL_DESC":      1115,
		"G2C_HELLO_ACK":       2001,
		"G2C_LOGIN_RES":       2002,
		"G2C_CHAR_LIST_RES":   2003,
		"G2C_CHAR_CREATE_RES": 2004,
		"G2C_ENTER_WORLD_RES": 2005,
		"G2C_PONG":            2007,
		"G2C_KICK":            2008,
		"G2C_ENTITY_SPAWN":    2101,
		"G2C_ENTITY_DESPAWN":  2102,
		"G2C_ENTITY_MOVE":     2103,
		"G2C_CHAT_MSG":        2104,
		"G2C_ENTITY_ACTION":   2105,
		"G2C_ENTITY_LIFE":     2106,
		"G2C_CHANGE_MAP":      2107,
		"G2C_ENTITY_MOVES":    2108,
		"G2C_ITEM_LIST":       2109,
		"G2C_ITEM_ADD":        2110,
		"G2C_ITEM_REMOVE":     2111,
		"G2C_ITEM_MOVE":       2112,
		"G2C_ITEM_RESULT":     2113,
		"G2C_MONEY":           2114,
		"G2C_PLAYER_ATTRIB":   2115,
		"G2C_SKILL_LIST":      2116,
		"G2C_SKILL_LEVEL":     2117,
		"G2C_SKILL_FORBID":    2118,
		"G2C_ENTITY_RIDE":     2119,
		"G2C_ENTITY_CAMP":     2120,
		"G2C_PLAYER_FACTION":  2121,
		"G2C_ENTITY_STATE":    2122,
		"G2C_SKILL_DESC":      2123,
		"G2C_MISSLE":          2124,
		"GZ_ZONE_HELLO":       9001,
		"ZG_ZONE_HELLO_ACK":   9002,
		"GZ_SESSION_OPEN":     9003,
		"ZG_SESSION_OPEN_ACK": 9004,
		"GZ_SESSION_CLOSE":    9005,
		"GZ_CLIENT_PACKET":    9006,
		"ZG_ZONE_PACKET":      9007,
		"ZG_PLAYER_SAVE":      9008,
		"ZG_ZONE_STATS":       9009,
	}
)

func (x MsgId) Enum() *MsgId {
	p := new(MsgId)
	*p = x
	return p
}

func (x MsgId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgId) Descriptor() protoreflect.EnumDescriptor {
	return file_jx_msg_proto_enumTypes[1].Descriptor()
}

func (MsgId) Type() protoreflect.EnumType {
	return &file_jx_msg_proto_enumTypes[1]
}

func (x MsgId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgId.Descriptor instead.
func (MsgId) EnumDescriptor() ([]byte, []int) {
	return file_jx_msg_proto_rawDescGZIP(), []int{1}
}

var File_jx_msg_proto protoreflect.FileDescriptor

const file_jx_msg_proto_rawDesc = "" +
	"\n" +
	"\fjx/msg.proto\x12\x05jx.pb*:\n" +
	"\bProtocol\x12\x18\n" +
	"\x14PROTOCOL_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10PROTOCOL_VERSION\x10\x01*\x9a\n" +
	"\n" +
	"\x05MsgId\x12\f\n" +
	"\bMSG_NONE\x10\x00\x12\x0e\n" +
	"\tC2G_HELLO\x10\xe9\a\x12\x0e\n" +
	"\tC2G_LOGIN\x10\xea\a\x12\x12\n" +
	"\rC2G_CHAR_LIST\x10\xeb\a\x12\x14\n" +
	"\x0fC2G_CHAR_CREATE\x10\xec\a\x12\x14\n" +
	"\x0fC2G_ENTER_WORLD\x10\xed\a\x12\x14\n" +
	"\x0fC2G_LEAVE_WORLD\x10\xee\a\x12\r\n" +
	"\bC2G_PING\x10\xef\a\x12\r\n" +
	"\bC2G_MOVE\x10\xcd\b\x12\r\n" +
	"\bC2G_CHAT\x10\xce\b\x12\x0f\n" +
	"\n" +
	"C2G_ATTACK\x10\xcf\b\x12\x12\n" +
	"\rC2G_ITEM_MOVE\x10\xd0\b\x12\x13\n" +
	"\x0eC2G_ITEM_EQUIP\x10\xd1\b\x12\x15\n" +
	"\x10C2G_ITEM_UNEQUIP\x10\xd2\b\x12\x11\n" +
	"\fC2G_ITEM_USE\x10\xd3\b\x12\x12\n" +
	"\rC2G_ITEM_DROP\x10\xd4\b\x12\x10\n" +
	"\vC2G_PICK_UP\x10\xd5\b\x12\x12\n" +
	"\rC2G_ADD_POINT\x10\xd6\b\x12\x18\n" +
	"\x13C2G_ADD_SKILL_POINT\x10\xd7\b\x12\x13\n" +
	"\x0eC2G_CAST_SKILL\x10\xd8\b\x12\x0f\n" +
	"\n" +
	"C2G_REVIVE\x10\xd9\b\x12\r\n" +
	"\bC2G_RIDE\x10\xda\b\x12\x13\n" +
	"\x0eC2G_SKILL_DESC\x10\xdb\b\x12\x12\n" +
	"\rG2C_HELLO_ACK\x10\xd1\x0f\x12\x12\n" +
	"\rG2C_LOGIN_RES\x10\xd2\x0f\x12\x16\n" +
	"\x11G2C_CHAR_LIST_RES\x10\xd3\x0f\x12\x18\n" +
	"\x13G2C_CHAR_CREATE_RES\x10\xd4\x0f\x12\x18\n" +
	"\x13G2C_ENTER_WORLD_RES\x10\xd5\x0f\x12\r\n" +
	"\bG2C_PONG\x10\xd7\x0f\x12\r\n" +
	"\bG2C_KICK\x10\xd8\x0f\x12\x15\n" +
	"\x10G2C_ENTITY_SPAWN\x10\xb5\x10\x12\x17\n" +
	"\x12G2C_ENTITY_DESPAWN\x10\xb6\x10\x12\x14\n" +
	"\x0fG2C_ENTITY_MOVE\x10\xb7\x10\x12\x11\n" +
	"\fG2C_CHAT_MSG\x10\xb8\x10\x12\x16\n" +
	"\x11G2C_ENTITY_ACTION\x10\xb9\x10\x12\x14\n" +
	"\x0fG2C_ENTITY_LIFE\x10\xba\x10\x12\x13\n" +
	"\x0eG2C_CHANGE_MAP\x10\xbb\x10\x12\x15\n" +
	"\x10G2C_ENTITY_MOVES\x10\xbc\x10\x12\x12\n" +
	"\rG2C_ITEM_LIST\x10\xbd\x10\x12\x11\n" +
	"\fG2C_ITEM_ADD\x10\xbe\x10\x12\x14\n" +
	"\x0fG2C_ITEM_REMOVE\x10\xbf\x10\x12\x12\n" +
	"\rG2C_ITEM_MOVE\x10\xc0\x10\x12\x14\n" +
	"\x0fG2C_ITEM_RESULT\x10\xc1\x10\x12\x0e\n" +
	"\tG2C_MONEY\x10\xc2\x10\x12\x16\n" +
	"\x11G2C_PLAYER_ATTRIB\x10\xc3\x10\x12\x13\n" +
	"\x0eG2C_SKILL_LIST\x10\xc4\x10\x12\x14\n" +
	"\x0fG2C_SKILL_LEVEL\x10\xc5\x10\x12\x15\n" +
	"\x10G2C_SKILL_FORBID\x10\xc6\x10\x12\x14\n" +
	"\x0fG2C_ENTITY_RIDE\x10\xc7\x10\x12\x14\n" +
	"\x0fG2C_ENTITY_CAMP\x10\xc8\x10\x12\x17\n" +
	"\x12G2C_PLAYER_FACTION\x10\xc9\x10\x12\x15\n" +
	"\x10G2C_ENTITY_STATE\x10\xca\x10\x12\x13\n" +
	"\x0eG2C_SKILL_DESC\x10\xcb\x10\x12\x0f\n" +
	"\n" +
	"G2C_MISSLE\x10\xcc\x10\x12\x12\n" +
	"\rGZ_ZONE_HELLO\x10\xa9F\x12\x16\n" +
	"\x11ZG_ZONE_HELLO_ACK\x10\xaaF\x12\x14\n" +
	"\x0fGZ_SESSION_OPEN\x10\xabF\x12\x18\n" +
	"\x13ZG_SESSION_OPEN_ACK\x10\xacF\x12\x15\n" +
	"\x10GZ_SESSION_CLOSE\x10\xadF\x12\x15\n" +
	"\x10GZ_CLIENT_PACKET\x10\xaeF\x12\x13\n" +
	"\x0eZG_ZONE_PACKET\x10\xafF\x12\x13\n" +
	"\x0eZG_PLAYER_SAVE\x10\xb0F\x12\x12\n" +
	"\rZG_ZONE_STATS\x10\xb1FB6Z4github.com/JXGAME04/DUANGODOT/next/services/pkg/jxpbb\x06proto3"

var (
	file_jx_msg_proto_rawDescOnce sync.Once
	file_jx_msg_proto_rawDescData []byte
)

func file_jx_msg_proto_rawDescGZIP() []byte {
	file_jx_msg_proto_rawDescOnce.Do(func() {
		file_jx_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jx_msg_proto_rawDesc), len(file_jx_msg_proto_rawDesc)))
	})
	return file_jx_msg_proto_rawDescData
}

var file_jx_msg_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_jx_msg_proto_goTypes = []any{
	(Protocol)(0), // 0: jx.pb.Protocol
	(MsgId)(0),    // 1: jx.pb.MsgId
}
var file_jx_msg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_jx_msg_proto_init() }
func file_jx_msg_proto_init() {
	if File_jx_msg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jx_msg_proto_rawDesc), len(file_jx_msg_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_jx_msg_proto_goTypes,
		DependencyIndexes: file_jx_msg_proto_depIdxs,
		EnumInfos:         file_jx_msg_proto_enumTypes,
	}.Build()
	File_jx_msg_proto = out.File
	file_jx_msg_proto_goTypes = nil
	file_jx_msg_proto_depIdxs = nil
}
