// Persistent character data ("RoleData").  This is the model every layer agrees on:
// persist stores it, the zone loads/saves it, the client receives a projection of it.
// Add fields freely; never renumber or reuse a tag.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.4
// source: jx/role.proto

package jxpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RolePosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneId        uint32                 `protobuf:"varint,1,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"` // logical zone/map id
	Pos           *Vec2                  `protobuf:"bytes,2,opt,name=pos,proto3" json:"pos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolePosition) Reset() {
	*x = RolePosition{}
	mi := &file_jx_role_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolePosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePosition) ProtoMessage() {}

func (x *RolePosition) ProtoReflect() protoreflect.Message {
	mi := &file_jx_role_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePosition.ProtoReflect.Descriptor instead.
func (*RolePosition) Descriptor() ([]byte, []int) {
	return file_jx_role_proto_rawDescGZIP(), []int{0}
}

func (x *RolePosition) GetZoneId() uint32 {
	if x != nil {
		return x.ZoneId
	}
	return 0
}

func (x *RolePosition) GetPos() *Vec2 {
	if x != nil {
		return x.Pos
	}
	return nil
}

type RoleStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hp            int32                  `protobuf:"varint,1,opt,name=hp,proto3" json:"hp,omitempty"`
	HpMax         int32                  `protobuf:"varint,2,opt,name=hp_max,json=hpMax,proto3" json:"hp_max,omitempty"`
	Mp            int32                  `protobuf:"varint,3,opt,name=mp,proto3" json:"mp,omitempty"`
	MpMax         int32                  `protobuf:"varint,4,opt,name=mp_max,json=mpMax,proto3" json:"mp_max,omitempty"`
	Stamina       int32                  `protobuf:"varint,5,opt,name=stamina,proto3" json:"stamina,omitempty"`
	StaminaMax    int32                  `protobuf:"varint,6,opt,name=stamina_max,json=staminaMax,proto3" json:"stamina_max,omitempty"`
	Strength      int32                  `protobuf:"varint,7,opt,name=strength,proto3" json:"strength,omitempty"`
	Dexterity     int32                  `protobuf:"varint,8,opt,name=dexterity,proto3" json:"dexterity,omitempty"`
	Vitality      int32                  `protobuf:"varint,9,opt,name=vitality,proto3" json:"vitality,omitempty"`
	Energy        int32                  `protobuf:"varint,10,opt,name=energy,proto3" json:"energy,omitempty"`
	MoveSpeed     int32                  `protobuf:"varint,11,opt,name=move_speed,json=moveSpeed,proto3" json:"move_speed,omitempty"` // units per second
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleStats) Reset() {
	*x = RoleStats{}
	mi := &file_jx_role_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleStats) ProtoMessage() {}

func (x *RoleStats) ProtoReflect() protoreflect.Message {
	mi := &file_jx_role_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleStats.ProtoReflect.Descriptor instead.
func (*RoleStats) Descriptor() ([]byte, []int) {
	return file_jx_role_proto_rawDescGZIP(), []int{1}
}

func (x *RoleStats) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *RoleStats) GetHpMax() int32 {
	if x != nil {
		return x.HpMax
	}
	return 0
}

func (x *RoleStats) GetMp() int32 {
	if x != nil {
		return x.Mp
	}
	return 0
}

func (x *RoleStats) GetMpMax() int32 {
	if x != nil {
		return x.MpMax
	}
	return 0
}

func (x *RoleStats) GetStamina() int32 {
	if x != nil {
		return x.Stamina
	}
	return 0
}

func (x *RoleStats) GetStaminaMax() int32 {
	if x != nil {
		return x.StaminaMax
	}
	return 0
}

func (x *RoleStats) GetStrength() int32 {
	if x != nil {
		return x.Strength
	}
	return 0
}

func (x *RoleStats) GetDexterity() int32 {
	if x != nil {
		return x.Dexterity
	}
	return 0
}

func (x *RoleStats) GetVitality() int32 {
	if x != nil {
		return x.Vitality
	}
	return 0
}

func (x *RoleStats) GetEnergy() int32 {
	if x != nil {
		return x.Energy
	}
	return 0
}

func (x *RoleStats) GetMoveSpeed() int32 {
	if x != nil {
		return x.MoveSpeed
	}
	return 0
}

type RoleItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemUid       uint64                 `protobuf:"varint,1,opt,name=item_uid,json=itemUid,proto3" json:"item_uid,omitempty"`
	TemplateId    uint32                 `protobuf:"varint,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Count         uint32                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Slot          uint32                 `protobuf:"varint,4,opt,name=slot,proto3" json:"slot,omitempty"` // container/slot are decided by the inventory design (phase 2)
	Container     uint32                 `protobuf:"varint,5,opt,name=container,proto3" json:"container,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleItem) Reset() {
	*x = RoleItem{}
	mi := &file_jx_role_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleItem) ProtoMessage() {}

func (x *RoleItem) ProtoReflect() protoreflect.Message {
	mi := &file_jx_role_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleItem.ProtoReflect.Descriptor instead.
func (*RoleItem) Descriptor() ([]byte, []int) {
	return file_jx_role_proto_rawDescGZIP(), []int{2}
}

func (x *RoleItem) GetItemUid() uint64 {
	if x != nil {
		return x.ItemUid
	}
	return 0
}

func (x *RoleItem) GetTemplateId() uint32 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *RoleItem) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *RoleItem) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *RoleItem) GetContainer() uint32 {
	if x != nil {
		return x.Container
	}
	return 0
}

type RoleData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	AccountId     uint64                 `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"` // UTF-8, validated by the auth/persist layer
	Level         uint32                 `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	Exp           uint64                 `protobuf:"varint,5,opt,name=exp,proto3" json:"exp,omitempty"`
	Series        uint32                 `protobuf:"varint,6,opt,name=series,proto3" json:"series,omitempty"` // five elements (metal, wood, water, fire, earth) as in the old game
	Sex           uint32                 `protobuf:"varint,7,opt,name=sex,proto3" json:"sex,omitempty"`
	Faction       uint32                 `protobuf:"varint,8,opt,name=faction,proto3" json:"faction,omitempty"`
	Position      *RolePosition          `protobuf:"bytes,9,opt,name=position,proto3" json:"position,omitempty"`
	Stats         *RoleStats             `protobuf:"bytes,10,opt,name=stats,proto3" json:"stats,omitempty"`
	Items         []*RoleItem            `protobuf:"bytes,11,rep,name=items,proto3" json:"items,omitempty"`
	CreatedAtMs   uint64                 `protobuf:"varint,12,opt,name=created_at_ms,json=createdAtMs,proto3" json:"created_at_ms,omitempty"`
	LastLoginMs   uint64                 `protobuf:"varint,13,opt,name=last_login_ms,json=lastLoginMs,proto3" json:"last_login_ms,omitempty"`
	PlayTimeS     uint64                 `protobuf:"varint,14,opt,name=play_time_s,json=playTimeS,proto3" json:"play_time_s,omitempty"`
	DataVersion   uint32                 `protobuf:"varint,15,opt,name=data_version,json=dataVersion,proto3" json:"data_version,omitempty"` // bump when a migration is required
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleData) Reset() {
	*x = RoleData{}
	mi := &file_jx_role_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleData) ProtoMessage() {}

func (x *RoleData) ProtoReflect() protoreflect.Message {
	mi := &file_jx_role_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleData.ProtoReflect.Descriptor instead.
func (*RoleData) Descriptor() ([]byte, []int) {
	return file_jx_role_proto_rawDescGZIP(), []int{3}
}

func (x *RoleData) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *RoleData) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *RoleData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleData) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *RoleData) GetExp() uint64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *RoleData) GetSeries() uint32 {
	if x != nil {
		return x.Series
	}
	return 0
}

func (x *RoleData) GetSex() uint32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *RoleData) GetFaction() uint32 {
	if x != nil {
		return x.Faction
	}
	return 0
}

func (x *RoleData) GetPosition() *RolePosition {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *RoleData) GetStats() *RoleStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *RoleData) GetItems() []*RoleItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *RoleData) GetCreatedAtMs() uint64 {
	if x != nil {
		return x.CreatedAtMs
	}
	return 0
}

func (x *RoleData) GetLastLoginMs() uint64 {
	if x != nil {
		return x.LastLoginMs
	}
	return 0
}

func (x *RoleData) GetPlayTimeS() uint64 {
	if x != nil {
		return x.PlayTimeS
	}
	return 0
}

func (x *RoleData) GetDataVersion() uint32 {
	if x != nil {
		return x.DataVersion
	}
	return 0
}

var File_jx_role_proto protoreflect.FileDescriptor

const file_jx_role_proto_rawDesc = "" +
	"\n" +
	"\rjx/role.proto\x12\x05jx.pb\x1a\x0fjx/common.proto\"F\n" +
	"\fRolePosition\x12\x17\n" +
	"\azone_id\x18\x01 \x01(\rR\x06zoneId\x12\x1d\n" +
	"\x03pos\x18\x02 \x01(\v2\v.jx.pb.Vec2R\x03pos\"\xa1\x02\n" +
	"\tRoleStats\x12\x0e\n" +
	"\x02hp\x18\x01 \x01(\x05R\x02hp\x12\x15\n" +
	"\x06hp_max\x18\x02 \x01(\x05R\x05hpMax\x12\x0e\n" +
	"\x02mp\x18\x03 \x01(\x05R\x02mp\x12\x15\n" +
	"\x06mp_max\x18\x04 \x01(\x05R\x05mpMax\x12\x18\n" +
	"\astamina\x18\x05 \x01(\x05R\astamina\x12\x1f\n" +
	"\vstamina_max\x18\x06 \x01(\x05R\n" +
	"staminaMax\x12\x1a\n" +
	"\bstrength\x18\a \x01(\x05R\bstrength\x12\x1c\n" +
	"\tdexterity\x18\b \x01(\x05R\tdexterity\x12\x1a\n" +
	"\bvitality\x18\t \x01(\x05R\bvitality\x12\x16\n" +
	"\x06energy\x18\n" +
	" \x01(\x05R\x06energy\x12\x1d\n" +
	"\n" +
	"move_speed\x18\v \x01(\x05R\tmoveSpeed\"\x8e\x01\n" +
	"\bRoleItem\x12\x19\n" +
	"\bitem_uid\x18\x01 \x01(\x04R\aitemUid\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\rR\n" +
	"templateId\x12\x14\n" +
	"\x05count\x18\x03 \x01(\rR\x05count\x12\x12\n" +
	"\x04slot\x18\x04 \x01(\rR\x04slot\x12\x1c\n" +
	"\tcontainer\x18\x05 \x01(\rR\tcontainer\"\xd1\x03\n" +
	"\bRoleData\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x04R\taccountId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x04 \x01(\rR\x05level\x12\x10\n" +
	"\x03exp\x18\x05 \x01(\x04R\x03exp\x12\x16\n" +
	"\x06series\x18\x06 \x01(\rR\x06series\x12\x10\n" +
	"\x03sex\x18\a \x01(\rR\x03sex\x12\x18\n" +
	"\afaction\x18\b \x01(\rR\afaction\x12/\n" +
	"\bposition\x18\t \x01(\v2\x13.jx.pb.RolePositionR\bposition\x12&\n" +
	"\x05stats\x18\n" +
	" \x01(\v2\x10.jx.pb.RoleStatsR\x05stats\x12%\n" +
	"\x05items\x18\v \x03(\v2\x0f.jx.pb.RoleItemR\x05items\x12\"\n" +
	"\rcreated_at_ms\x18\f \x01(\x04R\vcreatedAtMs\x12\"\n" +
	"\rlast_login_ms\x18\r \x01(\x04R\vlastLoginMs\x12\x1e\n" +
	"\vplay_time_s\x18\x0e \x01(\x04R\tplayTimeS\x12!\n" +
	"\fdata_version\x18\x0f \x01(\rR\vdataVersionB6Z4github.com/JXGAME04/DUANGODOT/next/services/pkg/jxpbb\x06proto3"

var (
	file_jx_role_proto_rawDescOnce sync.Once
	file_jx_role_proto_rawDescData []byte
)

func file_jx_role_proto_rawDescGZIP() []byte {
	file_jx_role_proto_rawDescOnce.Do(func() {
		file_jx_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jx_role_proto_rawDesc), len(file_jx_role_proto_rawDesc)))
	})
	return file_jx_role_proto_rawDescData
}

var file_jx_role_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_jx_role_proto_goTypes = []any{
	(*RolePosition)(nil), // 0: jx.pb.RolePosition
	(*RoleStats)(nil),    // 1: jx.pb.RoleStats
	(*RoleItem)(nil),     // 2: jx.pb.RoleItem
	(*RoleData)(nil),     // 3: jx.pb.RoleData
	(*Vec2)(nil),         // 4: jx.pb.Vec2
}
var file_jx_role_proto_depIdxs = []int32{
	4, // 0: jx.pb.RolePosition.pos:type_name -> jx.pb.Vec2
	0, // 1: jx.pb.RoleData.position:type_name -> jx.pb.RolePosition
	1, // 2: jx.pb.RoleData.stats:type_name -> jx.pb.RoleStats
	2, // 3: jx.pb.RoleData.items:type_name -> jx.pb.RoleItem
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_jx_role_proto_init() }
func file_jx_role_proto_init() {
	if File_jx_role_proto != nil {
		return
	}
	file_jx_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jx_role_proto_rawDesc), len(file_jx_role_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_jx_role_proto_goTypes,
		DependencyIndexes: file_jx_role_proto_depIdxs,
		MessageInfos:      file_jx_role_proto_msgTypes,
	}.Build()
	File_jx_role_proto = out.File
	file_jx_role_proto_goTypes = nil
	file_jx_role_proto_depIdxs = nil
}
