// Persistent character data ("RoleData").  This is the model every layer agrees on:
// persist stores it, the zone loads/saves it, the client receives a projection of it.
// Add fields freely; never renumber or reuse a tag.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.4
// source: jx/role.proto

package jxpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RolePosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneId        uint32                 `protobuf:"varint,1,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"` // logical zone id
	Pos           *Vec2                  `protobuf:"bytes,2,opt,name=pos,proto3" json:"pos,omitempty"`
	MapId         uint32                 `protobuf:"varint,3,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"` // map bundle within the zone (0 = the zone's default map)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolePosition) Reset() {
	*x = RolePosition{}
	mi := &file_jx_role_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolePosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePosition) ProtoMessage() {}

func (x *RolePosition) ProtoReflect() protoreflect.Message {
	mi := &file_jx_role_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePosition.ProtoReflect.Descriptor instead.
func (*RolePosition) Descriptor() ([]byte, []int) {
	return file_jx_role_proto_rawDescGZIP(), []int{0}
}

func (x *RolePosition) GetZoneId() uint32 {
	if x != nil {
		return x.ZoneId
	}
	return 0
}

func (x *RolePosition) GetPos() *Vec2 {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *RolePosition) GetMapId() uint32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

// The character's own numbers, the way TRoleData of the JX2 server keeps them (KPlayer::LoadFrom,
// docs/LINUX-SERVER.md §10): hp_max / mp_max are the BASE maxima (m_LifeMax / m_ManaMax: levels
// and attribute points, before equipment); stamina_max is recomputed from the level tables; the
// five points are the base points (m_nStrength.. the player put there), the current ones are
// derived every time the zone recalculates.
type RoleStats struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Hp             int32                  `protobuf:"varint,1,opt,name=hp,proto3" json:"hp,omitempty"`
	HpMax          int32                  `protobuf:"varint,2,opt,name=hp_max,json=hpMax,proto3" json:"hp_max,omitempty"`
	Mp             int32                  `protobuf:"varint,3,opt,name=mp,proto3" json:"mp,omitempty"`
	MpMax          int32                  `protobuf:"varint,4,opt,name=mp_max,json=mpMax,proto3" json:"mp_max,omitempty"`
	Stamina        int32                  `protobuf:"varint,5,opt,name=stamina,proto3" json:"stamina,omitempty"`
	StaminaMax     int32                  `protobuf:"varint,6,opt,name=stamina_max,json=staminaMax,proto3" json:"stamina_max,omitempty"`
	Strength       int32                  `protobuf:"varint,7,opt,name=strength,proto3" json:"strength,omitempty"`
	Dexterity      int32                  `protobuf:"varint,8,opt,name=dexterity,proto3" json:"dexterity,omitempty"`
	Vitality       int32                  `protobuf:"varint,9,opt,name=vitality,proto3" json:"vitality,omitempty"`
	Energy         int32                  `protobuf:"varint,10,opt,name=energy,proto3" json:"energy,omitempty"`
	MoveSpeed      int32                  `protobuf:"varint,11,opt,name=move_speed,json=moveSpeed,proto3" json:"move_speed,omitempty"`                // units per second
	Lucky          int32                  `protobuf:"varint,12,opt,name=lucky,proto3" json:"lucky,omitempty"`                                         // m_nLucky
	AttributePoint int32                  `protobuf:"varint,13,opt,name=attribute_point,json=attributePoint,proto3" json:"attribute_point,omitempty"` // m_nAttributePoint: unspent (5 per level)
	SkillPoint     int32                  `protobuf:"varint,14,opt,name=skill_point,json=skillPoint,proto3" json:"skill_point,omitempty"`             // m_nSkillPoint: unspent (1 per level)
	Reborn         uint32                 `protobuf:"varint,15,opt,name=reborn,proto3" json:"reborn,omitempty"`                                       // times reborn (KPlayer+0x86b8, <= 7): picks the experience table
	Camp           uint32                 `protobuf:"varint,16,opt,name=camp,proto3" json:"camp,omitempty"`                                           // m_Camp (BaseInfo.iteam)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RoleStats) Reset() {
	*x = RoleStats{}
	mi := &file_jx_role_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleStats) ProtoMessage() {}

func (x *RoleStats) ProtoReflect() protoreflect.Message {
	mi := &file_jx_role_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleStats.ProtoReflect.Descriptor instead.
func (*RoleStats) Descriptor() ([]byte, []int) {
	return file_jx_role_proto_rawDescGZIP(), []int{1}
}

func (x *RoleStats) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *RoleStats) GetHpMax() int32 {
	if x != nil {
		return x.HpMax
	}
	return 0
}

func (x *RoleStats) GetMp() int32 {
	if x != nil {
		return x.Mp
	}
	return 0
}

func (x *RoleStats) GetMpMax() int32 {
	if x != nil {
		return x.MpMax
	}
	return 0
}

func (x *RoleStats) GetStamina() int32 {
	if x != nil {
		return x.Stamina
	}
	return 0
}

func (x *RoleStats) GetStaminaMax() int32 {
	if x != nil {
		return x.StaminaMax
	}
	return 0
}

func (x *RoleStats) GetStrength() int32 {
	if x != nil {
		return x.Strength
	}
	return 0
}

func (x *RoleStats) GetDexterity() int32 {
	if x != nil {
		return x.Dexterity
	}
	return 0
}

func (x *RoleStats) GetVitality() int32 {
	if x != nil {
		return x.Vitality
	}
	return 0
}

func (x *RoleStats) GetEnergy() int32 {
	if x != nil {
		return x.Energy
	}
	return 0
}

func (x *RoleStats) GetMoveSpeed() int32 {
	if x != nil {
		return x.MoveSpeed
	}
	return 0
}

func (x *RoleStats) GetLucky() int32 {
	if x != nil {
		return x.Lucky
	}
	return 0
}

func (x *RoleStats) GetAttributePoint() int32 {
	if x != nil {
		return x.AttributePoint
	}
	return 0
}

func (x *RoleStats) GetSkillPoint() int32 {
	if x != nil {
		return x.SkillPoint
	}
	return 0
}

func (x *RoleStats) GetReborn() uint32 {
	if x != nil {
		return x.Reborn
	}
	return 0
}

func (x *RoleStats) GetCamp() uint32 {
	if x != nil {
		return x.Camp
	}
	return 0
}

// One attribute of an item (KMagicAttrib of the old core): a type and up to three parameters.
type ItemMagic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          uint32                 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Value         []int32                `protobuf:"varint,2,rep,packed,name=value,proto3" json:"value,omitempty"` // 3 values
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemMagic) Reset() {
	*x = ItemMagic{}
	mi := &file_jx_role_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemMagic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemMagic) ProtoMessage() {}

func (x *ItemMagic) ProtoReflect() protoreflect.Message {
	mi := &file_jx_role_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemMagic.ProtoReflect.Descriptor instead.
func (*ItemMagic) Descriptor() ([]byte, []int) {
	return file_jx_role_proto_rawDescGZIP(), []int{2}
}

func (x *ItemMagic) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ItemMagic) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

// One item a character holds (KItem + its place in KItemList; docs/OLD-TO-NEW.md).  What made
// the item is kept (version, genre/detail/particular/level, gen_param) so its table row can be
// found again, and what was rolled for it (base attributes, magic) so it never re-rolls.
type ItemData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`           // unique within the character, never reused
	Version       uint32                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"` // the item table set it was made from (settings/item/000..)
	Genre         uint32                 `protobuf:"varint,3,opt,name=genre,proto3" json:"genre,omitempty"`     // ITEMGENRE
	Detail        uint32                 `protobuf:"varint,4,opt,name=detail,proto3" json:"detail,omitempty"`
	Particular    uint32                 `protobuf:"varint,5,opt,name=particular,proto3" json:"particular,omitempty"`
	Level         uint32                 `protobuf:"varint,6,opt,name=level,proto3" json:"level,omitempty"`
	Series        int32                  `protobuf:"varint,7,opt,name=series,proto3" json:"series,omitempty"`                      // -1 = none
	Count         uint32                 `protobuf:"varint,8,opt,name=count,proto3" json:"count,omitempty"`                        // stack
	Durability    int32                  `protobuf:"varint,9,opt,name=durability,proto3" json:"durability,omitempty"`              // -1 = never wears
	ExType        uint32                 `protobuf:"varint,10,opt,name=ex_type,json=exType,proto3" json:"ex_type,omitempty"`       // 0 normal, 1 gold, 2 platina, 3 purple
	GenParam      uint32                 `protobuf:"varint,11,opt,name=gen_param,json=genParam,proto3" json:"gen_param,omitempty"` // gold: row id; script item: row
	Group         uint32                 `protobuf:"varint,12,opt,name=group,proto3" json:"group,omitempty"`                       // gold: the set
	ExGroup       uint32                 `protobuf:"varint,13,opt,name=ex_group,json=exGroup,proto3" json:"ex_group,omitempty"`
	GroupSerial   uint32                 `protobuf:"varint,14,opt,name=group_serial,json=groupSerial,proto3" json:"group_serial,omitempty"`
	Base          []*ItemMagic           `protobuf:"bytes,15,rep,name=base,proto3" json:"base,omitempty"`
	Require       []*ItemMagic           `protobuf:"bytes,16,rep,name=require,proto3" json:"require,omitempty"`
	Magic         []*ItemMagic           `protobuf:"bytes,17,rep,name=magic,proto3" json:"magic,omitempty"`
	MagicEx       []*ItemMagic           `protobuf:"bytes,18,rep,name=magic_ex,json=magicEx,proto3" json:"magic_ex,omitempty"`
	Room          uint32                 `protobuf:"varint,19,opt,name=room,proto3" json:"room,omitempty"` // KItemRoom: 0 bag, 1 repository, 2 trade, 3 quick slots, 10 worn (x = part)
	X             uint32                 `protobuf:"varint,20,opt,name=x,proto3" json:"x,omitempty"`
	Y             uint32                 `protobuf:"varint,21,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemData) Reset() {
	*x = ItemData{}
	mi := &file_jx_role_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemData) ProtoMessage() {}

func (x *ItemData) ProtoReflect() protoreflect.Message {
	mi := &file_jx_role_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemData.ProtoReflect.Descriptor instead.
func (*ItemData) Descriptor() ([]byte, []int) {
	return file_jx_role_proto_rawDescGZIP(), []int{3}
}

func (x *ItemData) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ItemData) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ItemData) GetGenre() uint32 {
	if x != nil {
		return x.Genre
	}
	return 0
}

func (x *ItemData) GetDetail() uint32 {
	if x != nil {
		return x.Detail
	}
	return 0
}

func (x *ItemData) GetParticular() uint32 {
	if x != nil {
		return x.Particular
	}
	return 0
}

func (x *ItemData) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *ItemData) GetSeries() int32 {
	if x != nil {
		return x.Series
	}
	return 0
}

func (x *ItemData) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ItemData) GetDurability() int32 {
	if x != nil {
		return x.Durability
	}
	return 0
}

func (x *ItemData) GetExType() uint32 {
	if x != nil {
		return x.ExType
	}
	return 0
}

func (x *ItemData) GetGenParam() uint32 {
	if x != nil {
		return x.GenParam
	}
	return 0
}

func (x *ItemData) GetGroup() uint32 {
	if x != nil {
		return x.Group
	}
	return 0
}

func (x *ItemData) GetExGroup() uint32 {
	if x != nil {
		return x.ExGroup
	}
	return 0
}

func (x *ItemData) GetGroupSerial() uint32 {
	if x != nil {
		return x.GroupSerial
	}
	return 0
}

func (x *ItemData) GetBase() []*ItemMagic {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *ItemData) GetRequire() []*ItemMagic {
	if x != nil {
		return x.Require
	}
	return nil
}

func (x *ItemData) GetMagic() []*ItemMagic {
	if x != nil {
		return x.Magic
	}
	return nil
}

func (x *ItemData) GetMagicEx() []*ItemMagic {
	if x != nil {
		return x.MagicEx
	}
	return nil
}

func (x *ItemData) GetRoom() uint32 {
	if x != nil {
		return x.Room
	}
	return 0
}

func (x *ItemData) GetX() uint32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ItemData) GetY() uint32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// One skill of the character's KSkillList (jx_linux_y 0x080E48D0 writes {int16 id, int16 level,
// int32 exp}, KPlayer::LoadPlayerFightSkillList 0x080C0240 reads it back through KSkillList::Add);
// cells that live on increments only are not saved.
type RoleSkill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Level         uint32                 `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	Exp           uint32                 `protobuf:"varint,3,opt,name=exp,proto3" json:"exp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleSkill) Reset() {
	*x = RoleSkill{}
	mi := &file_jx_role_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleSkill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleSkill) ProtoMessage() {}

func (x *RoleSkill) ProtoReflect() protoreflect.Message {
	mi := &file_jx_role_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleSkill.ProtoReflect.Descriptor instead.
func (*RoleSkill) Descriptor() ([]byte, []int) {
	return file_jx_role_proto_rawDescGZIP(), []int{4}
}

func (x *RoleSkill) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleSkill) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *RoleSkill) GetExp() uint32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

// One saved task value of the character (KPlayerTask of the old core, the std::map at Player+0x809c+0x54c of jx_linux_y;
// KPlayer::SavePlayerTaskList 0x080BF1C0 writes the non-zero {int id, int value} pairs into TRoleData, LoadPlayerTaskList
// 0x080C0050 reads them back through SetSaveVal).  The temp values (m_nTaskTemp) are never saved.
type RoleTaskValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`       // 0..0x176f
	Value         int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"` // never 0 (a 0 erases the entry)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleTaskValue) Reset() {
	*x = RoleTaskValue{}
	mi := &file_jx_role_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleTaskValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleTaskValue) ProtoMessage() {}

func (x *RoleTaskValue) ProtoReflect() protoreflect.Message {
	mi := &file_jx_role_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleTaskValue.ProtoReflect.Descriptor instead.
func (*RoleTaskValue) Descriptor() ([]byte, []int) {
	return file_jx_role_proto_rawDescGZIP(), []int{5}
}

func (x *RoleTaskValue) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleTaskValue) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

// One event a script registered on the character (KPlayerEvent, Player+0x8064 of jx_linux_y: {word id, word count};
// the extra block of TRoleData keeps them, 0x080BEB60): AddPlayerEvent, counted by the kills of event_killnpc.txt
type RolePlayerEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"` // the kills so far
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolePlayerEvent) Reset() {
	*x = RolePlayerEvent{}
	mi := &file_jx_role_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolePlayerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePlayerEvent) ProtoMessage() {}

func (x *RolePlayerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_jx_role_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePlayerEvent.ProtoReflect.Descriptor instead.
func (*RolePlayerEvent) Descriptor() ([]byte, []int) {
	return file_jx_role_proto_rawDescGZIP(), []int{6}
}

func (x *RolePlayerEvent) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RolePlayerEvent) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type RoleData struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	PlayerId    uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	AccountId   uint64                 `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Name        string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"` // UTF-8, validated by the auth/persist layer
	Level       uint32                 `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	Exp         uint64                 `protobuf:"varint,5,opt,name=exp,proto3" json:"exp,omitempty"`
	Series      uint32                 `protobuf:"varint,6,opt,name=series,proto3" json:"series,omitempty"` // five elements (metal, wood, water, fire, earth) as in the old game
	Sex         uint32                 `protobuf:"varint,7,opt,name=sex,proto3" json:"sex,omitempty"`
	Faction     int32                  `protobuf:"varint,8,opt,name=faction,proto3" json:"faction,omitempty"` // KPlayerFaction::m_nCurFaction (KPlayer+0x59cc; cFaction of the DB record): 0..10, -1 = none
	Position    *RolePosition          `protobuf:"bytes,9,opt,name=position,proto3" json:"position,omitempty"`
	Stats       *RoleStats             `protobuf:"bytes,10,opt,name=stats,proto3" json:"stats,omitempty"`
	Items       []*ItemData            `protobuf:"bytes,11,rep,name=items,proto3" json:"items,omitempty"` // (RoleItem, the placeholder that stood here, was never written by anyone)
	CreatedAtMs uint64                 `protobuf:"varint,12,opt,name=created_at_ms,json=createdAtMs,proto3" json:"created_at_ms,omitempty"`
	LastLoginMs uint64                 `protobuf:"varint,13,opt,name=last_login_ms,json=lastLoginMs,proto3" json:"last_login_ms,omitempty"`
	PlayTimeS   uint64                 `protobuf:"varint,14,opt,name=play_time_s,json=playTimeS,proto3" json:"play_time_s,omitempty"`
	// Shape of this record.  persist.CurrentRoleVersion is what the running server writes; an
	// older record is upgraded on load (persist.MigrateRole), a newer one is refused instead of
	// being silently downgraded.  See docs/ADR-003-role-data.md.
	DataVersion uint32 `protobuf:"varint,15,opt,name=data_version,json=dataVersion,proto3" json:"data_version,omitempty"`
	FightMode   bool   `protobuf:"varint,16,opt,name=fight_mode,json=fightMode,proto3" json:"fight_mode,omitempty"` // KNpc::SetFightMode: in/out of combat stance (city gate traps)
	// Where the character was born (CharCreateReq.native_place, KRoleChiefInfo.NativePlaceId of the
	// old game): the map id of the starting village, the character's home for the revive rules.
	NativePlace uint32       `protobuf:"varint,17,opt,name=native_place,json=nativePlace,proto3" json:"native_place,omitempty"`
	NextItemId  uint32       `protobuf:"varint,18,opt,name=next_item_id,json=nextItemId,proto3" json:"next_item_id,omitempty"` // KItemList: the id the next item gets (ids never repeat within a character)
	Money       uint32       `protobuf:"varint,19,opt,name=money,proto3" json:"money,omitempty"`                               // in the bag (KItemList room_equipment money)
	BankMoney   uint32       `protobuf:"varint,20,opt,name=bank_money,json=bankMoney,proto3" json:"bank_money,omitempty"`      // in the repository
	Skills      []*RoleSkill `protobuf:"bytes,21,rep,name=skills,proto3" json:"skills,omitempty"`                              // the fight skill list (KSkillList; DBSkillData of the old server)
	// the revive point (KPlayer+0x20 map, +0x28 / +0x2c x, y: SetTempRevPos / SetRevPos): where KPlayer::Revive(0) puts
	// the character back; 0 = the spawn point of its map
	ReviveMap uint32 `protobuf:"varint,22,opt,name=revive_map,json=reviveMap,proto3" json:"revive_map,omitempty"`
	RevivePos *Vec2  `protobuf:"bytes,23,opt,name=revive_pos,json=revivePos,proto3" json:"revive_pos,omitempty"`
	// the id of the revive point (KPlayer+0x14: the Bishop's irevivalx of a fresh character = one of its village's ids in
	// revivepos.ini, or SetRevPos(map, ref) later); the zone resolves it through revive_pos.json; 0 = none
	ReviveRef uint32 `protobuf:"varint,24,opt,name=revive_ref,json=reviveRef,proto3" json:"revive_ref,omitempty"`
	// KPlayerFaction (Core/Src/KPlayerFaction.h; KPlayer+0x59cc..+0x59d8 of jx_linux_y): the faction last added (m_nLastAddFaction,
	// +0x59d4, the one the client's skill book shows the branches of) and how many times a faction was joined (m_nAddTimes,
	// +0x59d8: 0 = never, the name of a character without faction depends on it); m_nFirstAddFaction is not saved (LoadFrom 0x080C1A62)
	FactionLast  int32  `protobuf:"varint,25,opt,name=faction_last,json=factionLast,proto3" json:"faction_last,omitempty"`
	FactionCount uint32 `protobuf:"varint,26,opt,name=faction_count,json=factionCount,proto3" json:"faction_count,omitempty"`
	// KPlayerPK (Player+0x5a50): the PK state 0..2 (the save 0x080BFCDD writes the byte), the PK value 0..10 (0x080BFCEF), the
	// ForbidChangePK lock
	PkState  uint32 `protobuf:"varint,27,opt,name=pk_state,json=pkState,proto3" json:"pk_state,omitempty"`
	PkValue  uint32 `protobuf:"varint,28,opt,name=pk_value,json=pkValue,proto3" json:"pk_value,omitempty"`
	PkLocked bool   `protobuf:"varint,29,opt,name=pk_locked,json=pkLocked,proto3" json:"pk_locked,omitempty"`
	// the leadership (m_dwLeadExp +0x596c / m_dwLeadLevel +0x5970 of KPlayer): the level says how many a team led by the
	// character can hold (level_lead_exp.txt col 3, KTeam::CalcCaptainPower 0x080CC960); 0 = level 1
	LeadExp       uint64             `protobuf:"varint,30,opt,name=lead_exp,json=leadExp,proto3" json:"lead_exp,omitempty"`
	LeadLevel     uint32             `protobuf:"varint,31,opt,name=lead_level,json=leadLevel,proto3" json:"lead_level,omitempty"`
	TaskValues    []*RoleTaskValue   `protobuf:"bytes,32,rep,name=task_values,json=taskValues,proto3" json:"task_values,omitempty"` // the task values the scripts keep (GetTask / SetTask; docs/LINUX-SERVER.md §21)
	Events        []*RolePlayerEvent `protobuf:"bytes,33,rep,name=events,proto3" json:"events,omitempty"`                           // the kill events registered on the character (AddPlayerEvent; docs/LINUX-SERVER.md §23)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleData) Reset() {
	*x = RoleData{}
	mi := &file_jx_role_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleData) ProtoMessage() {}

func (x *RoleData) ProtoReflect() protoreflect.Message {
	mi := &file_jx_role_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleData.ProtoReflect.Descriptor instead.
func (*RoleData) Descriptor() ([]byte, []int) {
	return file_jx_role_proto_rawDescGZIP(), []int{7}
}

func (x *RoleData) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *RoleData) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *RoleData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleData) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *RoleData) GetExp() uint64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *RoleData) GetSeries() uint32 {
	if x != nil {
		return x.Series
	}
	return 0
}

func (x *RoleData) GetSex() uint32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *RoleData) GetFaction() int32 {
	if x != nil {
		return x.Faction
	}
	return 0
}

func (x *RoleData) GetPosition() *RolePosition {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *RoleData) GetStats() *RoleStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *RoleData) GetItems() []*ItemData {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *RoleData) GetCreatedAtMs() uint64 {
	if x != nil {
		return x.CreatedAtMs
	}
	return 0
}

func (x *RoleData) GetLastLoginMs() uint64 {
	if x != nil {
		return x.LastLoginMs
	}
	return 0
}

func (x *RoleData) GetPlayTimeS() uint64 {
	if x != nil {
		return x.PlayTimeS
	}
	return 0
}

func (x *RoleData) GetDataVersion() uint32 {
	if x != nil {
		return x.DataVersion
	}
	return 0
}

func (x *RoleData) GetFightMode() bool {
	if x != nil {
		return x.FightMode
	}
	return false
}

func (x *RoleData) GetNativePlace() uint32 {
	if x != nil {
		return x.NativePlace
	}
	return 0
}

func (x *RoleData) GetNextItemId() uint32 {
	if x != nil {
		return x.NextItemId
	}
	return 0
}

func (x *RoleData) GetMoney() uint32 {
	if x != nil {
		return x.Money
	}
	return 0
}

func (x *RoleData) GetBankMoney() uint32 {
	if x != nil {
		return x.BankMoney
	}
	return 0
}

func (x *RoleData) GetSkills() []*RoleSkill {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *RoleData) GetReviveMap() uint32 {
	if x != nil {
		return x.ReviveMap
	}
	return 0
}

func (x *RoleData) GetRevivePos() *Vec2 {
	if x != nil {
		return x.RevivePos
	}
	return nil
}

func (x *RoleData) GetReviveRef() uint32 {
	if x != nil {
		return x.ReviveRef
	}
	return 0
}

func (x *RoleData) GetFactionLast() int32 {
	if x != nil {
		return x.FactionLast
	}
	return 0
}

func (x *RoleData) GetFactionCount() uint32 {
	if x != nil {
		return x.FactionCount
	}
	return 0
}

func (x *RoleData) GetPkState() uint32 {
	if x != nil {
		return x.PkState
	}
	return 0
}

func (x *RoleData) GetPkValue() uint32 {
	if x != nil {
		return x.PkValue
	}
	return 0
}

func (x *RoleData) GetPkLocked() bool {
	if x != nil {
		return x.PkLocked
	}
	return false
}

func (x *RoleData) GetLeadExp() uint64 {
	if x != nil {
		return x.LeadExp
	}
	return 0
}

func (x *RoleData) GetLeadLevel() uint32 {
	if x != nil {
		return x.LeadLevel
	}
	return 0
}

func (x *RoleData) GetTaskValues() []*RoleTaskValue {
	if x != nil {
		return x.TaskValues
	}
	return nil
}

func (x *RoleData) GetEvents() []*RolePlayerEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_jx_role_proto protoreflect.FileDescriptor

const file_jx_role_proto_rawDesc = "" +
	"\n" +
	"\rjx/role.proto\x12\x05jx.pb\x1a\x0fjx/common.proto\"]\n" +
	"\fRolePosition\x12\x17\n" +
	"\azone_id\x18\x01 \x01(\rR\x06zoneId\x12\x1d\n" +
	"\x03pos\x18\x02 \x01(\v2\v.jx.pb.Vec2R\x03pos\x12\x15\n" +
	"\x06map_id\x18\x03 \x01(\rR\x05mapId\"\xad\x03\n" +
	"\tRoleStats\x12\x0e\n" +
	"\x02hp\x18\x01 \x01(\x05R\x02hp\x12\x15\n" +
	"\x06hp_max\x18\x02 \x01(\x05R\x05hpMax\x12\x0e\n" +
	"\x02mp\x18\x03 \x01(\x05R\x02mp\x12\x15\n" +
	"\x06mp_max\x18\x04 \x01(\x05R\x05mpMax\x12\x18\n" +
	"\astamina\x18\x05 \x01(\x05R\astamina\x12\x1f\n" +
	"\vstamina_max\x18\x06 \x01(\x05R\n" +
	"staminaMax\x12\x1a\n" +
	"\bstrength\x18\a \x01(\x05R\bstrength\x12\x1c\n" +
	"\tdexterity\x18\b \x01(\x05R\tdexterity\x12\x1a\n" +
	"\bvitality\x18\t \x01(\x05R\bvitality\x12\x16\n" +
	"\x06energy\x18\n" +
	" \x01(\x05R\x06energy\x12\x1d\n" +
	"\n" +
	"move_speed\x18\v \x01(\x05R\tmoveSpeed\x12\x14\n" +
	"\x05lucky\x18\f \x01(\x05R\x05lucky\x12'\n" +
	"\x0fattribute_point\x18\r \x01(\x05R\x0eattributePoint\x12\x1f\n" +
	"\vskill_point\x18\x0e \x01(\x05R\n" +
	"skillPoint\x12\x16\n" +
	"\x06reborn\x18\x0f \x01(\rR\x06reborn\x12\x12\n" +
	"\x04camp\x18\x10 \x01(\rR\x04camp\"5\n" +
	"\tItemMagic\x12\x12\n" +
	"\x04type\x18\x01 \x01(\rR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x03(\x05R\x05value\"\xc7\x04\n" +
	"\bItemData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\x12\x14\n" +
	"\x05genre\x18\x03 \x01(\rR\x05genre\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\rR\x06detail\x12\x1e\n" +
	"\n" +
	"particular\x18\x05 \x01(\rR\n" +
	"particular\x12\x14\n" +
	"\x05level\x18\x06 \x01(\rR\x05level\x12\x16\n" +
	"\x06series\x18\a \x01(\x05R\x06series\x12\x14\n" +
	"\x05count\x18\b \x01(\rR\x05count\x12\x1e\n" +
	"\n" +
	"durability\x18\t \x01(\x05R\n" +
	"durability\x12\x17\n" +
	"\aex_type\x18\n" +
	" \x01(\rR\x06exType\x12\x1b\n" +
	"\tgen_param\x18\v \x01(\rR\bgenParam\x12\x14\n" +
	"\x05group\x18\f \x01(\rR\x05group\x12\x19\n" +
	"\bex_group\x18\r \x01(\rR\aexGroup\x12!\n" +
	"\fgroup_serial\x18\x0e \x01(\rR\vgroupSerial\x12$\n" +
	"\x04base\x18\x0f \x03(\v2\x10.jx.pb.ItemMagicR\x04base\x12*\n" +
	"\arequire\x18\x10 \x03(\v2\x10.jx.pb.ItemMagicR\arequire\x12&\n" +
	"\x05magic\x18\x11 \x03(\v2\x10.jx.pb.ItemMagicR\x05magic\x12+\n" +
	"\bmagic_ex\x18\x12 \x03(\v2\x10.jx.pb.ItemMagicR\amagicEx\x12\x12\n" +
	"\x04room\x18\x13 \x01(\rR\x04room\x12\f\n" +
	"\x01x\x18\x14 \x01(\rR\x01x\x12\f\n" +
	"\x01y\x18\x15 \x01(\rR\x01y\"C\n" +
	"\tRoleSkill\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05level\x18\x02 \x01(\rR\x05level\x12\x10\n" +
	"\x03exp\x18\x03 \x01(\rR\x03exp\"5\n" +
	"\rRoleTaskValue\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value\"7\n" +
	"\x0fRolePlayerEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\"\xba\b\n" +
	"\bRoleData\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x04R\taccountId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x04 \x01(\rR\x05level\x12\x10\n" +
	"\x03exp\x18\x05 \x01(\x04R\x03exp\x12\x16\n" +
	"\x06series\x18\x06 \x01(\rR\x06series\x12\x10\n" +
	"\x03sex\x18\a \x01(\rR\x03sex\x12\x18\n" +
	"\afaction\x18\b \x01(\x05R\afaction\x12/\n" +
	"\bposition\x18\t \x01(\v2\x13.jx.pb.RolePositionR\bposition\x12&\n" +
	"\x05stats\x18\n" +
	" \x01(\v2\x10.jx.pb.RoleStatsR\x05stats\x12%\n" +
	"\x05items\x18\v \x03(\v2\x0f.jx.pb.ItemDataR\x05items\x12\"\n" +
	"\rcreated_at_ms\x18\f \x01(\x04R\vcreatedAtMs\x12\"\n" +
	"\rlast_login_ms\x18\r \x01(\x04R\vlastLoginMs\x12\x1e\n" +
	"\vplay_time_s\x18\x0e \x01(\x04R\tplayTimeS\x12!\n" +
	"\fdata_version\x18\x0f \x01(\rR\vdataVersion\x12\x1d\n" +
	"\n" +
	"fight_mode\x18\x10 \x01(\bR\tfightMode\x12!\n" +
	"\fnative_place\x18\x11 \x01(\rR\vnativePlace\x12 \n" +
	"\fnext_item_id\x18\x12 \x01(\rR\n" +
	"nextItemId\x12\x14\n" +
	"\x05money\x18\x13 \x01(\rR\x05money\x12\x1d\n" +
	"\n" +
	"bank_money\x18\x14 \x01(\rR\tbankMoney\x12(\n" +
	"\x06skills\x18\x15 \x03(\v2\x10.jx.pb.RoleSkillR\x06skills\x12\x1d\n" +
	"\n" +
	"revive_map\x18\x16 \x01(\rR\treviveMap\x12*\n" +
	"\n" +
	"revive_pos\x18\x17 \x01(\v2\v.jx.pb.Vec2R\trevivePos\x12\x1d\n" +
	"\n" +
	"revive_ref\x18\x18 \x01(\rR\treviveRef\x12!\n" +
	"\ffaction_last\x18\x19 \x01(\x05R\vfactionLast\x12#\n" +
	"\rfaction_count\x18\x1a \x01(\rR\ffactionCount\x12\x19\n" +
	"\bpk_state\x18\x1b \x01(\rR\apkState\x12\x19\n" +
	"\bpk_value\x18\x1c \x01(\rR\apkValue\x12\x1b\n" +
	"\tpk_locked\x18\x1d \x01(\bR\bpkLocked\x12\x19\n" +
	"\blead_exp\x18\x1e \x01(\x04R\aleadExp\x12\x1d\n" +
	"\n" +
	"lead_level\x18\x1f \x01(\rR\tleadLevel\x125\n" +
	"\vtask_values\x18  \x03(\v2\x14.jx.pb.RoleTaskValueR\n" +
	"taskValues\x12.\n" +
	"\x06events\x18! \x03(\v2\x16.jx.pb.RolePlayerEventR\x06eventsB6Z4github.com/JXGAME04/DUANGODOT/next/services/pkg/jxpbb\x06proto3"

var (
	file_jx_role_proto_rawDescOnce sync.Once
	file_jx_role_proto_rawDescData []byte
)

func file_jx_role_proto_rawDescGZIP() []byte {
	file_jx_role_proto_rawDescOnce.Do(func() {
		file_jx_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jx_role_proto_rawDesc), len(file_jx_role_proto_rawDesc)))
	})
	return file_jx_role_proto_rawDescData
}

var file_jx_role_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_jx_role_proto_goTypes = []any{
	(*RolePosition)(nil),    // 0: jx.pb.RolePosition
	(*RoleStats)(nil),       // 1: jx.pb.RoleStats
	(*ItemMagic)(nil),       // 2: jx.pb.ItemMagic
	(*ItemData)(nil),        // 3: jx.pb.ItemData
	(*RoleSkill)(nil),       // 4: jx.pb.RoleSkill
	(*RoleTaskValue)(nil),   // 5: jx.pb.RoleTaskValue
	(*RolePlayerEvent)(nil), // 6: jx.pb.RolePlayerEvent
	(*RoleData)(nil),        // 7: jx.pb.RoleData
	(*Vec2)(nil),            // 8: jx.pb.Vec2
}
var file_jx_role_proto_depIdxs = []int32{
	8,  // 0: jx.pb.RolePosition.pos:type_name -> jx.pb.Vec2
	2,  // 1: jx.pb.ItemData.base:type_name -> jx.pb.ItemMagic
	2,  // 2: jx.pb.ItemData.require:type_name -> jx.pb.ItemMagic
	2,  // 3: jx.pb.ItemData.magic:type_name -> jx.pb.ItemMagic
	2,  // 4: jx.pb.ItemData.magic_ex:type_name -> jx.pb.ItemMagic
	0,  // 5: jx.pb.RoleData.position:type_name -> jx.pb.RolePosition
	1,  // 6: jx.pb.RoleData.stats:type_name -> jx.pb.RoleStats
	3,  // 7: jx.pb.RoleData.items:type_name -> jx.pb.ItemData
	4,  // 8: jx.pb.RoleData.skills:type_name -> jx.pb.RoleSkill
	8,  // 9: jx.pb.RoleData.revive_pos:type_name -> jx.pb.Vec2
	5,  // 10: jx.pb.RoleData.task_values:type_name -> jx.pb.RoleTaskValue
	6,  // 11: jx.pb.RoleData.events:type_name -> jx.pb.RolePlayerEvent
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_jx_role_proto_init() }
func file_jx_role_proto_init() {
	if File_jx_role_proto != nil {
		return
	}
	file_jx_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jx_role_proto_rawDesc), len(file_jx_role_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_jx_role_proto_goTypes,
		DependencyIndexes: file_jx_role_proto_depIdxs,
		MessageInfos:      file_jx_role_proto_msgTypes,
	}.Build()
	File_jx_role_proto = out.File
	file_jx_role_proto_goTypes = nil
	file_jx_role_proto_depIdxs = nil
}
